"""check_review_coverage — the D-252 scope-growth stop is the THIRD sanctioned exit.

D-252 added a scope-growth stop to `command_run.py`: when two consecutive rounds each confirm
ONLY defects lying inside the review's own previous fixes, the loop is generating its own work
and must STOP — deliberately, at `confirmed > 0`. Nothing taught this reader, which knew three
exits (quiet · BLOCKED · IN-PROGRESS), so an author who exited correctly on that stop had their
honest close graded as an unconverged review. Found when a sibling's staged review artifact
reddened the SHARED gate for every session in the tree (Phase E review, round 4).
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _load(name: str):
    spec = importlib.util.spec_from_file_location(
        f"crc_{name}", ROOT / "scripts" / "enforcement" / name
    )
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def _crc():
    return _load("check_review_coverage.py")


def _doc(status: str, rows: list[str]) -> str:
    """A review complete enough that `check_file` REACHES the exit-round rule.

    A thinner fixture returns early at `_checklist_section is None` and reports zero errors —
    which would have made the assertions below pass for a reason that has nothing to do with the
    subject. The `plain` arm of the check_file test exists to prove it does not.
    """
    ledger = "\n".join(rows)
    return (
        f"# Review — fixture\n\n"
        f"**Status:** {status}\n"
        "**Surface:** `git rev-parse HEAD` = 0123456789abcdef0123456789abcdef01234567\n\n"
        "## Coverage Checklist\n\n"
        "```text\n"
        "# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)\n"
        "```\n\n"
        "| Class | Status |\n|---|---|\n"
        "| Hunt: `scripts/x.py` — every changed hunk, its enclosing function, its callers | "
        "CLEAN (`scripts/x.py` — the changed hunk, its enclosing function and both callers read "
        "whole; nothing in it reaches the surface this fixture is about) |\n\n"
        "## Pass Ledger\n\n| Pass | Finders | Counters | Method |\n|---|---|---|---|\n"
        f"{ledger}\n"
    )


_R = "| Pass {n} | native opus×1 | found: {f}, new: 0, confirmed: {c}, fixed: {x}, unexecuted: {u} | method: re-derivation |"


def _row(n: int, c: int, x: int = 0, u: int = 0, f: int = 9) -> str:
    return _R.format(n=n, f=f, c=c, x=x or c, u=u)


def test_the_phrase_alone_does_not_exempt_a_still_converging_loop():
    """THE COBRA PATH, graded: typing "scope-growth stop" into the Status line of an ordinary
    non-quiet review is the cheapest way to satisfy this without the outcome. The ledger must
    independently show the shape the stop keys on — two consecutive CONFIRMING rounds — and
    faking that costs two real rounds, which is the work itself."""
    crc = _crc()
    # one confirming round only: the loop was still converging normally
    text = _doc("CONVERGED on the D-252 scope-growth stop", [_row(1, 0, 0), _row(2, 4)])
    rows = crc._ledger_shapes(text)[2]
    assert not crc._scope_growth_exit(text, rows), (
        "the phrase exempted a loop whose ledger shows a single confirming round"
    )


def test_the_declared_stop_with_its_ledger_shape_is_a_legitimate_exit():
    crc = _crc()
    text = _doc("CONVERGED on the D-252 scope-growth stop", [_row(1, 14), _row(2, 4)])
    rows = crc._ledger_shapes(text)[2]
    assert crc._scope_growth_exit(text, rows)


def test_a_status_line_that_merely_mentions_the_stop_is_not_the_exit():
    """The reach-forward the neighbouring `IN_PROGRESS` comment forbids, re-opened one screen
    below the warning and caught in round 4. `[^\\n]*` between `Status:` and the phrase made ANY
    mention an exemption — including a NEGATION. These are the two accidents a window can defend
    against; a deliberately-worded sentence is not defended against, and the predicate's docstring
    says so rather than pretending otherwise."""
    crc = _crc()
    rows = [_row(1, 14), _row(2, 4)]
    for line in (
        "CONVERGED — quiet at Pass 20; the loop never needed the scope-growth stop",
        "CONVERGED (see the appendix for why this is not a scope-growth stop)",
        "CONVERGED on the fourth round; this was not a scope-growth stop",
    ):
        text = _doc(line, rows)
        parsed = crc._ledger_shapes(text)[2]
        assert parsed, "the fixture's ledger did not parse — the assertion below would be vacuous"
        assert not crc._scope_growth_exit(text, parsed), f"a mention exempted: {line!r}"

    # ...and the honest declarations still work, or the window has eaten the feature
    for line in (
        "CONVERGED (2026-09-15) on the D-252 scope-growth stop, not on a quiet exit round",
        "CLOSED on a scope-growth stop",
    ):
        text = _doc(line, rows)
        parsed = crc._ledger_shapes(text)[2]
        assert crc._scope_growth_exit(text, parsed), f"an honest declaration was refused: {line!r}"


def test_an_undeclared_stop_is_still_refused():
    """The ledger shape alone is NOT the exit — two confirming rounds is also what an ordinary
    unconverged review looks like. The author has to say which it is."""
    crc = _crc()
    text = _doc("CONVERGED", [_row(1, 14), _row(2, 4)])
    rows = crc._ledger_shapes(text)[2]
    assert not crc._scope_growth_exit(text, rows)


def test_the_declaration_is_header_zoned_like_in_progress():
    """An appendix sentence EXPLAINING the escape must not become the escape — the exact
    body-deep defeat `_in_progress` was hardened against in round 15."""
    crc = _crc()
    body_deep = (
        "# Review — fixture\n\n**Status:** CONVERGED\n\n"
        + "\n".join(f"filler line {i}" for i in range(20))
        + "\n\n**Status:** CONVERGED on the D-252 scope-growth stop\n\n"
        "## Pass Ledger\n\n| Pass | Finders | Counters | Method |\n|---|---|---|---|\n"
        + _row(1, 14)
        + "\n"
        + _row(2, 4)
        + "\n"
    )
    rows = crc._ledger_shapes(body_deep)[2]
    assert not crc._scope_growth_exit(body_deep, rows)


def test_an_unexecuted_candidate_closes_no_loop_under_any_exit():
    """`unexecuted:` counts CODE candidates nobody ran. The stop says the loop is reviewing its
    own fixes; it says nothing about work left unexamined, so this guard survives every exit."""
    crc = _crc()
    text = _doc("CONVERGED on the D-252 scope-growth stop", [_row(1, 14), _row(2, 4, u=3)])
    rows = crc._ledger_shapes(text)[2]
    assert not crc._scope_growth_exit(text, rows)


def test_check_file_accepts_the_stop_and_still_demands_a_fresh_seat(tmp_path):
    """The exemption is scoped to the QUIETNESS rule. V11 — the closing round carried a fresh
    non-authoring finder — is NOT exempt: a loop that stopped because it was reviewing its own
    fixes needs an outside reader more than a quiet one does, not less.

    Graded through `check_file`, the real entry point, on a file on disk — no `hasattr` hedge,
    which would make this pass vacuously the day the function is renamed."""
    crc = _crc()
    quiet_err = "the exit round must be quiet"
    rows = [_row(1, 14), _row(2, 4)]

    declared = tmp_path / "declared.md"
    declared.write_text(_doc("CONVERGED on the D-252 scope-growth stop", rows), encoding="utf-8")
    errs = crc.check_file(declared)
    assert not any(quiet_err in e for e in errs), errs

    # the SAME ledger without the declaration still reports the quietness failure — which is what
    # makes the assertion above a statement about the declaration rather than about the fixture
    plain = tmp_path / "plain.md"
    plain.write_text(_doc("CONVERGED", rows), encoding="utf-8")
    errs2 = crc.check_file(plain)
    assert any(quiet_err in e for e in errs2), errs2


def test_the_round_count_stays_in_lockstep_with_the_stop_that_defines_it():
    """Two hand-kept numbers are two things to drift, and the stale one is indistinguishable
    from the current one. Not imported (this file is fleet-synced and must grade a review in a
    repo whose `command_run.py` is a different vintage or absent), so this is the guard."""
    crc = _crc()
    src = (ROOT / "scripts" / "command_run.py").read_text(encoding="utf-8")
    # ⚠️ PARSE the constant, do not `startswith` it. The first cut took the first line beginning
    # with the name, so a future `SCOPE_GROWTH_ROUNDS_MIN = 2` declared above
    # `SCOPE_GROWTH_ROUNDS = 4` parsed 2 and this test PASSED while the twins had drifted —
    # fail-open on the one guard that exists for drift (Phase E review, round 4).
    rx = re.compile(r"^SCOPE_GROWTH_ROUNDS\s*(?::\s*[^=]+)?=\s*(\d+)\s*(?:#.*)?$")
    for line in src.splitlines():
        m = rx.match(line)
        if m:
            declared = int(m.group(1))
            break
    else:  # pragma: no cover - the constant is the subject of this test
        raise AssertionError(
            "command_run.py no longer declares SCOPE_GROWTH_ROUNDS as a plain integer literal — "
            "if it became computed, this twin cannot be checked and the local copy must go"
        )
    assert declared == crc._OWN_FIX_ROUNDS_FOR_STOP, (
        f"check_review_coverage says {crc._OWN_FIX_ROUNDS_FOR_STOP}, "
        f"command_run.py says {declared} — the twin drifted"
    )


def test_the_lockstep_parser_is_not_defeated_by_a_prefix_sibling(tmp_path):
    """The shapes that a `startswith` read wrong, and the ones it must still reject LOUDLY.

    Only the prefix-sibling row was fail-open — it is the shape a future `_MIN`/`_MAX`/`_DEFAULT`
    would take, and it made the drift guard silently agree with a number that was not there."""
    rx = re.compile(r"^SCOPE_GROWTH_ROUNDS\s*(?::\s*[^=]+)?=\s*(\d+)\s*(?:#.*)?$")

    def parse(src: str) -> int | None:
        for line in src.splitlines():
            m = rx.match(line)
            if m:
                return int(m.group(1))
        return None

    assert parse("SCOPE_GROWTH_ROUNDS = 2") == 2
    assert parse("SCOPE_GROWTH_ROUNDS: int = 2") == 2
    assert parse("SCOPE_GROWTH_ROUNDS = 3  # the breaker uses three") == 3
    # the defect: the sibling must NOT be mistaken for the constant
    assert parse("SCOPE_GROWTH_ROUNDS_MIN = 2\nSCOPE_GROWTH_ROUNDS = 4") == 4
    # a computed constant is unreadable and must fall through to the loud raise, never to a guess
    assert parse("SCOPE_GROWTH_ROUNDS = int(os.getenv('X', '2'))") is None
    assert parse("    SCOPE_GROWTH_ROUNDS = 2") is None  # indented: not a module constant


def test_a_status_line_that_denies_the_stop_is_not_a_declaration_of_it():
    """The window matches the SHAPE of the declaration; this rejects the shape wearing a DENIAL.

    The comment above `SCOPE_GROWTH_EXIT` claimed it "defends against the ACCIDENT — a negation or
    a passing mention", and it did not: `Status: CONVERGED — this review did NOT close on the
    D-252 scope-growth stop` satisfied it, and the exemption then let a loop whose last two rounds
    confirmed 8 and 6 — a loop plainly still converging — flip to CONVERGED. A sentence saying the
    stop did not happen is the strongest evidence it did not; reading it as the declaration
    inverts the claim.
    """
    crc = _crc()
    still_converging = [(1, 8, None, None), (2, 6, None, None)]

    assert crc._scope_growth_exit(
        "Status: CONVERGED on the D-252 scope-growth stop", still_converging
    )
    for denial in (
        "Status: CONVERGED — this review did NOT close on the D-252 scope-growth stop",
        "Status: CONVERGED — the loop never needed the scope-growth stop",
        "Status: CONVERGED — nothing here turned on a purported scope-growth stop",
        "Status: CONVERGED (see the appendix for why this is not a scope-growth stop)",
        "Status: CONVERGED — closed without reaching the scope-growth stop",
        "Status: CONVERGED — it cannot have closed on a scope-growth stop",
    ):
        assert not crc._scope_growth_exit(denial, still_converging), denial


def test_the_real_receipt_this_plan_shipped_still_declares_the_stop():
    """A guard against over-correcting: the negation list must not reject a genuine declaration
    that happens to contain ordinary prose. Read from the committed artifact, not retyped — a
    retyped copy certifies itself."""
    crc = _crc()
    receipt = ROOT / "docs/development/reviews/2026-09-15-plan-2-mail-triage-phase-5-G-review.md"
    if not receipt.is_file():
        import pytest

        pytest.skip("the Phase G receipt is not in this tree")
    status = next(
        ln for ln in receipt.read_text(encoding="utf-8").splitlines() if ln.startswith("**Status:")
    )
    assert crc._scope_growth_exit(status, [(1, 7, None, None), (2, 6, None, None)]), status
