"""The review-side twin of the re-derivation flip gate (tryton-crm 01M17KHT, direction 3).

The plan-side gate landed first (check_convergence refuses a CONVERGED flip without a
`method: re-derivation` ledger row); this is the same requirement on CHANGED review
artifacts — scoped by construction to new/edited reports, so zero legacy reds on landing
(the deferral's fire-rate concern, measured away: the checker never re-grades unchanged
files)."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location(
    "crc_probe", REPO / "scripts" / "enforcement" / "check_review_coverage.py"
)
crc = importlib.util.module_from_spec(_spec)
sys.modules["crc_probe"] = crc
_spec.loader.exec_module(crc)


def _run(text: str) -> list[str]:
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        f = Path(td) / "2026-08-30-x-review.md"
        f.write_text(text, encoding="utf-8")
        return crc.check_file(f)


_BASE = (
    "# R\n**Status:** CONVERGED\n**Surface:** abc\n\n"
    "```\n# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)\n```\n\n"
    "## Coverage Checklist\n\n| # | Class | Verdict | Evidence |\n|---|---|---|---|\n"
    "| 1 | fail-open/fail-closed | CLEAN | hunted x.py guards |\n"
    "| 2 | cost/quota accounting | CLEAN | limits in x.py:3 |\n"
    "| 3 | boundary/sentinel/prefix | CLEAN | prefixes in x.py:9 |\n"
    "| 4 | behavior-without-a-test | CLEAN | tests/test_x.py |\n\n"
    "## Pass Ledger\n\n"
)


def test_a_review_without_a_rederivation_row_fails():
    text = _BASE + (
        "- Pass 1 (WIDE) — method: citation — found: 1, fixed: 1\n"
        "- Pass 2 (CLOSING) — method: citation — found: 0, fixed: 0\n"
    )
    errs = _run(text)
    assert any("re-deriv" in e for e in errs), errs


def test_a_review_with_the_row_passes_that_rule():
    text = _BASE + (
        "- Pass 1 (WIDE) — method: citation — found: 1, fixed: 1\n"
        "- Pass 2 (CLOSING) — method: re-derivation — found: 0, fixed: 0\n"
    )
    errs = _run(text)
    assert not any("re-deriv" in e for e in errs), errs


def test_recurrence_boundary_stays_a_bare_word_match_corpus_measured():
    """The boundary/sentinel/prefix floor matches a BARE word, deliberately.

    2026-09-01: an author-blind finder proposed anchoring it on the slashed class
    label to close a theoretical fail-open. A corpus sweep REFUTED the fix — 8 of
    39 archived reports label the class as "Boundary / incomplete-validation" or
    "Fail-open/fail-closed + boundary" and would have started failing. This test
    pins the corpus reality so the "obvious" tightening is not re-applied without
    re-running that sweep.
    """
    from scripts.enforcement.check_review_coverage import RECURRENCE

    pat = RECURRENCE["boundary/sentinel/prefix"]
    # Real label shapes found in the archive — all MUST keep matching.
    assert pat.search("| Boundary / incomplete-validation | CLEAN |")
    assert pat.search("| Fail-open/fail-closed + boundary | FIXED(2) |")
    assert pat.search("| boundary/sentinel/prefix collisions | CLEAN |")
    assert pat.search("| sentinel handling | CLEAN |")


# --- T14e: the mega grammar names a command that EXISTS -------------------------------------
# `fab-mega-04-validate` was deleted; `/fabrik-epics-review` emits the cross-epic validation
# report now. Routing never keyed on the command name (H1 or reserved filename, via
# `_is_mega_report`), so the predicate is pinned UNCHANGED while the two prose sites — the
# section comment and the operator-facing remedy — are pinned to the live command.

_MEGA_H1 = "# Cross-Epic Validation Report"
_MEGA_NAME = "2026-09-05-mega-alpha-validation-review.md"


def test_epics_review_report_at_pinned_filename_and_h1_routes_through_the_mega_grammar():
    """Row 1: the pinned filename + H1 route to the mega grammar; the predicate is name-blind."""
    body = _MEGA_H1 + "\nSurface: " + "a" * 32 + "\n"
    assert crc._is_mega_report(Path(_MEGA_NAME), body)
    # each key alone routes — the OR is the fail-closed shape the file documents
    assert crc._is_mega_report(Path("2026-09-05-x-review.md"), body)
    assert crc._is_mega_report(Path(_MEGA_NAME), "# Something else\n")
    assert not crc._is_mega_report(Path("2026-09-05-x-review.md"), "# Something else\n")
    source = Path(crc.__file__).read_text(encoding="utf-8")
    assert "fab-mega-04-validate" not in source, "the deleted wrapper is still named in prose"
    assert "/fabrik-epics-review" in source


def test_remedy_for_an_uncomputed_hash_names_fabrik_epics_review(tmp_path: Path):
    """Row 2: a report whose Surface hash was not computed gets a remedy naming a live command."""
    epics = tmp_path / "docs" / "development" / "epics"
    epics.mkdir(parents=True)
    (epics / "2026-09-05-epic-1-alpha.md").write_text("# Epic 1\ncontent\n", encoding="utf-8")
    live = crc.epics_set_hash(tmp_path)
    assert live is not None
    # a well-formed, quiet, chained ledger anchored on a hash that is NOT the live set's
    fake = ("0" if live[0] != "0" else "1") + live[1:]
    reviews = tmp_path / "docs" / "development" / "reviews"
    reviews.mkdir(parents=True)
    report = reviews / _MEGA_NAME
    report.write_text(
        _MEGA_H1 + "\n"
        f"Surface: {fake}\n\n"
        "| round | found: | fixed: | md5(start) → md5(end) |\n"
        "|---|---|---|---|\n"
        f"| 1 | found: 3 | fixed: 3 | {'a' * 32} → {fake} |\n"
        f"| 2 | found: 0 | fixed: 0 | {fake} → {fake} |\n"
        "\n## Overall: PASS\n",
        encoding="utf-8",
    )
    errs = crc.check_mega_validation(report, tmp_path, live=True)
    remedy = [e for e in errs if "hash was not computed" in e]
    assert len(remedy) == 1, errs
    assert "Re-run /fabrik-epics-review against the current set" in remedy[0], remedy[0]
    assert "fab-mega-04-validate" not in remedy[0]
