"""check_review_coverage — the D-252 scope-growth stop is the THIRD sanctioned exit.

D-252 added a scope-growth stop to `command_run.py`: when two consecutive rounds each confirm
ONLY defects lying inside the review's own previous fixes, the loop is generating its own work
and must STOP — deliberately, at `confirmed > 0`. Nothing taught this reader, which knew three
exits (quiet · BLOCKED · IN-PROGRESS), so an author who exited correctly on that stop had their
honest close graded as an unconverged review. Found when a sibling's staged review artifact
reddened the SHARED gate for every session in the tree (Phase E review, round 4).
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _load(name: str):
    spec = importlib.util.spec_from_file_location(
        f"crc_{name}", ROOT / "scripts" / "enforcement" / name
    )
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def _crc():
    return _load("check_review_coverage.py")


def _doc(status: str, rows: list[str]) -> str:
    """A review complete enough that `check_file` REACHES the exit-round rule.

    A thinner fixture returns early at `_checklist_section is None` and reports zero errors —
    which would have made the assertions below pass for a reason that has nothing to do with the
    subject. The `plain` arm of the check_file test exists to prove it does not.
    """
    ledger = "\n".join(rows)
    return (
        f"# Review — fixture\n\n"
        f"**Status:** {status}\n"
        "**Surface:** `git rev-parse HEAD` = 0123456789abcdef0123456789abcdef01234567\n\n"
        "## Coverage Checklist\n\n"
        "```text\n"
        "# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)\n"
        "```\n\n"
        "| Class | Status |\n|---|---|\n"
        "| Hunt: `scripts/x.py` — every changed hunk, its enclosing function, its callers | "
        "CLEAN (`scripts/x.py` — the changed hunk, its enclosing function and both callers read "
        "whole; nothing in it reaches the surface this fixture is about) |\n\n"
        "## Pass Ledger\n\n| Pass | Finders | Counters | Method |\n|---|---|---|---|\n"
        f"{ledger}\n"
    )


_R = "| Pass {n} | native opus×1 | found: {f}, new: 0, confirmed: {c}, fixed: {x}, unexecuted: {u} | method: re-derivation |"


def _row(n: int, c: int, x: int = 0, u: int = 0, f: int = 9) -> str:
    return _R.format(n=n, f=f, c=c, x=x or c, u=u)


def test_the_phrase_alone_does_not_exempt_a_still_converging_loop():
    """THE COBRA PATH, graded: typing "scope-growth stop" into the Status line of an ordinary
    non-quiet review is the cheapest way to satisfy this without the outcome. The ledger must
    independently show the shape the stop keys on — two consecutive CONFIRMING rounds — and
    faking that costs two real rounds, which is the work itself."""
    crc = _crc()
    # one confirming round only: the loop was still converging normally
    text = _doc("CONVERGED on the D-252 scope-growth stop", [_row(1, 0, 0), _row(2, 4)])
    rows = crc._ledger_shapes(text)[2]
    assert not crc._scope_growth_exit(text, rows), (
        "the phrase exempted a loop whose ledger shows a single confirming round"
    )


def test_the_declared_stop_with_its_ledger_shape_is_a_legitimate_exit():
    crc = _crc()
    text = _doc("CONVERGED on the D-252 scope-growth stop", [_row(1, 14), _row(2, 4)])
    rows = crc._ledger_shapes(text)[2]
    assert crc._scope_growth_exit(text, rows)


def test_an_undeclared_stop_is_still_refused():
    """The ledger shape alone is NOT the exit — two confirming rounds is also what an ordinary
    unconverged review looks like. The author has to say which it is."""
    crc = _crc()
    text = _doc("CONVERGED", [_row(1, 14), _row(2, 4)])
    rows = crc._ledger_shapes(text)[2]
    assert not crc._scope_growth_exit(text, rows)


def test_the_declaration_is_header_zoned_like_in_progress():
    """An appendix sentence EXPLAINING the escape must not become the escape — the exact
    body-deep defeat `_in_progress` was hardened against in round 15."""
    crc = _crc()
    body_deep = (
        "# Review — fixture\n\n**Status:** CONVERGED\n\n"
        + "\n".join(f"filler line {i}" for i in range(20))
        + "\n\n**Status:** CONVERGED on the D-252 scope-growth stop\n\n"
        "## Pass Ledger\n\n| Pass | Finders | Counters | Method |\n|---|---|---|---|\n"
        + _row(1, 14)
        + "\n"
        + _row(2, 4)
        + "\n"
    )
    rows = crc._ledger_shapes(body_deep)[2]
    assert not crc._scope_growth_exit(body_deep, rows)


def test_an_unexecuted_candidate_closes_no_loop_under_any_exit():
    """`unexecuted:` counts CODE candidates nobody ran. The stop says the loop is reviewing its
    own fixes; it says nothing about work left unexamined, so this guard survives every exit."""
    crc = _crc()
    text = _doc("CONVERGED on the D-252 scope-growth stop", [_row(1, 14), _row(2, 4, u=3)])
    rows = crc._ledger_shapes(text)[2]
    assert not crc._scope_growth_exit(text, rows)


def test_check_file_accepts_the_stop_and_still_demands_a_fresh_seat(tmp_path):
    """The exemption is scoped to the QUIETNESS rule. V11 — the closing round carried a fresh
    non-authoring finder — is NOT exempt: a loop that stopped because it was reviewing its own
    fixes needs an outside reader more than a quiet one does, not less.

    Graded through `check_file`, the real entry point, on a file on disk — no `hasattr` hedge,
    which would make this pass vacuously the day the function is renamed."""
    crc = _crc()
    quiet_err = "the exit round must be quiet"
    rows = [_row(1, 14), _row(2, 4)]

    declared = tmp_path / "declared.md"
    declared.write_text(_doc("CONVERGED on the D-252 scope-growth stop", rows), encoding="utf-8")
    errs = crc.check_file(declared)
    assert not any(quiet_err in e for e in errs), errs

    # the SAME ledger without the declaration still reports the quietness failure — which is what
    # makes the assertion above a statement about the declaration rather than about the fixture
    plain = tmp_path / "plain.md"
    plain.write_text(_doc("CONVERGED", rows), encoding="utf-8")
    errs2 = crc.check_file(plain)
    assert any(quiet_err in e for e in errs2), errs2


def test_the_round_count_stays_in_lockstep_with_the_stop_that_defines_it():
    """Two hand-kept numbers are two things to drift, and the stale one is indistinguishable
    from the current one. Not imported (this file is fleet-synced and must grade a review in a
    repo whose `command_run.py` is a different vintage or absent), so this is the guard."""
    crc = _crc()
    src = (ROOT / "scripts" / "command_run.py").read_text(encoding="utf-8")
    for line in src.splitlines():
        if line.startswith("SCOPE_GROWTH_ROUNDS"):
            declared = int(line.split("=")[1].strip())
            break
    else:  # pragma: no cover - the constant is the subject of this test
        raise AssertionError("command_run.py no longer declares SCOPE_GROWTH_ROUNDS")
    assert declared == crc._OWN_FIX_ROUNDS_FOR_STOP, (
        f"check_review_coverage says {crc._OWN_FIX_ROUNDS_FOR_STOP}, "
        f"command_run.py says {declared} — the twin drifted"
    )
