"""Tests for scripts/enforcement/check_convergence.py — the convergence-evidence gate.

A markdown artifact that CLAIMS convergence must embed its proof, or the gate
fails. These tests drive the real script over a throwaway git repo (it discovers
artifacts via ``git status``), so they exercise the actual code path.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

CHECK = Path(__file__).resolve().parents[1] / "scripts" / "enforcement" / "check_convergence.py"

COMPLIANT_PLAN = """# Plan for X

**Status:** CONVERGED

## Evidence

## Phase 1 — wiring
Grounded in src/app/handler.py:42 (the request handler) and db/schema.sql:10.

```
$ python scripts/final_gate.py --lean
{"status": "success", "passed": 15, "failed": 0}
```

## Coverage Checklist

Classes derived from the rubric run, output pasted verbatim:

```
# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)
## FLOOR — always injected
```

plus the four standing recurrence classes.

| Class | Verdict | Evidence |
|---|---|---|
| fail-open vs fail-closed | CLEAN | src/app/handler.py:42 — guard denies on unset context |
| cost/quota accounting edges | CLEAN | no metered call on this path (src/app/handler.py:42) |
| boundary/sentinel | CLEAN | db/schema.sql:10 enum matches the handler's writes |
| behavior-without-a-test | FIXED | added tests/test_handler.py:11 |

## Pass Ledger

- Pass 1 (WIDE) — method: citation — found: 2, fixed: 2
- Pass 2 (CLOSING) — method: re-derivation — found: 0, fixed: 0

## Self-audit
Every claim above traces to a path:line citation and the gate output. No
runtime-only assumptions remain.
"""

PLAN_NO_CHECKLIST = COMPLIANT_PLAN[: COMPLIANT_PLAN.index("## Coverage Checklist")] + (
    "## Self-audit\nEvery claim traces to a citation and the gate output.\n"
)

PLAN_NO_EVIDENCE = """# Plan for X

**Status:** CONVERGED

## Phase 1
We will change the handler. It is converged, trust me.
"""

PLAN_NO_CLAIM = """# Plan for X

**Status:** DRAFT

## Phase 1
Exploratory notes; no convergence claimed yet. src/app/handler.py:42
"""

COMPLIANT_REVIEW = """# Review of plan X

## Phase 1 verdict
Mirrors the plan; no deviation.

reviewed — sign-off.

```
$ python scripts/final_gate.py --json
{"status": "success", "tier": 1, "passed": 15, "failed": 0}
```
"""

REVIEW_NO_GATE = """# Review of plan X

This was reviewed and looks converged to me.
No gate output, no phase verdicts.
"""

# --- EXECUTED-plan → whole-plan-review gate fixtures --------------------------

EXECUTED_PLAN_NO_REVIEW = """# Plan X

**Status:** EXECUTED 2026-08-03 (abc1234)

## Phase A
Shipped the handler. src/app/handler.py:42
"""

EXECUTED_PLAN_CITES_MISSING = """# Plan X

**Status:** EXECUTED 2026-08-03 (abc1234)
Whole-plan review: docs/development/reviews/2026-08-03-plan-x-review.md

## Phase A
Shipped. src/app/handler.py:42
"""

EXECUTED_PLAN_CITES = """# Plan X

**Status:** EXECUTED 2026-08-03 (abc1234)
Whole-plan review: docs/development/reviews/2026-08-03-plan-x-review.md

## Phase A
Shipped. src/app/handler.py:42
"""

# A real whole-plan review: passes _check_review (gate + phase + "reviewed") AND
# my adjudication signal (Coverage Checklist present, last `found:` is 0).
ADJUDICATED_REVIEW = """# Whole-plan review of Plan X

Surface: HEADabc + 0decafbad

## Coverage Checklist
| class | verdict |
|---|---|
| fail-open vs fail-closed | CLEAN |
| cost/quota edges | FIXED(1) |

## Phase A verdict
Mirrors the plan; one finding fixed.

reviewed — sign-off.

## Pass Ledger
Pass 1 — found: 2, fixed: 1
Pass 2 — found: 0, fixed: 0

```
$ python scripts/final_gate.py --json
{"status": "success", "tier": 2, "passed": 20, "failed": 0}
```
"""

# Passes _check_review (gate + phase + "reviewed") but is NOT coverage-adjudicated:
# no quiet `found: 0, fixed: 0` pass, so the loop never reached a clean exit.
STUB_REVIEW = """# Whole-plan review of Plan X

## Coverage Checklist
| class | verdict |
|---|---|
| fail-open vs fail-closed | UNCHECKED |

## Phase A verdict
pending.

reviewed.

## Pass Ledger
Pass 1 — found: 3, fixed: 1

```
{"status": "success", "passed": 1, "failed": 0}
```
"""

# A review that DOCUMENTS its own non-convergence: "found:0" appears only in prose,
# never as a quiet `found: 0, fixed: 0` pass. Must be REJECTED (the false-accept
# a whole-file last-`found:` heuristic let through).
PROSE_NONCONVERGENCE_REVIEW = """# Whole-plan review of Plan X

## Coverage Checklist
| class | verdict |
|---|---|
| cost/quota edges | FIXED(6) |

## Phase A verdict
One finding BLOCKED after 3 attempts.

## Pass Ledger
Pass 1 — found: 15, fixed: 9
Pass 2 — found: 6, fixed: 5

The loop did NOT reach a clean found:0 round — one finding is BLOCKED-escalated.

reviewed.

```
{"status": "success", "passed": 1, "failed": 0}
```
"""

# A genuine quiet pass, with a trailing `found: N` in later prose (declared
# residuals / net-new-coverage note). Must be ACCEPTED (the false-reject).
TRAILING_FOUND_REVIEW = """# Whole-plan review of Plan X

## Coverage Checklist
| class | verdict |
|---|---|
| fail-open vs fail-closed | CLEAN |

## Phase A verdict
Clean.

reviewed — sign-off.

## Pass Ledger
Pass 1 — found: 2, fixed: 2
Pass 2 — found: 0, fixed: 0

Declared residuals (advisory, out of scope): found: 2 follow-ups for a later plan.

```
{"status": "success", "passed": 20, "failed": 0}
```
"""

# Status is DRAFT/IN-PROGRESS with "executed" only in prose — NOT an EXECUTED claim.
PLAN_NOT_EXECUTED = """# Plan X

**Status:** DRAFT — to be executed after review; the migration was executed manually once.

## Phase A
Notes. src/app/handler.py:42
"""


# Status is CLOSED / Done, but the word "executed" appears in the status PROSE —
# must NOT be treated as an EXECUTED claim (real /opt/fabrik plans do this).
PLAN_EXECUTED_IN_PROSE_ONLY = """# Plan X

**Status:** ✅ **CLOSED 2026-06-02 — superseded** (a Draft that was never executed directly)

## Phase A
Notes. src/app/handler.py:42
"""

PLAN_DONE_WITH_EXECUTED_PROSE = """# Plan X

**Status:** Done, end-to-end verified. Initial install was executed unauthorized by an external AI.

## Phase A
Notes. src/app/handler.py:42
"""


def _run(repo: Path, relpath: str, content: str) -> int:
    return _run_files(repo, {relpath: content})


def _run_files(repo: Path, files: dict[str, str]) -> int:
    for relpath, content in files.items():
        (repo / relpath).parent.mkdir(parents=True, exist_ok=True)
        (repo / relpath).write_text(content)
    # The gate runs on STAGED content (it skips untracked '??' in-flight drafts —
    # "checked at staging"), so stage the fixtures to exercise the real path.
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True, timeout=15)
    proc = subprocess.run(
        [sys.executable, str(CHECK), "--project-root", str(repo)],
        capture_output=True,
        text=True,
        timeout=30,
    )
    return proc.returncode


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True, timeout=15)
    subprocess.run(["git", "config", "user.email", "t@t"], cwd=tmp_path, check=True, timeout=15)
    subprocess.run(["git", "config", "user.name", "t"], cwd=tmp_path, check=True, timeout=15)
    return tmp_path


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo, check=True, timeout=15, capture_output=True)


def _check(repo: Path) -> int:
    return subprocess.run(
        [sys.executable, str(CHECK), "--project-root", str(repo)],
        capture_output=True,
        text=True,
        timeout=30,
    ).returncode


def _check_out(repo: Path) -> tuple[int, str]:
    proc = subprocess.run(
        [sys.executable, str(CHECK), "--project-root", str(repo)],
        capture_output=True,
        text=True,
        timeout=30,
    )
    return proc.returncode, proc.stdout


def test_compliant_plan_passes(repo: Path) -> None:
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", COMPLIANT_PLAN) == 0


def test_converged_plan_without_evidence_fails(repo: Path) -> None:
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", PLAN_NO_EVIDENCE) == 1


def test_plan_not_claiming_convergence_is_ignored(repo: Path) -> None:
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", PLAN_NO_CLAIM) == 0


# --- Coverage Checklist on the CONVERGED flip -----------------------------------------
# /fabrik-plan-review was the ONLY review command with no rubric injection and no class
# ledger, so its convergence meant "nothing further occurred to the reviewer" rather than
# "every known failure class was swept". An out-of-band /fabrik-review on an ALREADY-
# CONVERGED 10-ticket plan found 5 more real defects that the rubric names explicitly —
# incl. a task_name the DB CHECK constraint refuses to store, and a per-tenant job created
# every 300s forever (transdoc, 2026-08-23). The plan is exactly where a 12-Factor
# violation gets WRITTEN, and the pipeline has no /fabrik-review step on the plan artifact.


def test_converged_plan_without_coverage_checklist_fails(repo: Path) -> None:
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", PLAN_NO_CHECKLIST) == 1


def test_converged_plan_with_unchecked_checklist_row_fails(repo: Path) -> None:
    doc = COMPLIANT_PLAN.replace("| boundary/sentinel | CLEAN", "| boundary/sentinel | UNCHECKED")
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", doc) == 1


def test_converged_plan_with_unverdicted_checklist_row_fails(repo: Path) -> None:
    doc = COMPLIANT_PLAN.replace("| boundary/sentinel | CLEAN", "| boundary/sentinel | looked at")
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", doc) == 1


def test_converged_plan_checklist_not_derived_from_rubric_fails(repo: Path) -> None:
    """Classes must come from review_rubric.py, not from memory — same floor /fabrik-review has."""
    doc = COMPLIANT_PLAN.replace(
        "# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)", ""
    )
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", doc) == 1


def test_converged_plan_checklist_heading_alone_is_not_enough(repo: Path) -> None:
    """An empty section satisfies a heading grep but adjudicates nothing."""
    doc = re.sub(r"\|[^\n]*\|\n", "", COMPLIANT_PLAN)
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", doc) == 1


def test_compliant_review_passes(repo: Path) -> None:
    assert _run(repo, "docs/development/reviews/2026-06-18-plan-x-review.md", COMPLIANT_REVIEW) == 0


def test_review_without_embedded_success_fails(repo: Path) -> None:
    assert _run(repo, "docs/development/reviews/2026-06-18-plan-x-review.md", REVIEW_NO_GATE) == 1


# --- review-branch escapes (parity with the plan branch; live: a de-claimed review
# doc honestly WITHHOLDING sign-off false-failed, and a literal success JSON in
# PROSE satisfied the evidence regex while the doc explained why faking it is wrong.


def test_a_converged_lane_may_embed_a_gate_a_sibling_lane_reds(repo: Path) -> None:
    """A SURFACE-scoped record was graded against a REPO-WIDE gate.

    With one lane per repo that is right; with concurrent lanes the record inherits every other
    lane's state. wef1 measured a converged 6-round loop (307 tests green, ruff clean) whose gate
    failed on ONE check with every finding inside a SIBLING's plan directory and 0 naming the
    reviewed surface — leaving three bad exits: embed a failing gate under a CONVERGED claim,
    stamp IN-PROGRESS (semantically false, and check_review_coverage then flags it as a loop that
    never closed), or skip the artifact /fabrik-review requires
    (01M1KVAZGNJAXXSB4XFMKPQG0Z).
    """
    honest = (
        "# Review of aspect 18\n\n## Phase 1 verdict\nConverged: 6 rounds, 19 classes, 0 new.\n\n"
        "reviewed — sign-off.\n\n"
        "GATE-SCOPE: out-of-surface — Plan-Set Contract (Spine+Tickets); findings naming this "
        "surface: 0 of 7; measured by: `check_plan_tickets --plan-dir <sibling set> | grep <my paths>`\n\n"
        "```\n$ python scripts/final_gate.py --json\n"
        '{"status": "failure", "tier": 2, "passed": 54, "failed": 1}\n```\n'
    )
    assert _run(repo, "docs/development/reviews/2026-09-03-aspect-18-review.md", honest) == 0

    # the declaration is not a magic word: it must carry its own denominator ...
    no_denominator = honest.replace("findings naming this surface: 0 of 7; ", "")
    assert (
        _run(repo, "docs/development/reviews/2026-09-03-aspect-18b-review.md", no_denominator) == 1
    )

    # ... it must name how it was measured ...
    unmeasured = honest.split("; measured by:")[0] + "\n\n" + honest.split("```", 1)[1]
    assert _run(repo, "docs/development/reviews/2026-09-03-aspect-18c-review.md", unmeasured) == 1

    # ... a NON-ZERO count naming this surface is the reviewer's own debt, not another lane's ...
    mine = honest.replace("0 of 7", "3 of 7")
    assert _run(repo, "docs/development/reviews/2026-09-03-aspect-18d-review.md", mine) == 1

    # ... and the failing gate must still be SHOWN, not merely asserted.
    no_embed = honest.split("```")[0]
    assert _run(repo, "docs/development/reviews/2026-09-03-aspect-18e-review.md", no_embed) == 1


def test_a_fenced_quote_of_the_gate_scope_grammar_is_documentation_not_a_declaration(
    repo: Path,
) -> None:
    """The first cut read the declaration on the RAW record, so a review documenting this very
    mechanism — one real sign-off claim, the grammar quoted inside a fence as an example, and an
    unrelated fenced `"status": "failure"` — passed with zero evidence. Found and reproduced by
    the fix's own review (pass 1, native finder), which also ran check_review_coverage on the
    same fixture: it did not catch it either. Same convention as `_claims_reviewed`: fenced text
    is a quotation.
    """
    quoted = (
        "# Review notes on the out-of-surface mechanism\n\n## Phase 1 verdict\nDocumenting the grammar.\n\n"
        "reviewed — sign-off.\n\n"
        "The declaration shape is:\n\n```\nGATE-SCOPE: out-of-surface — Plan-Set Contract; "
        "findings naming this surface: 0 of 7; measured by: `grep`\n```\n\n"
        'and an unrelated example of a failing run:\n\n```\n{"status": "failure", "failed": 1}\n```\n'
    )
    assert _run(repo, "docs/development/reviews/2026-09-05-quoted-grammar-review.md", quoted) == 1

    # a denominator of ZERO is a contradiction wearing the grammar — a failing gate has findings
    zero = (
        "# Review of aspect 19\n\n## Phase 1 verdict\nConverged.\n\nreviewed — sign-off.\n\n"
        "GATE-SCOPE: out-of-surface — Plan-Set Contract; findings naming this surface: 0 of 0; "
        'measured by: `grep`\n\n```\n{"status": "failure", "failed": 1}\n```\n'
    )
    assert _run(repo, "docs/development/reviews/2026-09-05-zero-denominator-review.md", zero) == 1

    # a DANGLING `measured by:` — the label with no value on its line — must fail: `\s*` crossed the
    # newline and any later non-space satisfied it (review pass 3, native finder, executed)
    dangling = (
        "# Review of aspect 20\n\n## Phase 1 verdict\nConverged.\n\nreviewed — sign-off.\n\n"
        "GATE-SCOPE: out-of-surface — Plan-Set Contract; findings naming this surface: 0 of 7; "
        "measured by:\n\n## Notes\n\nWe did not record the command.\n\n"
        '```\n{"status": "failure", "failed": 1}\n```\n'
    )
    assert (
        _run(repo, "docs/development/reviews/2026-09-05-dangling-measured-review.md", dangling) == 1
    )


def test_an_honest_declaration_with_a_fenced_value_passes(repo: Path) -> None:
    """Fences are replaced by a token for the declaration read, never deleted: deleting them made
    `measured by: ```cmd```` a fail-closed false failure while the fenced-grammar QUOTE still fails
    (review pass 4). Its own repo: the sibling test's failing fixtures stay staged in theirs, and a
    passing assertion graded beside them reads 1 for THEM — which is how this case first went red."""
    fenced_value = (
        "# Review of aspect 21\n\n## Phase 1 verdict\nConverged.\n\nreviewed — sign-off.\n\n"
        "GATE-SCOPE: out-of-surface — Plan-Set Contract; findings naming this surface: 0 of 7; "
        "measured by: ```check_plan_tickets --plan-dir x | grep mine```\n\n"
        '```\n{"status": "failure", "failed": 1}\n```\n'
    )
    assert (
        _run(repo, "docs/development/reviews/2026-09-05-fenced-value-review.md", fenced_value) == 0
    )


def test_review_withholding_claims_is_not_a_claim(repo: Path) -> None:
    # Directly-negated claim words are a DISCLOSURE, not a claim — no evidence owed.
    doc = (
        "# Session review notes\n\n"
        "Formal sign-off is withheld pending the seo closure.\n"
        "This surface is not yet reviewed to a no-op; not converged.\n"
    )
    assert _run(repo, "docs/development/reviews/2026-08-08-plan-y-review.md", doc) == 0


def test_fenced_claim_words_are_quotes_not_claims(repo: Path) -> None:
    # Claim words inside fences are quotations (template/example), not claims.
    doc = (
        "# Notes on the review grammar\n\n"
        "The closing line looks like:\n\n"
        "```\nreviewed — sign-off.\n```\n"
    )
    assert _run(repo, "docs/development/reviews/2026-08-08-plan-y-review.md", doc) == 0


def test_unnegated_claim_wins_over_nearby_negations(repo: Path) -> None:
    # Plan-branch precedence mirrored: ONE unnegated affirmative claims, even if
    # other sentences carry negated forms — and it still owes the evidence.
    doc = "# Review of plan Y\n\nOne residual is not converged (filed).\n\nreviewed — sign-off.\n"
    assert _run(repo, "docs/development/reviews/2026-08-08-plan-y-review.md", doc) == 1


def test_inline_fence_quote_does_not_break_embed_pairing(repo: Path) -> None:
    # An inline ```…``` quote (in-contract) before the real embed must not
    # shift block pairing so the genuine success JSON goes uncaptured.
    doc = (
        "# Review of plan Y\n\n"
        "## Phase A verdict\nMirrors the plan. Use ```json``` fences for embeds.\n\n"
        "reviewed — sign-off.\n\n"
        "```\n$ python scripts/final_gate.py --json\n"
        '{"status": "success", "tier": 2, "passed": 20, "failed": 0}\n```\n'
    )
    assert _run(repo, "docs/development/reviews/2026-08-09-plan-z-review.md", doc) == 0


def test_more_negated_claim_shapes_are_disclosures(repo: Path) -> None:
    doc = (
        "# Session notes\n\n"
        "Sign-off for this whole plan remains withheld pending operator closure.\n"
        "The branch cannot be merged until reviewed. Two docs stay un-reviewed.\n"
    )
    assert _run(repo, "docs/development/reviews/2026-08-09-plan-z-review.md", doc) == 0


def test_gate_json_in_prose_does_not_satisfy_evidence(repo: Path) -> None:
    # The embed must be a VERBATIM fenced block; the literal string in prose is
    # exactly how a fake (or an explanation of one) passes.
    doc = (
        "# Review of plan Y\n\n"
        "## Phase A verdict\nMirrors the plan.\n\n"
        "reviewed — sign-off.\n\n"
        'The gate would be satisfied by pasting "status": "success" in prose, '
        "which would be fake — noting the loophole here.\n"
    )
    assert _run(repo, "docs/development/reviews/2026-08-08-plan-y-review.md", doc) == 1


def test_no_artifacts_passes(repo: Path) -> None:
    proc = subprocess.run(
        [sys.executable, str(CHECK), "--project-root", str(repo)],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert proc.returncode == 0


# --- EXECUTED-plan → whole-plan-review gate -----------------------------------


def test_executed_plan_without_review_fails(repo: Path) -> None:
    # The SEO fingerprint: Status flipped EXECUTED with no persisted review.
    assert _run(repo, "docs/development/plans/2026-08-03-plan-x.md", EXECUTED_PLAN_NO_REVIEW) == 1


def test_executed_plan_citing_missing_review_fails(repo: Path) -> None:
    # Cites a review path that does not exist on disk.
    assert (
        _run(repo, "docs/development/plans/2026-08-03-plan-x.md", EXECUTED_PLAN_CITES_MISSING) == 1
    )


def test_executed_plan_citing_unadjudicated_review_fails(repo: Path) -> None:
    assert (
        _run_files(
            repo,
            {
                "docs/development/plans/2026-08-03-plan-x.md": EXECUTED_PLAN_CITES,
                "docs/development/reviews/2026-08-03-plan-x-review.md": STUB_REVIEW,
            },
        )
        == 1
    )


def test_executed_plan_with_adjudicated_review_passes(repo: Path) -> None:
    assert (
        _run_files(
            repo,
            {
                "docs/development/plans/2026-08-03-plan-x.md": EXECUTED_PLAN_CITES,
                "docs/development/reviews/2026-08-03-plan-x-review.md": ADJUDICATED_REVIEW,
            },
        )
        == 0
    )


def test_rename_into_archived_is_enforced(repo: Path) -> None:
    # The flip-EXECUTED-and-archive-in-one-commit move (a git rename into archived/)
    # must NOT be an escape hatch — it is still held to the review-citation rule.
    src = repo / "docs/development/plans/2026-08-03-plan-x.md"
    src.parent.mkdir(parents=True, exist_ok=True)
    # Seed identical to EXECUTED_PLAN_NO_REVIEW except the Status line, so the later
    # move is detected by git as a RENAME (high similarity), not delete+add.
    src.write_text(EXECUTED_PLAN_NO_REVIEW.replace("EXECUTED 2026-08-03 (abc1234)", "CONVERGED"))
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "seed plan")
    # Now flip EXECUTED (no citation) and move it into archived/ — as one staged change.
    dst = repo / "docs/development/plans/archived/2026-08-03-plan-x.md"
    dst.parent.mkdir(parents=True, exist_ok=True)
    _git(repo, "mv", str(src), str(dst))
    dst.write_text(EXECUTED_PLAN_NO_REVIEW)
    _git(repo, "add", "-A")
    assert _check(repo) == 1


def test_flip_and_archive_as_delete_add_is_enforced(repo: Path) -> None:
    # The move can be recorded as delete+add (big body rewrite) instead of a rename —
    # HEAD-comparison catches it anyway (archived path is new-with-EXECUTED at HEAD).
    src = repo / "docs/development/plans/2026-08-03-plan-x.md"
    src.parent.mkdir(parents=True, exist_ok=True)
    src.write_text("# Plan X\n\n**Status:** CONVERGED\n\n## Phase A\nshort seed body\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "seed")
    _git(repo, "config", "status.renames", "false")  # force delete+add representation
    src.unlink()
    dst = repo / "docs/development/plans/archived/2026-08-03-plan-x.md"
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(EXECUTED_PLAN_NO_REVIEW + "\n(completely rewritten summary body)\n")
    _git(repo, "add", "-A")
    assert _check(repo) == 1


def test_modified_already_archived_plan_is_skipped(repo: Path) -> None:
    # An already-settled archived plan that is merely re-touched (bulk reformat)
    # must NOT be re-failed for lacking the (new) citation — the 'cries wolf' guard.
    p = repo / "docs/development/plans/archived/2026-07-01-plan-old.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(EXECUTED_PLAN_NO_REVIEW)
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "seed archived plan")
    p.write_text(EXECUTED_PLAN_NO_REVIEW + "\n<!-- reformatted -->\n")  # incidental touch
    _git(repo, "add", "-A")
    assert _check(repo) == 0


def test_executed_word_in_status_prose_is_not_an_executed_claim(repo: Path) -> None:
    # CLOSED / Done / DRAFT status with "executed" in the prose must NOT trip the gate.
    assert (
        _run(repo, "docs/development/plans/2026-06-02-plan-x.md", PLAN_EXECUTED_IN_PROSE_ONLY) == 0
    )
    assert (
        _run(repo, "docs/development/plans/2026-06-01-plan-y.md", PLAN_DONE_WITH_EXECUTED_PROSE)
        == 0
    )
    assert _run(repo, "docs/development/plans/2026-06-03-plan-z.md", PLAN_NOT_EXECUTED) == 0


def test_review_documenting_nonconvergence_is_rejected(repo: Path) -> None:
    # "found:0" in prose (a BLOCKED-escalated, non-quiet exit) is NOT a clean exit.
    assert (
        _run_files(
            repo,
            {
                "docs/development/plans/2026-08-03-plan-x.md": EXECUTED_PLAN_CITES,
                "docs/development/reviews/2026-08-03-plan-x-review.md": PROSE_NONCONVERGENCE_REVIEW,
            },
        )
        == 1
    )


def test_quiet_pass_with_trailing_found_is_accepted(repo: Path) -> None:
    # A real `found: 0, fixed: 0` pass is adjudicated even if later prose adds a trailing `found: N`.
    assert (
        _run_files(
            repo,
            {
                "docs/development/plans/2026-08-03-plan-x.md": EXECUTED_PLAN_CITES,
                "docs/development/reviews/2026-08-03-plan-x-review.md": TRAILING_FOUND_REVIEW,
            },
        )
        == 0
    )


def test_review_with_a_trailing_summary_pair_is_still_accepted(repo: Path) -> None:
    # Candidate-2 guard (NO CRIES-WOLF): a genuinely-converged review whose ledger
    # reaches `found: 0, fixed: 0` but then ends with a per-phase summary line that
    # itself carries counts ("Phase A found: 3, fixed: 3") must STILL be accepted.
    # (A whole-tree "last found/fixed pair" heuristic wrongly rejected this common shape.)
    review = (
        "# Whole-plan review\n\n## Pass Ledger\nPass 1 — found: 2, fixed: 2\n"
        "Pass 2 — found: 0, fixed: 0\n\n## Per-phase summary\n"
        "Phase A found: 3, fixed: 3\nPhase B found: 1, fixed: 1\n\n"
        '## Phase A verdict\nclean.\n\nreviewed — sign-off.\n\n```\n{"status": "success", "passed": 9}\n```\n'
    )
    assert (
        _run_files(
            repo,
            {
                "docs/development/plans/2026-08-03-plan-x.md": EXECUTED_PLAN_CITES,
                "docs/development/reviews/2026-08-03-plan-x-review.md": review,
            },
        )
        == 0
    )


def test_reorg_move_of_settled_archived_plan_is_skipped(repo: Path) -> None:
    # Candidate-1 guard (NO CRIES-WOLF): a dir reorg that MOVES a settled, pre-citation
    # EXECUTED archived plan must not re-fail it — it was already EXECUTED at its source.
    old = repo / "docs/development/plans/archived/2026-07-01-plan-old.md"
    old.parent.mkdir(parents=True, exist_ok=True)
    old.write_text(EXECUTED_PLAN_NO_REVIEW)  # settled, no citation (grandfathered)
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "seed settled archived plan")
    new = repo / "docs/development/plans/archived/2026-07/plan-old.md"
    new.parent.mkdir(parents=True, exist_ok=True)
    _git(repo, "mv", str(old), str(new))  # relocate during a reorg
    _git(repo, "add", "-A")
    assert _check(repo) == 0


# --- Spine+ticket shape: tolerant CONVERGED + new-transition-only (BC 6) --------

SPINE_DIR = "docs/development/plans/2026-08-05-plan-1-widget"

CONVERGED_SPINE_ORPHAN_ROW = """# Plan: widget

Status: CONVERGED

## Ticket Board

| Ticket | Title | Depends | Parallel | State | Commit |
|---|---|---|---|---|---|
| T01 | schema | — | ⚡ | ⬜ | — |
| T02 | api | T01 | ⛓️ | ⬜ | — |

## Merge Order

1. T01
2. T02

## Evidence

Grounded in src/app/handler.py:42.

```
$ python scripts/final_gate.py --lean
{"status": "success", "passed": 15, "failed": 0}
```

## Self-audit
Traced.
"""

TICKET_T01 = """# T01 — schema

Depends: none
Parallel: ⚡
Complexity: simple
Docs: none
Gate: pytest -q

## Scope
Schema. DO-NOT touch api.

## Touches
- src/app/schema.py

## Behavior Contract
- **Given** x, **When** y, **Then** z (src/app/schema.py:1).

## Context Files
- .windsurf/rules/core/10-python.md
"""


def test_bc6_new_plain_converged_spine_with_orphan_row_fails(repo: Path) -> None:
    # T02 row has no ticket file on disk → orphan → fail (also proves the
    # tolerant CONVERGED regex: the Status line is PLAIN, not **Status:**).
    rc = _run_files(
        repo,
        {
            f"{SPINE_DIR}/2026-08-05-plan-1-widget.md": CONVERGED_SPINE_ORPHAN_ROW,
            f"{SPINE_DIR}/T01-schema.md": TICKET_T01,
        },
    )
    rc2, out = _check_out(repo)
    # Message-level: the ORPHAN-ROW mechanism specifically (the fixture also has
    # other contract gaps; rc alone would pass with the orphan loop deleted).
    assert rc == 1 and rc2 == 1
    assert "orphan row" in out


def test_flip_runs_full_ticket_contract_in_process(repo: Path) -> None:
    # BC 33's flip half: the in-process check_plan_dir(context="flip") call must
    # surface plan-set contract ERRORs (here: missing Complexity) at the
    # CONVERGED flip — if the import or the call regresses, the whole contract
    # would silently degrade to orphan-rows + the Status ban.
    complete = CONVERGED_SPINE_ORPHAN_ROW.replace("| T02 | api | T01 | ⛓️ | ⬜ | — |\n", "").replace(
        "2. T02\n", ""
    )
    no_cx = TICKET_T01.replace("Complexity: simple\n", "")
    rc = _run_files(
        repo,
        {
            f"{SPINE_DIR}/2026-08-05-plan-1-widget.md": complete,
            f"{SPINE_DIR}/T01-schema.md": no_cx,
        },
    )
    rc2, out = _check_out(repo)
    assert rc == 1 and rc2 == 1
    assert "plan-set contract" in out and "no parseable Complexity" in out


def test_spine_executed_per_ticket_review_never_proves_the_whole_plan(tmp_path: Path) -> None:
    # D7 discrimination (exec-D hardening): a spine flipping EXECUTED must cite
    # the WHOLE-PLAN validation review; an adjudicated D4 per-ticket review
    # (-T##-review.md) cannot satisfy the citation — else a set flips EXECUTED
    # without the D7 validation ever running.
    import scripts.enforcement.check_convergence as cc

    d = tmp_path / "docs" / "development" / "plans" / "2026-08-05-plan-1-widget"
    d.mkdir(parents=True)
    spine = d / "2026-08-05-plan-1-widget.md"
    rev_dir = tmp_path / "docs" / "development" / "reviews"
    rev_dir.mkdir(parents=True)
    (rev_dir / "2026-08-05-plan-1-widget-T01-review.md").write_text(
        ADJUDICATED_REVIEW, encoding="utf-8"
    )
    spine.write_text(
        "# Plan\n\nStatus: EXECUTED 2026-08-05\n\nWhole-plan review: "
        "docs/development/reviews/2026-08-05-plan-1-widget-T01-review.md\n",
        encoding="utf-8",
    )
    fails = cc._check_executed_plan(tmp_path, spine)
    assert any("per-ticket -T##-review.md files never satisfy it" in f for f in fails)

    # The SAME adjudicated content, cited as the whole-plan review, satisfies it.
    (rev_dir / "2026-08-05-plan-1-widget-review.md").write_text(
        ADJUDICATED_REVIEW, encoding="utf-8"
    )
    spine.write_text(
        spine.read_text(encoding="utf-8").replace("-T01-review.md", "-review.md"),
        encoding="utf-8",
    )
    fails2 = cc._check_executed_plan(tmp_path, spine)
    assert not any("cited whole-plan review" in f for f in fails2)


def test_bc6_ticket_with_status_line_fails_spine_convergence(repo: Path) -> None:
    complete = CONVERGED_SPINE_ORPHAN_ROW.replace("| T02 | api | T01 | ⛓️ | ⬜ | — |\n", "").replace(
        "2. T02\n", ""
    )
    rc = _run_files(
        repo,
        {
            f"{SPINE_DIR}/2026-08-05-plan-1-widget.md": complete,
            f"{SPINE_DIR}/T01-schema.md": TICKET_T01 + "\nStatus: DRAFT\n",
        },
    )
    rc2, out = _check_out(repo)
    assert rc == 1 and rc2 == 1
    assert "carries a Status: line" in out  # the BAN mechanism, not a side effect


def test_bc6_already_converged_at_head_is_settled(repo: Path) -> None:
    # A plain-CONVERGED monolith WITHOUT evidence, committed at HEAD, then
    # re-touched: the tolerant regex now matches it, but new-transition-only
    # enforcement must skip it (fleet backcompat — /opt/seo live instance).
    p = repo / "docs/development/plans/2026-08-02-plan-1-legacy.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("# Old plan\n\n**Status: CONVERGED** (4 passes)\n\nNo evidence sections at all.\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "seed settled converged plan")
    p.write_text(p.read_text() + "\nA later touch.\n")
    _git(repo, "add", "-A")
    assert _check(repo) == 0


def test_bc6_new_plain_converged_monolith_without_evidence_fails(repo: Path) -> None:
    # The tolerant regex must catch a NEW plain-Status monolith (was invisible
    # to the bold-only token regex).
    assert (
        _run(
            repo,
            "docs/development/plans/2026-08-05-plan-2-mono.md",
            "# Plan\n\nStatus: CONVERGED\n\n## Phase 1\nNo evidence.\n",
        )
        == 1
    )


def test_fenced_converged_quote_is_not_a_claim(repo: Path) -> None:
    # A DRAFT plan QUOTING the flip in an example block must not be enforced.
    body = (
        "# Plan\n\nStatus: DRAFT\n\nExample of the final flip:\n\n"
        "```markdown\nStatus: CONVERGED\n```\n\nNo evidence sections at all.\n"
    )
    assert _run(repo, "docs/development/plans/2026-08-06-plan-1-fq.md", body) == 0


def test_fenced_executed_at_head_does_not_settle_a_real_flip(repo: Path) -> None:
    # HEAD has a DRAFT plan quoting `Status: EXECUTED` in a fence; a later REAL
    # EXECUTED flip must still be enforced (the citation gate must fire).
    p = repo / "docs/development/plans/2026-08-06-plan-2-fx.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        "# Plan\n\nStatus: DRAFT\n\n```markdown\nStatus: EXECUTED\n```\n", encoding="utf-8"
    )
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "seed draft with fenced example")
    p.write_text("# Plan\n\nStatus: EXECUTED\n\nDone.\n", encoding="utf-8")
    _git(repo, "add", "-A")
    assert _check(repo) == 1  # claims EXECUTED, cites no review → enforced


def test_dual_claim_executed_at_head_plus_new_converged_still_enforced(repo: Path) -> None:
    # Round-9 #1: an already-EXECUTED-at-HEAD spine gaining a NEW CONVERGED claim
    # must still run the plan-set contract (the skip-if-EXECUTED dedupe opened
    # this hole; dedupe now happens on finding lines, not by skipping a path).
    d = repo / "docs/development/plans/2026-08-06-plan-3-dual"
    d.mkdir(parents=True)
    spine = d / "2026-08-06-plan-3-dual.md"
    spine.write_text(
        "# Plan\n\nStatus: EXECUTED\n\n## Ticket Board\n\n"
        "| Ticket | Title | Depends | Parallel | State | Commit |\n|---|---|---|---|---|---|\n"
        "| T99 | ghost | — | ⚡ | ⬜ | — |\n\nWhole-plan review: docs/development/reviews/x-review.md\n",
        encoding="utf-8",
    )
    (repo / "docs/development/reviews").mkdir(parents=True, exist_ok=True)
    (repo / "docs/development/reviews/x-review.md").write_text(
        '# R\n\nreviewed\n\n```\n"status": "success" and more content here\n```\n\n'
        "## Phase 1 verdict\nok\n\nfound: 0, fixed: 0\n",
        encoding="utf-8",
    )
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "seed executed spine (settled)")
    spine.write_text(
        spine.read_text(encoding="utf-8").replace(
            "Status: EXECUTED", "Status: EXECUTED — CLEAN-CONVERGED"
        ),
        encoding="utf-8",
    )
    _git(repo, "add", "-A")
    rc, out = _check_out(repo)
    assert rc == 1 and "orphan row" in out


def test_executed_citation_must_be_plan_relevant_not_any_quiet_review(tmp_path):
    """An EXECUTED plan citing an UNRELATED quiet review (name-drop) plus its own
    non-quiet validation review must FAIL — the quiet round must come from a review
    whose filename references this plan (the accidental-satisfaction loophole)."""
    import scripts.enforcement.check_convergence as cc

    root = tmp_path
    (root / "docs/development/plans").mkdir(parents=True)
    (root / "docs/development/reviews").mkdir(parents=True)
    plan = root / "docs/development/plans/2026-01-01-plan-9-widget.md"
    own = root / "docs/development/reviews/2026-01-01-plan-9-widget-review.md"
    other = root / "docs/development/reviews/2026-01-01-unrelated-review.md"
    own.write_text("# validation\nfound: 2, fixed: 2 — no quiet round recorded\n")
    other.write_text("# some other surface\nPass 3 | found: 0 | fixed: 0 | EXIT\n")
    plan.write_text(
        "# Plan: widget\n\nStatus: EXECUTED\n\n"
        "Whole-plan validation: `docs/development/reviews/2026-01-01-plan-9-widget-review.md`.\n"
        "Unrelated evidence: `docs/development/reviews/2026-01-01-unrelated-review.md`.\n"
    )
    fails = cc._check_executed_plan(root, plan)
    assert fails, "an unrelated quiet review must not satisfy the EXECUTED citation"

    # positive control: the plan-relevant review carrying the quiet round satisfies it
    own.write_text("# validation\n## Phase verdicts\nPass 4 | found: 0 | fixed: 0 | EXIT\n")
    assert cc._check_executed_plan(root, plan) == []


def test_executed_single_unrelated_citation_also_fails(tmp_path):
    """Round-2: even with exactly ONE citation, an unrelated quiet review must not
    satisfy the EXECUTED flip — the stem rule is unconditional (retro-safe: all
    archived EXECUTED plans stem-match their citations)."""
    import scripts.enforcement.check_convergence as cc

    root = tmp_path
    (root / "docs/development/plans").mkdir(parents=True)
    (root / "docs/development/reviews").mkdir(parents=True)
    plan = root / "docs/development/plans/2026-01-01-plan-9-widget.md"
    other = root / "docs/development/reviews/2026-01-01-unrelated-review.md"
    other.write_text("# other\nPass 3 | found: 0 | fixed: 0 | EXIT\n")
    plan.write_text(
        "# Plan: widget\n\nStatus: EXECUTED\n\n"
        "Whole-plan validation: `docs/development/reviews/2026-01-01-unrelated-review.md`.\n"
    )
    assert cc._check_executed_plan(root, plan), "single unrelated quiet citation must not satisfy"


# ── F4: a claim word QUOTED as data is not a claim about the document ────────────────────────────
# transdoc, 2026-08-27: their product ships a button whose label is the past tense of "to review".
# A certification report could not quote the control it drove — and neither could the note explaining
# the false positive — because REVIEWED matches anywhere in the doc. Hyphenating does not help: \b
# matches at a hyphen. The report was contorted into "mark-as-complete" wording purely to pass,
# which made the artifact LESS clear than the truth. A gate that forces a doc to misdescribe reality
# is worse than one that misses a case.
#
# Fenced blocks were already stripped; INLINE code was not. A backticked span is data by convention.


def _claims(text: str) -> bool:
    import importlib.util

    spec = importlib.util.spec_from_file_location("cc", CHECK)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod._claims_reviewed(text)


def test_a_backticked_ui_label_is_not_a_convergence_claim():
    assert not _claims("The dropzone exposes a `Reviewed` toggle; TC01 drove it.")
    assert not _claims("Asserted the `converged` badge renders for an approved doc.")


def test_prose_outside_the_backticks_still_claims():
    """The exemption must be surgical — quoting a label cannot launder a real claim beside it."""
    assert _claims("The plan is converged. The UI also has a `Reviewed` button.")
    assert _claims("This artifact was reviewed end to end.")


def test_an_unterminated_backtick_does_not_swallow_the_rest_of_the_document():
    """Fail-open on a malformed span: a stray backtick must not silently exempt every later claim."""
    assert _claims("A stray ` tick opens here. This document is converged.")


def test_negation_still_wins_inside_and_outside_code():
    assert not _claims("sign-off is withheld")
    assert not _claims("not yet reviewed")


# ── a probe whose command is ELIDED is not a probe ──────────────────────────────────────────────
# tryton-crm, 2026-08-28: three probe defects survived a plan that was Status: CONVERGED with
# check_plan_quality, check_plans, check_convergence AND final_gate all green. The sharpest was a
# fence reading `$ ... "account.payment fields_get"` — probe duty demands you re-run a `$ ` line
# and diff its output, and an elided command makes that impossible. The fence still satisfied the
# non-trivial-content rule, because the elided command sat above real pasted output.


def _cc():
    import importlib.util
    from pathlib import Path

    root = Path(__file__).resolve().parent.parent
    spec = importlib.util.spec_from_file_location(
        "cc_probe", root / "scripts" / "enforcement" / "check_convergence.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_an_elided_probe_command_is_counted():
    cc = _cc()
    text = '```\n$ ... "account.payment fields_get"\nname | string | char\n```\n'
    assert cc._elided_probes(text) == 1


def test_a_real_probe_command_is_not_counted():
    """The false-positive side, and the one that matters: 1,131 of 1,134 fleet plan/review docs
    carry real `$ ` probes, and flagging any of them would make the gate untrustworthy."""
    cc = _cc()
    text = '```\n$ python scripts/final_gate.py --json\n"status": "success"\n```\n'
    assert cc._elided_probes(text) == 0


def test_an_ellipsis_in_output_is_not_an_elided_command():
    """Truncated output legitimately contains `...`; only the COMMAND line is policed."""
    cc = _cc()
    text = "```\n$ grep -rn pattern .\nfile.py:1: match\n...\nfile.py:99: match\n```\n"
    assert cc._elided_probes(text) == 0


def test_an_ellipsis_inside_a_real_command_is_not_flagged():
    """`$ grep "..." file` is a real command with a literal ellipsis argument — the rule anchors on
    the command STARTING with `...`, so a mid-line ellipsis never fires."""
    cc = _cc()
    text = '```\n$ grep -n "..." notes.txt\nnotes.txt:3: ...\n```\n'
    assert cc._elided_probes(text) == 0


def test_elided_probes_outside_a_fence_are_ignored():
    """Prose may describe the shape `$ ...` while teaching the rule; only fenced blocks count."""
    cc = _cc()
    assert cc._elided_probes("A placeholder line like `$ ...` is not a probe.\n") == 0


def test_multiple_elided_probes_are_all_counted():
    cc = _cc()
    text = "```\n$ ... one\nout\n```\n\n```\n$ ... two\nout\n```\n"
    assert cc._elided_probes(text) == 2


def test_an_elided_probe_is_actually_reported_not_just_counted(tmp_path):
    """The wiring, not the helper. Neutering `_elided_probes`'s CALL SITE (`elided = 0`) left all
    50 tests green — the counter was covered and the reporting path was not, so the finding could
    have shipped unable to fire. This test is the one that goes red for that mutation."""
    import subprocess

    cc = _cc()
    root = tmp_path
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    d = root / "docs" / "development" / "plans"
    d.mkdir(parents=True)
    plan = d / "2026-08-28-plan-1-probe.md"
    plan.write_text(
        "# Plan\n\nStatus: CONVERGED\n\n## Phase A\n\n## Evidence\n\n"
        "src/app.py:42 — the call site\n\n"
        '```\n$ ... "account.payment fields_get"\nname | string | char | required\n```\n\n'
        "## Self-audit\n\nchecked.\n",
        encoding="utf-8",
    )
    fails = cc._check_plan(root, plan)
    assert any("ELIDED" in f for f in fails), fails


def test_a_plan_with_a_real_probe_is_not_flagged_for_elision(tmp_path):
    """Companion false-positive side, through the same reporting path."""
    import subprocess

    cc = _cc()
    root = tmp_path
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    d = root / "docs" / "development" / "plans"
    d.mkdir(parents=True)
    plan = d / "2026-08-28-plan-2-probe.md"
    plan.write_text(
        "# Plan\n\nStatus: CONVERGED\n\n## Phase A\n\n## Evidence\n\n"
        "src/app.py:42 — the call site\n\n"
        '```\n$ python scripts/final_gate.py --json\n"status": "success"\n```\n\n'
        "## Self-audit\n\nchecked.\n",
        encoding="utf-8",
    )
    assert not any("ELIDED" in f for f in cc._check_plan(root, plan)), cc._check_plan(root, plan)


# ── a TRIMMED fence must declare itself ─────────────────────────────────────────────────────────
# tryton-crm's defect 3, and their proposed convention. I declined to ship it for want of a
# decidable test and invited a proposal; theirs is decidable from the text alone: a fence body
# containing a bare `...` line has been trimmed, so its info string must be `excerpt`.


def test_a_trimmed_fence_without_the_marker_is_counted():
    cc = _cc()
    text = "```\n$ sed -n '784,815p' account.py\n    def get_amount(cls):\n    ...\n```\n"
    assert cc._unmarked_excerpts(text) == 1


def test_a_trimmed_fence_that_declares_itself_is_clean():
    cc = _cc()
    text = "```excerpt\n$ sed -n '784,815p' account.py\n    def get_amount(cls):\n    ...\n```\n"
    assert cc._unmarked_excerpts(text) == 0


def test_complete_output_is_never_flagged():
    """The false-positive side: it fires ONLY on a fence that already contains a bare `...`, so a
    complete output — however long — is untouched. That is what gives it zero migration pressure."""
    cc = _cc()
    text = '```\n$ python scripts/final_gate.py --json\n"status": "success"\n"blocking": 41\n```\n'
    assert cc._unmarked_excerpts(text) == 0


def test_an_ellipsis_inside_a_line_is_not_a_trim_marker():
    """Only a line that is EXACTLY `...` counts. `foo ... bar` is prose or a real argument."""
    cc = _cc()
    assert cc._unmarked_excerpts("```\n$ grep x f\nresult ... continues\n```\n") == 0


def test_an_indented_bare_ellipsis_still_counts():
    """Trimmed code output is usually indented; anchoring on column 0 would miss the common case."""
    cc = _cc()
    assert cc._unmarked_excerpts("```\n$ cat f.py\n    def a():\n        ...\n```\n") == 1


def test_a_trimmed_fence_is_actually_reported_through_check_plan(tmp_path):
    """The wiring, not the helper — the mutation that slipped past the elided-probe tests."""
    import subprocess

    cc = _cc()
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    d = tmp_path / "docs" / "development" / "plans"
    d.mkdir(parents=True)
    plan = d / "2026-08-28-plan-3-excerpt.md"
    plan.write_text(
        "# Plan\n\nStatus: CONVERGED\n\n## Phase A\n\n## Evidence\n\nsrc/app.py:42 — the site\n\n"
        "```\n$ sed -n '1,40p' src/app.py\ndef handler():\n...\n```\n\n## Self-audit\n\nok.\n",
        encoding="utf-8",
    )
    assert any("TRIMMED" in f for f in cc._check_plan(tmp_path, plan)), cc._check_plan(
        tmp_path, plan
    )


def test_the_marker_is_a_token_so_a_language_tag_survives():
    """The hub's own first violation was a ```python fence. Requiring the info string to BE
    "excerpt" would trade syntax highlighting for the marker; requiring it to CONTAIN the token
    keeps both. Found by fixing our own corpus before shipping the rule to 46 repos."""
    cc = _cc()
    assert cc._unmarked_excerpts("```python excerpt\ndef a():\n    ...\n```\n") == 0
    assert cc._unmarked_excerpts("```python\ndef a():\n    ...\n```\n") == 1


def test_a_lookalike_word_does_not_satisfy_the_marker():
    """Token match, not substring: `excerpted`/`no-excerpt` must not clear it."""
    cc = _cc()
    assert cc._unmarked_excerpts("```excerpted\nx\n...\n```\n") == 1


# ── an archived plan whose Status still says work continues ──────────────────────────────────────
# tryton-crm (2026-08-28): `git mv` moves INDEXED content, so their `Status: EXECUTED` flip stayed
# unstaged and the plan archived as IN-PROGRESS. No gate could see it — `_check_plan` early-returns
# unless the text claims CONVERGED, and the EXECUTED contract only binds plans that CLAIM EXECUTED,
# so a plan stranded mid-flight is out of scope for both while the archive claims nothing is left.


def _archived_repo(tmp_path, name: str, status: str | None):
    import subprocess

    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    d = tmp_path / "docs" / "development" / "plans" / "archived"
    d.mkdir(parents=True)
    body = f"# Plan\n\n{'Status: ' + status if status else '(no status line)'}\n\nwork\n"
    (d / name).write_text(body, encoding="utf-8")
    for args in (
        ["add", "-A"],
        ["-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "a"],
    ):
        subprocess.run(["git", "-C", str(tmp_path), *args], check=True)
    # re-touch so it appears in git status (the check only reads CHANGED files)
    (d / name).write_text(body + "\ntouched\n", encoding="utf-8")
    return tmp_path


def test_an_archived_plan_still_in_progress_is_flagged(tmp_path):
    cc = _cc()
    root = _archived_repo(tmp_path, "2026-08-11-plan-1-quotation.md", "IN-PROGRESS")
    fails = cc._archived_midflight(root)
    assert fails and "archived while its own Status" in fails[0], fails


def test_an_archived_executed_plan_is_clean(tmp_path):
    cc = _cc()
    root = _archived_repo(tmp_path, "2026-08-11-plan-1-done.md", "EXECUTED 2026-08-12")
    assert cc._archived_midflight(root) == []


def test_a_status_less_legacy_archived_plan_is_not_flagged(tmp_path):
    """The narrowing that made this shippable. The filed proposal — 'flag any archived plan not
    EXECUTED' — measured 348 of 553 archived docs fleet-wide, nearly all legacy shapes with no
    Status line at all. A gate that cries wolf on landing gets noqa'd."""
    cc = _cc()
    root = _archived_repo(tmp_path, "2026-05-27-plan-legacy.md", None)
    assert cc._archived_midflight(root) == []


def test_a_ticket_file_in_an_archived_plan_set_is_not_flagged(tmp_path):
    """T## tickets legitimately carry no plan Status; only the dated PLAN file is policed."""
    cc = _cc()
    root = _archived_repo(tmp_path, "T01-some-ticket.md", "IN-PROGRESS")
    assert cc._archived_midflight(root) == []


def test_a_broken_git_never_wedges_the_archived_check(tmp_path):
    """No git repo at all — must return [], never raise, or a blocking gate dies on a bad cwd."""
    cc = _cc()
    assert cc._archived_midflight(tmp_path / "nowhere") == []


def test_the_archived_check_is_wired_into_main_not_just_defined(tmp_path, capsys, monkeypatch):
    """THE WIRING. Deleting `fails.extend(_archived_midflight(root))` from main() left all 65 tests
    green — the helper was covered and its call site was not, so the check could ship unable to
    fire. Third time this exact gap appeared today; asserting through main() is what closes it."""
    cc = _cc()
    root = _archived_repo(tmp_path, "2026-08-11-plan-1-wired.md", "IN-PROGRESS")
    monkeypatch.setattr("sys.argv", ["check_convergence.py", "--project-root", str(root)])
    rc = cc.main()
    out = capsys.readouterr().out + capsys.readouterr().err
    assert rc != 0 or "archived while its own Status" in out, (rc, out)


def test_a_rubric_invocation_inside_a_fence_satisfies_the_checklist_rule():
    """job-agent, 2026-08-28: the checker demanded evidence that `review_rubric.py` had been RUN
    while searching the FENCE-STRIPPED text — structurally blind to the one place a command and its
    output naturally go. Putting the invocation where it belongs made it invisible, a genuinely
    circular state that cost 4 round-trips. Fence-stripping is right for a heading's PRESENCE and
    wrong for a command INVOCATION."""
    cc = _cc()
    text = (
        "## Coverage Checklist\n\n| # | Class | Verdict |\n|---|---|---|\n| 1 | x | CLEAN |\n\n"
        "```\n# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)\nFLOOR …\n```\n"
    )
    fails = cc._checklist_fails(text, cc.FENCE_STRIP.sub("", text))
    assert not any("review_rubric" in f for f in fails), fails


def test_a_checklist_with_no_rubric_invocation_anywhere_still_fails():
    """The rule must keep its teeth — this is what stops classes being invented from memory."""
    cc = _cc()
    text = "## Coverage Checklist\n\n| # | Class | Verdict |\n|---|---|---|\n| 1 | x | CLEAN |\n"
    fails = cc._checklist_fails(text, cc.FENCE_STRIP.sub("", text))
    assert any("review_rubric" in f for f in fails), fails


# --- the re-derivation ledger row (tryton-crm 01M17KHT, 2026-08-29) -----------------------
# /fabrik-plan-review stamped CONVERGED after ELEVEN rounds with the factual-pass sentence IN
# the command and applied in ZERO of them — six defects survived, three execution-stalling.
# Their root cause: the ledger had no METHOD column, so eleven citation rounds were
# indistinguishable from a loop that re-derived. The flip now REFUSES without >=1
# re-derivation row. Form is machine-checked; the honesty boundary (writing the token without
# running the pass) is the same adjudicated limit as BLOCKED evidence — declarative, backstopped
# by the operator reading the escalation.


def _min_converged_plan(ledger_line: str) -> str:
    return (
        "**Status:** CONVERGED\n\n## Evidence\n\nsee `a.py:1`\n\n"
        "```\n$ echo proof\nproof\n```\n\n## Self-audit\n\nok\n\n"
        "## Pass Ledger\n\n" + ledger_line + "\n"
    )


def test_a_new_converged_plan_without_a_rederivation_row_is_refused(tmp_path):
    cc = _cc()
    p = tmp_path / "2026-08-29-plan-1-x.md"
    p.write_text(_min_converged_plan("- Pass 1 (WIDE) — method: citation — found: 2, fixed: 2"))
    fails = cc._check_plan(tmp_path, p)
    assert any("re-deriv" in f for f in fails), fails


def test_a_rederivation_row_satisfies_the_flip(tmp_path):
    cc = _cc()
    p = tmp_path / "2026-08-29-plan-2-x.md"
    p.write_text(
        _min_converged_plan(
            "- Pass 1 (WIDE) — method: citation — found: 2, fixed: 2\n"
            "- Pass 2 (CLOSING) — method: re-derivation — found: 0, fixed: 0"
        )
    )
    fails = cc._check_plan(tmp_path, p)
    assert not any("re-deriv" in f for f in fails), fails


def test_a_fence_quoted_rederivation_row_does_not_satisfy(tmp_path):
    """A DRAFT template quoting the example table must not pre-satisfy the rule."""
    cc = _cc()
    p = tmp_path / "2026-08-29-plan-3-x.md"
    p.write_text(
        _min_converged_plan("- Pass 1 — method: citation — found: 0, fixed: 0")
        + "\n```\n| 2 | all | re-derivation | 0 | 0 |\n```\n"
    )
    fails = cc._check_plan(tmp_path, p)
    assert any("re-deriv" in f for f in fails), fails


def test_an_in_progress_review_skeleton_is_not_a_convergence_claim(tmp_path):
    """fabrik-lib 01M180SP: the termination contract MANDATES creating the review file
    before pass 1, and _check_review immediately redded it for lacking an embedded green
    gate it cannot yet have — a chicken-and-egg hit twice in one session. Header-zone
    Status: IN-PROGRESS is the sanctioned mid-loop state (the coverage grader already
    honors it); the flip back to CONVERGED re-arms this check."""
    cc = _cc()
    d = tmp_path / "docs" / "development" / "reviews"
    d.mkdir(parents=True)
    f = d / "2026-08-30-x-review.md"
    f.write_text(
        "# Review — x\n**Status:** IN-PROGRESS\n**Surface:** abc\n\n"
        "This review is mid-loop; classes reviewed so far: none.\n",
        encoding="utf-8",
    )
    assert cc._check_review(tmp_path, f) == []
    flipped = f.read_text().replace("IN-PROGRESS", "CONVERGED")
    f.write_text(flipped, encoding="utf-8")
    assert cc._check_review(tmp_path, f), "the flip must re-arm the evidence demand"


# ── V13: QUIET_PASS follows the D-206 grammar ────────────────────────────────────────────────────
# D-203 re-cut the review loop and D-206 (supersedes D-048) made `confirmed:` the exit counter: a
# round is quiet when its CONFIRMED count is zero and nothing stands unexecuted — `found:` is prose.
# These rows are the shared V13 ↔ V1 fixtures (the same rows grade at check_review_coverage.py's
# exit rule); the whole-document quiet fixtures above (ADJUDICATED_REVIEW, TRAILING_FOUND_REVIEW)
# are the OLD-grammar shape this pair must keep matching.

# D9's round 18 of the D-191 receipt — three defects confirmed by execution, so not quiet.
D9_ROUND_18_ROW = (
    "| Pass 18 | opus×1 | found: 11, new: 9, confirmed: 3, fixed: 3, unexecuted: 0 | m |"
)
# V1's round 19 — the delta round that closes it: a non-zero `found:` with `confirmed: 0`.
V1_ROUND_19_ROW = "| Pass 19 | opus×1 | found: 5, new: 0, confirmed: 0, fixed: 0 | delta |"
# `unexecuted:` above zero: old-grammar quiet on its face, two code candidates still standing.
UNEXECUTED_ROW = "| u | x | found: 0 | fixed: 0 | unexecuted: 2 |"
# Zero-padded — must read the same at both gates.
CONFIRMED_00_ROW = "| 19 | found: 0 | confirmed: 00 | fixed: 0 |"
# A numeric `confirmed:` above zero beside `found: 0`: quiet under the old pair, never under D-206.
CONFIRMED_3_ROW = "| 18 | found: 0, confirmed: 3, fixed: 0 |"


def test_quiet_pass_grades_the_five_v13_rows():
    """The D-206 grammar, row by row (the design spec's V13)."""
    q = _cc().QUIET_PASS
    assert not q.search(D9_ROUND_18_ROW), "three confirmed defects is not a quiet round"
    assert q.search(V1_ROUND_19_ROW), "confirmed: 0 + fixed: 0 is quiet however large `found:` is"
    assert not q.search(UNEXECUTED_ROW), "unexecuted: 2 stands — the old pair must not read quiet"
    assert q.search(CONFIRMED_00_ROW), "a zero-padded confirmed: 00 is confirmed: 0"
    assert not q.search(CONFIRMED_3_ROW), "a numeric confirmed: 3 kills the old found:/fixed: pair"


def test_a_prose_confirmed_label_keeps_an_old_grammar_rows_quiet_match():
    """The lookaheads are anchored to a DIGIT: this gate runs re.I and is deliberately
    zero-false-positive (check_convergence.py:186-199), so a prose `CONFIRMED: see residual`
    label on an honest old-grammar row must not fail a genuinely converged receipt."""
    q = _cc().QUIET_PASS
    assert q.search("| 19 | found: 0 | fixed: 0 | delta — CONFIRMED: see residual |")


# The receipt corpus PINNED at the plan's base commit. The working tree's corpus grows — the next
# converged receipt a sibling commits would red an exact count here for a reason that has nothing
# to do with the regex — so the denominator is read out of a fixed tree object, never `ls-files`
# and never the working tree. 275 receipts / 166 quiet / 166 quiet / 0 flips is stable forever.
_CORPUS_SHA = "8092e8a8"


def test_quiet_pass_is_set_identical_to_the_retired_regex_over_the_committed_receipts():
    """Backward compatibility is a CONTRACT (DD4): re-cutting the grammar must not flip a single
    committed receipt. The retired value is carried here as a LITERAL — it no longer exists in the
    module — and both are run whole-text, exactly as _check_executed_plan does
    (check_convergence.py:768-772)."""
    old = re.compile(r"found:\s*0\b[^\n]*?fixed:\s*0\b", re.I)
    new = _cc().QUIET_PASS
    root = Path(__file__).resolve().parent.parent
    ls_tree = ["git", "-C", str(root), "ls-tree", "-r", "--name-only", _CORPUS_SHA]
    listing = subprocess.run(
        [*ls_tree, "--", "docs/development/reviews/"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    files = [f for f in listing if f.endswith(".md")]
    assert len(files) == 275, (
        f"the pinned corpus at {_CORPUS_SHA} is 275 receipts, got {len(files)}"
    )
    old_quiet: set[str] = set()
    new_quiet: set[str] = set()
    for rel in files:
        text = subprocess.run(
            ["git", "-C", str(root), "show", f"{_CORPUS_SHA}:{rel}"],
            capture_output=True,
            text=True,
            check=True,
            errors="replace",
        ).stdout
        if old.search(text):
            old_quiet.add(rel)
        if new.search(text):
            new_quiet.add(rel)
    old_only = sorted(old_quiet - new_quiet)
    new_only = sorted(new_quiet - old_quiet)
    # Counts first, then a BOUNDED sample of each flip direction — the full lists live in the
    # assertion message below, and printing 166 paths here makes a real failure unreadable.
    print(
        f"pinned corpus {_CORPUS_SHA}: {len(files)} receipts, "
        f"old quiet {len(old_quiet)}, new quiet {len(new_quiet)}, "
        f"flips {len(old_only)} old-only + {len(new_only)} new-only "
        f"(first 3 each: {old_only[:3]} / {new_only[:3]})"
    )
    assert old_quiet == new_quiet, {"old-only": old_only, "new-only": new_only}
    assert len(new_quiet) == 166, f"{len(new_quiet)} quiet of {len(files)} pinned receipts"


# ------------------------------- the closing-row `confirmed: 0` rule (review-family adoption, Phase C)

_LEDGER_SPINE_HEAD = '# Plan: ledger fixture\n\nStatus: CONVERGED\n\n## Goal\n\nx.\n\n## Ticket Board\n\n| Ticket | Title | Depends | Parallel | State | Commit |\n|---|---|---|---|---|---|\n| T01 | fixture | — | ⚡ | ⬜ | — |\n\n## Merge Order\n\n1. T01\n\n## Behavior Contract\n\n- **Given** x, **When** y, **Then** z (src/app/handler.py:1).\n\n## Coverage Checklist\n\n```\n$ python scripts/review_rubric.py --changed src/app/handler.py\n# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)\nFLOOR …\n```\n\n| Class | Status |\n|---|---|\n| fail-open | CLEAN |\n\n## Evidence\n\nGrounded in src/app/handler.py:42.\n\n```\n$ python scripts/final_gate.py --lean\n{"status": "success", "passed": 15, "failed": 0}\n```\n\n## Self-audit\nTraced.\n\n## Pass Ledger\n\n'

_LEDGER_TICKET = "# T01 — fixture\n\nDepends: none\nParallel: ⚡\nComplexity: native\nIntegration: true\nDocs: none\nGate: pytest -q\n\n## Scope\nFixture. DO-NOT touch api.\n\n## Touches\n- src/app/handler.py\n\n## Behavior Contract\n- **Given** x, **When** y, **Then** z (src/app/handler.py:1).\n\n## Context Files\n- .windsurf/rules/core/10-python.md\n"


def _ledger_spine(tmp_path: Path, archived: bool = False) -> Path:
    base = tmp_path / "docs" / "development" / "plans"
    d = (base / "archived" if archived else base) / "2026-09-10-plan-1-ledger"
    d.mkdir(parents=True, exist_ok=True)
    (d / "T01-fixture.md").write_text(_LEDGER_TICKET)
    return d / "2026-09-10-plan-1-ledger.md"


def _run_ledger(tmp_path: Path, ledger: str, archived: bool = False) -> tuple[int, str]:
    spine = _ledger_spine(tmp_path, archived)
    spine.write_text(_LEDGER_SPINE_HEAD + ledger)
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True, timeout=15)
    proc = subprocess.run(
        [sys.executable, str(CHECK), "--project-root", str(tmp_path)],
        capture_output=True,
        text=True,
        timeout=60,
    )
    return proc.returncode, proc.stdout


REFUSAL = "the last Pass row does not read confirmed: 0"


def test_a_converged_spine_whose_last_pass_row_confirms_more_than_zero_is_refused(repo):
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — full | found: 3 | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation — delta | found: 2 | confirmed: 2 |\n",
    )
    assert rc == 1 and REFUSAL in out, out


def test_a_converged_spine_whose_last_pass_row_confirms_zero_passes(repo):
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — full | found: 3 | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation — delta | found: 0 | confirmed: 0 |\n",
    )
    assert rc == 0, out


def test_a_counter_inside_a_code_span_and_a_colonless_counter_are_not_counter_rows(repo):
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — quoted a fifth `confirmed: 3` row | edits: 2 |\n| Pass 2 | seat | method: re-derivation — delta; confirmed 0 | edits: 0 |\n",
    )
    assert rc == 0, out


def test_an_edits_only_ledger_without_a_counter_keeps_todays_checks(repo):
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | all | method: citation | edits: 7 |\n| Pass 2 | all | method: re-derivation | edits: 0 |\n",
    )
    assert rc == 0, out


def test_an_indented_closing_row_under_a_list_item_is_still_a_counter_row(repo):
    rc, out = _run_ledger(
        repo,
        "- the ledger:\n  | Pass 1 | seats | method: citation — full | confirmed: 3 |\n  | Pass 2 | seat | method: re-derivation — delta | confirmed: 2 |\n",
    )
    assert rc == 1 and REFUSAL in out, out


def test_the_last_confirmed_token_on_the_closing_row_is_the_one_that_counts(repo):
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — full | confirmed: 4 |\n| Pass 2 | seat | method: re-derivation — delta; notes: confirmed: 4 earlier, now confirmed: 0 |\n",
    )
    assert rc == 0, out


def test_an_archived_spine_is_never_graded_by_the_closing_row_rule(repo):
    """28 of the 47 fleet spines are archived; `_executed_targets` does not skip `archived/`, so the
    `return []` at the top of `_check_spine_set` is the only thing keeping settled history out."""
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — full | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation — delta | confirmed: 4 |\n",
        archived=True,
    )
    assert rc == 0 and REFUSAL not in out, out


@pytest.mark.parametrize("label", ["**Pass 2**", "pass 2", "Round 2"])
def test_a_bold_lowercase_or_round_headed_closing_row_is_still_a_counter_row(repo, label):
    """`_REDERIVATION_ROW` accepts `pass|round`; the closing-row rule must not disagree about what a
    ledger row is, and the corpus writes bold labels for emphasis."""
    rc, out = _run_ledger(
        repo,
        f"| Pass 1 | seats | method: citation — full | confirmed: 0 |\n| {label} | seat | method: re-derivation — delta | confirmed: 4 |\n",
    )
    assert rc == 1 and "confirmed: 4" in out, out  # only a matched row can carry the 4


def test_a_two_digit_counter_is_read_whole(repo):
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — full | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation — delta | confirmed: 12 |\n",
    )
    assert rc == 1 and "confirmed: 12" in out, out


def test_unconfirmed_is_not_a_confirmed_counter(repo):
    """`QUIET_PASS` carries `(?<![\\w-])` in front of its token for exactly this reason."""
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — full | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation — delta | confirmed: 0, unconfirmed: 2 |\n",
    )
    assert rc == 0, out


def test_a_ledger_parked_in_an_html_comment_is_not_graded(repo):
    """Commenting out a superseded ledger is the standard markdown park; the receipt-side
    `_blank_quoted` blanks comments and fences alike (it also runs an unclosed comment to the end
    of the file; this rule needs the closer — fail-closed, by design)."""
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — full | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation — delta | confirmed: 0 |\n\n<!-- the old ledger, parked:\n| Pass 3 | seats | method: citation | confirmed: 9 |\n-->\n",
    )
    assert rc == 0, out


def _spine_set_fails(tmp_path: Path, ledger: str, archived: bool = False) -> list[str]:
    """`_check_spine_set` in-process — the function the closing-row rule lives in — so the archived
    carve-out and the message are graded on the path the rule takes (the CONVERGED target list
    already skips `archived/`; the EXECUTED one does not)."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    spine = _ledger_spine(tmp_path, archived)
    spine.write_text(_LEDGER_SPINE_HEAD + ledger)
    return cc._check_spine_set(tmp_path, spine, spine.read_text())


def test_the_archived_carve_out_keeps_settled_history_out_of_the_closing_row_rule(tmp_path):
    ledger = "| Pass 1 | seats | method: citation — full | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation — delta | confirmed: 4 |\n"
    assert _spine_set_fails(tmp_path, ledger, archived=True) == []
    live = _spine_set_fails(tmp_path, ledger, archived=False)
    assert any("last Pass row does not read confirmed: 0" in f for f in live), live


def test_the_refusal_is_a_sentence_that_quotes_the_row_as_written(tmp_path):
    """Both flip paths print this line; it must read as a sentence and quote the counter verbatim
    (`confirmed: 03` is `03`, not `3`)."""
    ledger = "| Pass 1 | seats | method: citation — full | confirmed: 0 |\n| Pass 2 | seat | method: re-derivation — delta | confirmed: 03 |\n"
    fails = _spine_set_fails(tmp_path, ledger)
    assert (
        len(fails) == 1
        and "the flip is refused: the last Pass row does not read confirmed: 0" in fails[0]
    ), fails
    assert "reads confirmed: 03" in fails[0], fails


def test_the_rule_strips_fences_itself_for_the_census_path():
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    # the quoted row comes LAST, so only a real strip keeps it out of the verdict
    raw = "| Pass 1 | seats | method: re-derivation | confirmed: 0 |\n\n```\n| Pass 2 | quoted | confirmed: 4 |\n```\n"
    assert cc._closing_row_fail(raw) is None


def test_an_html_comment_marker_inside_a_code_span_does_not_swallow_the_ledger():
    """`` `<!--` `` in prose is a code span, not a comment opener — masking runs before blanking."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    raw = "Park a superseded ledger in `<!--` at the top.\n\n| Pass 1 | seats | method: citation | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation | confirmed: 4 |\n\nClose it with `-->` at the end.\n"
    assert cc._closing_row_fail(raw) is not None


def test_a_zero_padded_closing_counter_reads_as_zero_at_both_gates(repo):
    """`QUIET_PASS` writes `0+` so `confirmed: 00` reads the same at both gates — this rule too."""
    rc, out = _run_ledger(
        repo,
        "| Pass 1 | seats | method: citation — full | confirmed: 3 |\n| Pass 2 | seat | method: re-derivation — delta | confirmed: 00 |\n",
    )
    assert rc == 0, out


def test_two_parked_comments_do_not_swallow_the_live_rows_between_them():
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    raw = "<!-- parked one -->\n| Pass 9 | seat | method: re-derivation | confirmed: 7 |\n<!-- parked two -->\n"
    assert cc._closing_row_fail(raw) is not None


def test_an_inline_fence_marker_in_prose_does_not_swallow_the_live_rows_after_it():
    """The documented parsing contract: balanced line-anchored fences, never a naive ```.*?```."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    raw = "see the ``` marker in prose\n| Pass 9 | seat | method: re-derivation | confirmed: 7 |\n```\nquoted\n```\n"
    assert cc._closing_row_fail(raw) is not None


def test_a_plan_whose_slug_contains_archived_is_still_graded(tmp_path):
    """The carve-out is the `archived/` DIRECTORY part, never a name fragment."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    d = tmp_path / "docs" / "development" / "plans" / "2026-09-10-plan-1-archived-ledger-cleanup"
    d.mkdir(parents=True)
    (d / "T01-fixture.md").write_text(_LEDGER_TICKET)
    spine = d / "2026-09-10-plan-1-archived-ledger-cleanup.md"
    spine.write_text(
        _LEDGER_SPINE_HEAD
        + "| Pass 1 | seats | method: citation | confirmed: 0 |\n| Pass 2 | seat | method: re-derivation | confirmed: 7 |\n"
    )
    fails = cc._check_spine_set(tmp_path, spine, spine.read_text())
    assert any("last Pass row does not read confirmed: 0" in f for f in fails), fails


def test_a_double_backtick_span_is_masked_like_a_single_one():
    """CommonMark code spans are run-length delimited — `` ``<!--`` `` is a span, not an empty span
    plus a bare opener; and the rule's own remedy ("cite an earlier count in a code span") must hold
    for the double-backtick spelling too."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    opener = "A parked ledger opens at ``<!--`` here.\n| Pass 1 | seat | method: re-derivation | confirmed: 3 |\nand closes at ``-->`` there.\n"
    assert cc._closing_row_fail(opener) is not None
    cited = "| Pass 2 | seat | method: re-derivation | confirmed: 0 | notes: pass 1 stood at ``confirmed: 3`` |\n"
    assert cc._closing_row_fail(cited) is None


def test_a_stray_backtick_in_prose_never_swallows_the_ledger():
    """A code span never crosses a line: an unmatched backtick before the ledger and another after it
    are literal text, not one span (round 5 caught the unbounded closer scan)."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    raw = "Notes: use the `--slices flag here\n| Pass 2 | seat | method: re-derivation | confirmed: 3 |\nLater: the `--units flag there\n"
    assert cc._closing_row_fail(raw) is not None


def test_a_longer_backtick_run_does_not_close_a_shorter_span():
    """CommonMark 6.1: a span closes with a run of the SAME length — `x ``confirmed: 3`` y` is one
    single-backtick span whose content holds a double run; the counter inside stays masked."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    raw = (
        "| Pass 2 | seat | method: re-derivation | confirmed: 0 | notes: `x ``confirmed: 3`` y` |\n"
    )
    assert cc._closing_row_fail(raw) is None


def test_the_span_masker_blanks_exactly_the_content_between_equal_runs():
    """Pins the masker's arithmetic (round 6 fuzz found verdict-flipping cells for every off-by-one):
    delimiters kept, content blanked, a shorter closer never closes a longer opener, a longer one
    never closes a shorter, the scan resumes AFTER the closer."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    assert cc._mask_spans("a `b` c") == "a `x` c"
    assert cc._mask_spans("``x`y``") == "``xxx``"
    assert (
        cc._mask_spans("notes ``confirmed: 3` |") == "notes ``confirmed: 3` |"
    )  # unclosed double run: literal
    assert cc._mask_spans("`a``b`") == "`xxxx`"  # a longer run INSIDE a shorter span is content
    row = "| Pass 2 | seat | method: re-derivation | confirmed: 0 | notes ``confirmed: 3` |\n"
    assert cc._closing_row_fail(row) is not None  # the unclosed double run leaves the 3 live
    cell = "| Pass 2 | seat | confirmed: 0 | ````confirmed: 3confirmed: 3`` x |\n"
    assert cc._closing_row_fail(cell) is not None  # a 4-run opener, a 2-run closer: literal
    cell2 = "| Pass 2 | seat | confirmed: 3 x ``<!--|confirmed: 0``confirmed: 0`` |\n"
    assert (
        cc._closing_row_fail(cell2) is None
    )  # the span closes at the first equal run; the last token is 0


def test_the_fence_strip_runs_before_the_span_masker():
    """The ORDER pin: with the fence strip first, this line keeps its leading ``` and is never a Pass
    row (the line-start anchor); with the masker first, the inner backtick is blanked, the inline
    fence quote then matches and its delimiters are stripped, and the row surfaces at line start —
    the mask-first order was refused by fuzz for exactly that reason."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    raw = "```<!--`-->```| Pass 1 | method: re-derivation | confirmed: 3 |\n"
    assert cc._closing_row_fail(raw) is None


def test_a_run_touching_the_newline_before_the_ledger_never_hides_it():
    """The closer scan must stop AT the newline, not step over it (round 7's surviving mutant: a
    non-matching run whose last backtick touches the line end let the scan continue into the ledger)."""
    sys.path.insert(0, str(CHECK.parent))
    import check_convergence as cc  # noqa: E402

    doc = "notes `x ``\n| Pass 1 | seat | method: re-derivation | confirmed: 3 | see `\n"
    assert cc._closing_row_fail(doc) is not None


# --- mail-triage plan Phase B (T4.1, T4.2, T4.3, T4.10) --------------------------------------

_REVIEW_QUIET_IN_PROSE = (
    "# R\n\n## Pass Ledger\n\nThe loop needs a quiet final pass — a "
    "'found: 0, fixed: 0' round — which this text merely DESCRIBES.\n"
)
_REVIEW_QUIET_ROW = (
    "# R\n\n## Pass Ledger\n\n| Pass | Counters |\n|---|---|\n"
    "| Pass 2 | found: 0, new: 0, confirmed: 0, fixed: 0, unexecuted: 0 |\n"
)
_EXECUTED_CITING = """# Plan X

**Status:** EXECUTED 2026-08-03 (whole-plan review: docs/development/reviews/2026-08-03-plan-x-review.md)

## Phase A
Done. src/app/handler.py:42
"""


def test_an_untracked_converged_plan_is_graded_before_it_is_staged(repo: Path) -> None:
    """T4.1 (01M1RFN3): a plan written and committed in one motion was untracked at the gate
    run and skipped as "checked at staging" — then staged and committed with no gate between.
    An untracked plan that CLAIMS convergence is a target now."""
    _git(repo, "commit", "--allow-empty", "-qm", "seed")
    p = repo / "docs/development/plans/2026-06-18-plan-x.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(PLAN_NO_EVIDENCE)
    assert _check(repo) == 1, "an untracked CONVERGED plan with no evidence must fail"
    p.write_text(PLAN_NO_CLAIM)
    assert _check(repo) == 0, "an untracked draft that claims nothing stays ignored"


def test_a_quiet_round_in_prose_never_satisfies_the_executed_citation(repo: Path) -> None:
    """T4.3 (01M1SQZ80): the EXECUTED branch searched the cited review's WHOLE text for the quiet
    pattern, so pasting the gate's own error message satisfied it; the pattern is read from a
    Pass-Ledger ROW only."""
    _git(repo, "commit", "--allow-empty", "-qm", "seed")
    rv = repo / "docs/development/reviews/2026-08-03-plan-x-review.md"
    rv.parent.mkdir(parents=True, exist_ok=True)
    plan = repo / "docs/development/plans/2026-08-03-plan-x.md"
    plan.parent.mkdir(parents=True, exist_ok=True)
    plan.write_text(_EXECUTED_CITING)
    rv.write_text(_REVIEW_QUIET_IN_PROSE)
    _git(repo, "add", "-A")
    assert _check(repo) == 1, "prose that describes a quiet round is not a quiet round"
    rv.write_text(_REVIEW_QUIET_ROW)
    _git(repo, "add", "-A")
    assert _check(repo) == 0


def test_a_committed_executed_plan_whose_review_is_missing_is_reported_advisory(
    repo: Path,
) -> None:
    """T4.2 (01M1SNCXH6, 01M1SNX21, 01M1SP32G): once the EXECUTED flip is COMMITTED the plan left
    the worklist forever. A committed EXECUTED plan whose cited review is missing, and an
    archived plan committed mid-flight, are now REPORTED on every run — advisory, never a red
    (the same asymmetry as check_review_coverage's committed-nonquiet sweep)."""
    plan = repo / "docs/development/plans/2026-08-03-plan-x.md"
    plan.parent.mkdir(parents=True, exist_ok=True)
    plan.write_text(_EXECUTED_CITING)
    arch = repo / "docs/development/plans/archived/2026-07-01-plan-y.md"
    arch.parent.mkdir(parents=True, exist_ok=True)
    arch.write_text("# Y\n\n**Status:** DRAFT\n\n## Phase 1\nx\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "landed ungated")
    rc, out = _check_out(repo)
    assert rc == 0, out
    assert out.startswith("⚠"), out
    assert "2026-08-03-plan-x.md" in out and "2026-07-01-plan-y.md" in out, out


def test_the_rederivation_message_names_the_closing_row_grammar(repo: Path) -> None:
    """T4.10 (01M1SR1WK): the refusal names the exact cell grammar the grader accepts, so a
    reader does not guess where the label goes."""
    p = repo / "docs/development/plans/2026-06-18-plan-x.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(COMPLIANT_PLAN.replace("re-derivation", "citation"))
    _git(repo, "add", "-A")
    rc, out = _check_out(repo)
    assert rc == 1
    assert "`| Pass N | … | method: re-derivation — … |`" in out, out


def test_proof_citation_accepts_every_scaffold_types_sources(repo: Path) -> None:
    """T4.8 (01M1V67JR): the grounding floor named py/ts/js/sql/md alone, so a CONVERGED plan
    whose evidence cites an Astro page, an ESM module or a Vue component read as uncited."""
    doc = (
        COMPLIANT_PLAN.replace("src/app/handler.py:42", "src/pages/index.astro:42")
        .replace("db/schema.sql:10", "src/lib/util.mjs:10")
        .replace("tests/test_handler.py:11", "src/components/Handler.vue:11")
    )
    assert "handler.py" not in doc
    assert _run(repo, "docs/development/plans/2026-06-18-plan-x.md", doc) == 0
