"""The commit-moment path of check_review_coverage (explicit staged paths).

Found live 2026-08-30: a phase review failing FOUR blocking rules was committed ungated —
the blocking path only scans `git status`, so a review committed without a gate run while
dirty escapes it forever (the advisory sweep checks a narrower class set and never saw it).
The class fix is a pre-commit hook that passes the STAGED review paths to the checker; this
tests the checker side: positional paths are graded with the full blocking battery and a
failing artifact exits non-zero at the moment it tries to enter history.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "scripts" / "enforcement" / "check_review_coverage.py"

_BAD_REVIEW = (
    "# R\n**Status:** CONVERGED\n**Surface:** abc\n\n"
    "```\n# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)\n```\n\n"
    "## Coverage Checklist\n\n| # | Class | Verdict | Evidence |\n|---|---|---|---|\n"
    "| 1 | fail-open/fail-closed | CLEAN | hunted x.py guards |\n"
    "| 2 | cost/quota accounting | CLEAN | limits in x.py:3 |\n"
    "| 3 | boundary/sentinel/prefix | CLEAN | prefixes in x.py:9 |\n"
    "| 4 | behavior-without-a-test | CLEAN | tests/test_x.py |\n\n"
    "## Pass Ledger\n\n"
    "- Pass 1 (WIDE) — method: citation — found: 1, fixed: 1\n"
    "- Pass 2 (CLOSING) — method: citation — found: 0, fixed: 0\n"
)

_GOOD_TAIL = "- Pass 2 (CLOSING) — method: re-derivation — found: 0, fixed: 0\n"


def _run_on(tmp_path: Path, text: str) -> subprocess.CompletedProcess:
    f = tmp_path / "2026-08-30-x-review.md"
    f.write_text(text, encoding="utf-8")
    return subprocess.run(
        [sys.executable, str(SCRIPT), str(f)],
        cwd=REPO,
        capture_output=True,
        text=True,
        timeout=120,
    )


def test_explicit_path_grades_with_the_full_blocking_battery(tmp_path):
    r = _run_on(tmp_path, _BAD_REVIEW)
    assert r.returncode == 1, f"rc={r.returncode} out={r.stdout!r} err={r.stderr!r}"
    assert "re-deriv" in r.stdout, r.stdout


def test_explicit_path_passes_a_clean_artifact(tmp_path):
    good = _BAD_REVIEW.replace(
        "- Pass 2 (CLOSING) — method: citation — found: 0, fixed: 0\n", _GOOD_TAIL
    )
    r = _run_on(tmp_path, good)
    assert r.returncode == 0, f"rc={r.returncode} out={r.stdout!r} err={r.stderr!r}"


def test_a_rotated_archive_md_is_not_a_review_artifact(tmp_path: Path):
    """A long review rotates its older finding tables into `<stem>-archive.md` (/fabrik-review
    § Reporting, web-ecommerce-factory 01M1QT171DPCGA43Q0739WGGNP: 417 KB against a 256 KB Read
    ceiling). The archive carries counter rows and no checklist by design — read as a review it
    would fail the checklist rule; `_changed_md` must skip it."""
    import importlib.util

    sp = importlib.util.spec_from_file_location("crc", SCRIPT)
    crc = importlib.util.module_from_spec(sp)
    sp.loader.exec_module(crc)
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    d = tmp_path / "docs" / "development" / "reviews"
    d.mkdir(parents=True)
    (d / "2026-09-05-x-review-archive.md").write_text(
        "# archive\n\n| Pass 1 | method: citation | found: 3 | new: 3 | fixed: 3 | finders: p |\n"
    )
    (d / "2026-09-05-x-review.md").write_text("# head\n\n## Coverage Checklist\n")
    paths, _notes, untracked = crc._changed_md(tmp_path, "docs/development/reviews/")
    names = sorted(p.name for p in [*paths, *untracked])  # untracked drafts ride the third slot
    assert names == ["2026-09-05-x-review.md"], names


def test_a_changed_path_with_no_hunt_row_is_refused(tmp_path):
    """T4.4 (01M20W9QK): the grader graded the Hunt rows that EXIST and never compared them with
    the receipt's own Changed list — 11 of 18 files went unhunted for seven rounds. A Changed
    path without a `Hunt:` row is refused; the template's own shape (one row per path) passes."""
    changed = "**Command:** /fabrik-review · **Changed:** `x.py`, `y.py`\n\n"
    hunt_x = "| 5 | Hunt: `x.py` — every changed hunk | CLEAN | read |\n"
    text = (
        _BAD_REVIEW.replace("# R\n", "# R\n" + changed)
        .replace(
            "| 4 | behavior-without-a-test | CLEAN | tests/test_x.py |\n",
            "| 4 | behavior-without-a-test | CLEAN | tests/test_x.py |\n" + hunt_x,
        )
        .replace("- Pass 2 (CLOSING) — method: citation — found: 0, fixed: 0\n", _GOOD_TAIL)
    )
    r = _run_on(tmp_path, text)
    assert r.returncode == 1, r.stdout
    assert "`y.py`" in r.stdout and "Hunt" in r.stdout, r.stdout
    r = _run_on(
        tmp_path,
        text.replace(hunt_x, hunt_x + "| 6 | Hunt: `y.py` — every changed hunk | CLEAN | read |\n"),
    )
    assert r.returncode == 0, r.stdout


def test_a_running_review_records_own_receipt_is_graded_even_when_unchanged(tmp_path, monkeypatch):
    """T4.5 (01M28K3F44): a receipt COMMITTED and unchanged was invisible to the blocking scan
    while its review was still RUNNING. With a live review-family record in COMMAND_RUN_DIR, the
    receipts written since its start are graded with the full battery regardless of git state."""
    import json
    import subprocess as sp
    import time

    repo = tmp_path / "repo"
    (repo / "docs/development/reviews").mkdir(parents=True)
    sp.run(["git", "init", "-q"], cwd=repo, check=True)
    sp.run(["git", "config", "user.email", "t@t"], cwd=repo, check=True)
    sp.run(["git", "config", "user.name", "t"], cwd=repo, check=True)
    started = time.time() - 60
    f = repo / "docs/development/reviews/2026-08-30-x-review.md"
    f.write_text(
        _BAD_REVIEW.replace(
            "| 1 | fail-open/fail-closed | CLEAN | hunted x.py guards |",
            "| 1 | fail-open/fail-closed | UNCHECKED |",
        ),
        encoding="utf-8",
    )
    sp.run(["git", "add", "-A"], cwd=repo, check=True)
    sp.run(["git", "commit", "-qm", "receipt committed unchanged"], cwd=repo, check=True)
    runs = tmp_path / "runs"
    runs.mkdir()
    (runs / "s9.json").write_text(
        json.dumps(
            {
                "command": "fabrik-review",
                "state": "running",
                "started_epoch": started,
                "repo_root": str(repo),
            }
        )
    )
    env = dict(__import__("os").environ, COMMAND_RUN_DIR=str(runs), CLAUDE_SESSION_ID="s9")
    r = sp.run(
        [sys.executable, str(SCRIPT), "--root", str(repo)],
        cwd=repo,
        capture_output=True,
        text=True,
        timeout=120,
        env=env,
    )
    assert r.returncode == 1, f"rc={r.returncode} out={r.stdout!r}"
    assert "UNCHECKED" in r.stdout, r.stdout
    env.pop("CLAUDE_SESSION_ID")
    r = sp.run(
        [sys.executable, str(SCRIPT), "--root", str(repo)],
        cwd=repo,
        capture_output=True,
        text=True,
        timeout=120,
        env=env,
    )
    assert r.returncode == 0, "with no running record the committed receipt stays an advisory"


def test_the_changed_list_reads_paths_only_across_wrapped_lines_and_never_from_a_fence(tmp_path):
    """Review round 1 (Phase B): every backticked token on the Changed line was demanded a
    `Hunt:` row (an md5 is not a path); a wrapped list lost every path after the first line;
    and a `Hunt:` row inside a quoted template example satisfied a real path."""
    good = _BAD_REVIEW.replace(
        "- Pass 2 (CLOSING) — method: citation — found: 0, fixed: 0\n", _GOOD_TAIL
    )
    hunt_x = "| 5 | Hunt: `x.py` — every changed hunk | CLEAN | read |\n"
    anchor = "| 4 | behavior-without-a-test | CLEAN | tests/test_x.py |\n"
    with_x = good.replace(anchor, anchor + hunt_x)
    r = _run_on(tmp_path, with_x.replace("# R\n", "# R\n**Changed:** `x.py` (md5 `deadbeef`)\n\n"))
    assert r.returncode == 0, r.stdout
    r = _run_on(tmp_path, with_x.replace("# R\n", "# R\n**Changed:** `x.py`,\n`y.py`\n\n"))
    assert r.returncode == 1 and "`y.py`" in r.stdout, r.stdout
    fenced = "```\n| 6 | Hunt: `y.py` — example | CLEAN | read |\n```\n"
    r = _run_on(
        tmp_path,
        with_x.replace("# R\n", "# R\n**Changed:** `x.py`, `y.py`\n\n" + fenced),
    )
    assert r.returncode == 1 and "`y.py`" in r.stdout, r.stdout


def test_a_running_record_pulls_only_its_own_receipts(tmp_path):
    """Review round 1 (Phase B): the running-record read joined every fresh file under reviews/ —
    a rotated `-archive.md` (no checklist by design), a sibling's receipt of another plan, and
    it fired for artifact reviews (spec/plan-review) that write no receipt at all."""
    import json
    import os
    import subprocess as sp
    import time

    repo = tmp_path / "repo"
    (repo / "docs/development/reviews").mkdir(parents=True)
    sp.run(["git", "init", "-q"], cwd=repo, check=True)
    started = time.time() - 60
    clean = _BAD_REVIEW.replace(
        "- Pass 2 (CLOSING) — method: citation — found: 0, fixed: 0\n", _GOOD_TAIL
    )
    unchecked = _BAD_REVIEW.replace(
        "| 1 | fail-open/fail-closed | CLEAN | hunted x.py guards |",
        "| 1 | fail-open/fail-closed | UNCHECKED |",
    )
    mine = repo / "docs/development/reviews/2026-09-13-plan-a-review.md"
    mine.write_text(
        clean + "\nPlan: docs/development/plans/2026-09-13-plan-a.md\n", encoding="utf-8"
    )
    (repo / "docs/development/reviews/2026-09-13-plan-a-review-archive.md").write_text(
        unchecked + "\nPlan: docs/development/plans/2026-09-13-plan-a.md\n", encoding="utf-8"
    )  # names the plan too — only the archive rule keeps it out
    (repo / "docs/development/reviews/2026-09-13-plan-b-review.md").write_text(
        unchecked + "\nPlan: docs/development/plans/2026-09-13-plan-b.md\n", encoding="utf-8"
    )
    sp.run(["git", "add", "-A"], cwd=repo, check=True)
    sp.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "all committed"],
        cwd=repo,
        check=True,
    )
    runs = tmp_path / "runs"
    runs.mkdir()

    def _rc(command: str) -> int:
        (runs / "s9.json").write_text(
            json.dumps(
                {
                    "command": command,
                    "state": "running",
                    "started_epoch": started,
                    "surface": "docs/development/plans/2026-09-13-plan-a.md (Phase B)",
                }
            )
        )
        env = dict(os.environ, COMMAND_RUN_DIR=str(runs), CLAUDE_SESSION_ID="s9")
        return sp.run(
            [sys.executable, str(SCRIPT), "--root", str(repo)],
            cwd=repo,
            capture_output=True,
            text=True,
            timeout=120,
            env=env,
        ).returncode

    assert _rc("fabrik-review") == 0, (
        "only plan-a's clean receipt is this run's; archive + plan-b stay out"
    )
    assert _rc("fabrik-spec-review") == 0
    mine.write_text(
        unchecked + "\nPlan: docs/development/plans/2026-09-13-plan-a.md\n", encoding="utf-8"
    )
    sp.run(["git", "add", "-A"], cwd=repo, check=True)
    sp.run(
        [
            "git",
            "-c",
            "user.email=t@t",
            "-c",
            "user.name=t",
            "commit",
            "-qm",
            "own receipt regressed",
        ],
        cwd=repo,
        check=True,
    )
    assert _rc("fabrik-review") == 1, "the run's own committed receipt is graded"
    assert _rc("fabrik-spec-review") == 0, "an artifact review writes no receipt"
