import importlib.util, pathlib, sys, tempfile
def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path); m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m); return m
crc = load(sys.argv[1] if len(sys.argv)>1 else "scripts/enforcement/check_review_coverage.py", "crc")
HEAD = (
    "# Review\n\nStatus: CLOSED\n\n**Surface:** `HEAD abc` · diff md5 `x`\n\n"
    "Rubric: `python scripts/review_rubric.py --changed a.py` (output fenced below)\n\n"
    "```\n# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)\n"
    "rubric body\n```\n\n"
    "## Coverage Checklist\n\n| # | Class | Verdict | Evidence |\n|---|---|---|---|\n"
    "| 1 | fail-open vs fail-closed | CLEAN | probed a.py guards + callers |\n"
    "| 2 | cost/quota accounting | CLEAN | hunted a.py cost paths |\n"
    "| 3 | boundary/sentinel/prefix | CLEAN | hunted a.py parsers |\n"
    "| 4 | behavior-without-a-test | CLEAN | hunted tests/test_a.py + a.py handlers |\n\n"
    "## Pass Ledger\n\n"
    "| Pass 1 | method: citation | found: 3 | new: 3 | fixed: 3 | finders: opus |\n"
    "| Pass 2 | method: re-derivation | found: 0 | new: 0 | fixed: 0 | finders: opus |\n"
)
def graded(tail):
    d = pathlib.Path(tempfile.mkdtemp())/"docs"/"development"/"reviews"; d.mkdir(parents=True)
    p = d/"2026-09-09-confirmed-review.md"; p.write_text(HEAD+tail, encoding="utf-8"); return crc.check_file(p)

print("=== ITEM 3: mid-ledger join (Pass 1, Pass 2, <join 3/4>, Pass 5)")
join = "| Pass 3 | f | found: 3 issues | fixed: 1 | | Pass 4 | f | found: 0 items | fixed: 0 |\n"
errs = graded(join + "| Pass 5 | f | found: 0 | fixed: 0 |\n")
print(f"  {len(errs)} error(s):")
for e in errs: print("   *", e[:130])

print("\n=== ITEM 1: the PROSE ledger join, as the LAST ledger line")
prose = ("Pass 3: method: re-derivation, found: 5 issues, fixed: 0 "
         "Pass 4: method: re-derivation, found: 0, fixed: 0\n")
d = pathlib.Path(tempfile.mkdtemp())/"docs"/"development"/"reviews"; d.mkdir(parents=True)
p = d/"2026-09-09-prose-review.md"
p.write_text(HEAD.replace("## Pass Ledger\n\n| Pass 1 | method: citation | found: 3 | new: 3 | fixed: 3 | finders: opus |\n| Pass 2 | method: re-derivation | found: 0 | new: 0 | fixed: 0 | finders: opus |\n",
   "## Pass Ledger\n\nPass 1: method: citation, found: 3, fixed: 3\nPass 2: method: re-derivation, found: 1, fixed: 1\n" + prose), encoding="utf-8")
t,pr,o,r = crc._ledger_shapes(p.read_text(encoding="utf-8"))
print("  joined:", crc._joined_row(prose.replace(" "," ").rstrip()), " ordered last:", o[-1][:4] if o else None, " refusals:", len(r))
e2 = crc.check_file(p)
print(f"  check_file -> {len(e2)} error(s):")
for e in e2: print("   *", e[:130])
