services:
  authelia:
    image: authelia/authelia:4.39.19
    container_name: authelia
    restart: unless-stopped
    volumes:
    - /opt/authelia/config:/config
    environment:
      TZ: Europe/Istanbul
    networks:
    - fabrik
    labels:
    - traefik.enable=true
    - traefik.http.routers.authelia.entryPoints=websecure
    - traefik.http.routers.authelia.rule=Host(`auth.vps1.ocoron.com`)
    - traefik.http.routers.authelia.tls=true
    - traefik.http.routers.authelia.tls.certresolver=letsencrypt
    - traefik.http.services.authelia.loadbalancer.server.port=9091
    - traefik.http.routers.authelia-http.entryPoints=web
    - traefik.http.routers.authelia-http.rule=Host(`auth.vps1.ocoron.com`)
    - traefik.http.routers.authelia-http.middlewares=redirect-to-https
    - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    - traefik.http.middlewares.authelia-forward.forwardAuth.address=http://authelia:9091/api/authz/forward-auth
    - traefik.http.middlewares.authelia-forward.forwardAuth.trustForwardHeader=true
    - traefik.http.middlewares.authelia-forward.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
    - 10.99.0.1:9091:9091
networks:
  fabrik:
    external: true
