endpoints:
- name: spoke-canary
  group: apps
  url: https://canary.vps2.ocoron.com/
  interval: 60s
  client:
    timeout: 30s
  conditions:
  - '[STATUS] == 200'
  alerts:
  - type: custom
    failure-threshold: 3
    send-on-resolved: true
