services:
  glitchtip-web:
    image: glitchtip/glitchtip:latest
    container_name: glitchtip-web
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-main:5432/glitchtip
      REDIS_URL: redis://redis-main:6379/4
      SECRET_KEY: ${GLITCHTIP_SECRET_KEY}
      PORT: '8000'
    networks:
    - fabrik
    labels:
    - traefik.enable=true
    - traefik.docker.network=fabrik
    - traefik.http.routers.glitchtip-web.rule=Host(`errors.vps1.ocoron.com`)
    - traefik.http.routers.glitchtip-web.entrypoints=websecure
    - traefik.http.routers.glitchtip-web.tls=true
    - traefik.http.routers.glitchtip-web.tls.certresolver=letsencrypt
    - traefik.http.routers.glitchtip-web.middlewares=authelia-forward@docker
    - traefik.http.services.glitchtip-web.loadbalancer.server.port=8000
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
    - 10.99.0.1:8000:8000
  glitchtip-worker:
    image: glitchtip/glitchtip:latest
    container_name: glitchtip-worker
    restart: unless-stopped
    command:
    - ./bin/run-celery-with-beat.sh
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-main:5432/glitchtip
      REDIS_URL: redis://redis-main:6379/4
      SECRET_KEY: ${GLITCHTIP_SECRET_KEY}
      PORT: '8000'
      CELERY_WORKER_CONCURRENCY: '2'
      CELERY_WORKER_MAX_TASKS_PER_CHILD: '10000'
    networks:
    - fabrik
    deploy:
      resources:
        limits:
          memory: 512M
networks:
  fabrik:
    external: true
