#!/usr/bin/env python3
# AFTER-EDIT: tests/test_sync_trigger_coverage.py, scripts/fabrik_synced_manifest.py
"""Gate: every FLEET-SYNCED surface must either TRIGGER the governance-sync or be declared a
deliberate non-trigger.

The bug this exists to make unreachable: `fabrik_synced_manifest.py` says WHAT is distributed to
~46 projects; the `governance-sync` `files:` filter in `.pre-commit-config.yaml` decides which
edits actually FIRE that distribution. When a path is in the first list and not the second, you
edit a fleet-wide file, commit it, and it silently never ships — the fleet keeps running the old
copy. That happened twice on 2026-08-09 (the `release_cut.py` review fix sat un-distributed until
a manual `--force` sync), which is why the filter is no longer allowed to be maintained by memory.

Deliberate non-triggers are legitimate and documented (CLAUDE.md § Sync-consciousness): RUN_SCRIPTS,
`.windsurf/workflows/`, and most reference docs ride the NEXT unrelated sync rather than paying a
fleet-wide distribution on every edit. So this gate does not demand universal coverage — it demands
that the choice was made CONSCIOUSLY: covered by the filter, or listed below. A brand-new manifest
entry matches neither and fails until someone decides which it is.

Direction: manifest → filter only. A filter alternative with no manifest entry (a path that
triggers a sync but is not itself distributed) is harmless — it costs one extra sync, it never
loses one — so it is out of scope here rather than an undetected defect.

Usage:
    python scripts/enforcement/check_sync_trigger_coverage.py          # gate (exit 1 on a gap)
    python scripts/enforcement/check_sync_trigger_coverage.py --fix    # print the regex to add
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

DEFAULT_HUB = Path("/opt/fabrik")


def hub_root(script: Path | None = None) -> Path | None:
    """The hub checkout this script belongs to, or None if this is a synced project copy.

    This script is itself fleet-synced with the rest of `scripts/enforcement/`, so it runs in
    ~48 repos that have no manifest to compare against. Naively deriving the root from
    `__file__` made a project copy read the PROJECT as if it were the hub and die on a
    FileNotFoundError, failing every project's Tier-2 gate. Pinning the root to a literal
    `/opt/fabrik` fixed that but broke the other direction: a `git worktree` of the hub (a
    documented workflow, CLAUDE.md § EXIT) lives at a different path, so the gate silently
    skipped itself exactly where hub work happens — a vacuous green.

    So: derive the candidate root from `__file__`, and accept it ONLY if the manifest is
    actually sitting in it. A hub worktree qualifies; a project copy cannot, and declines
    rather than reaching across into /opt/fabrik to report a hub gap as a project failure.
    """
    script = (script or Path(__file__)).resolve()
    if len(script.parents) > 2:
        candidate = script.parents[2]
        if (candidate / "scripts" / "fabrik_synced_manifest.py").is_file():
            return candidate
    return None


FABRIK_ROOT = hub_root() or DEFAULT_HUB

# Synced, but deliberately NOT a sync trigger — each rides the next unrelated distribution.
# Prefixes, matched against the repo-relative path. Adding a row here is a CONSCIOUS decision
# that "editing this need not reach the fleet today"; that is exactly what the gate is asking for.
# SEEDED_NOT_ENFORCED entries are NOT re-listed here — they are read from the manifest itself.
DECLARED_NON_TRIGGERS = (
    "templates/scaffold/scripts/",  # RUN_SCRIPTS (rund/runc/…): dev conveniences, not governance
    ".windsurf/workflows/",  # workflow templates: consumed on the next sync
    # Reference docs are declared ONE BY ONE, never as a blanket `docs/reference/` prefix: the
    # filter individually names technology-stack-decision-guide.md, i.e. someone decided that
    # one SHOULD trigger — a blanket prefix would short-circuit it before the regex is ever
    # consulted, so dropping it from the filter would go undetected (the very bug class this
    # gate exists for, reproduced inside the gate's own exemption list).
    "docs/reference/kilo/",  # regenerated nightly by the kilo pipeline — a machine-written diff
    "docs/reference/MD/",  # authoring templates: consumed on the next sync
    "docs/reference/long-command-monitoring.md",
    "docs/reference/mobile-responsive-testing-guide.md",
    "docs/reference/convergence-prompts.md",
    "docs/operations/",  # lifecycle docs: read-on-demand, not enforcement
    "libs/subagents",  # vendored module: projects re-vendor deliberately
    # AUTO-GENERATED by sync_projects.py and committed by automated chore(catalog) commits.
    # It was briefly a trigger; that made a ROBOT the thing that decides when the fleet gets a
    # distribution — and because the sync copies WORKING-TREE contents (shutil.copy2), an
    # unattended catalog regen would force-ship whatever half-finished .windsurf/rules/ or
    # scripts/enforcement/ edits a sibling agent happens to have uncommitted, to ~48 repos.
    # A deliberate rules/enforcement edit is made by an agent who knows the tree state; a
    # catalog regen is not. It rides the next such sync instead (hours, and it regenerates
    # anyway) — a far better trade than an unattended fleet push (native review finding).
    "docs/PROJECT_CATALOG.md",
)

# Every category the derivation depends on. A rename must fail loudly: a silently-dropped
# category stops being coverage-checked while the gate still reports green (review finding).
REQUIRED_MANIFEST_ATTRS = (
    "GOVERNANCE_FILES",
    "GOVERNANCE_TEMPLATES",
    "AGENT_HOOK_FILES",
    "REFERENCE_DOCS",
    "GOVERNANCE_DIRS",
    "VENDORED_DIRS",
    "CORE_SCRIPTS",
    "RUN_SCRIPTS",
    "RUN_SCRIPTS_SRC_DIR",
    "ENFORCEMENT_DIR",
    "SEEDED_NOT_ENFORCED",
)


class CoverageError(RuntimeError):
    """The gate could not read its inputs — fail loudly; a silent pass is worse than no gate."""


def trigger_pattern(config: Path, hook_id: str = "governance-sync") -> str:
    """The named hook's `files:` regex, read STRUCTURALLY from .pre-commit-config.yaml.

    Parsed as YAML and looked up BY HOOK ID. A string-scan for the id followed by the next
    `files:` line silently reads a LATER hook's filter when hooks are reordered, and returns
    the scalar indicator (`>-`) instead of the pattern when the filter is a block scalar —
    both validate coverage against the wrong regex, i.e. a false pass (review finding).
    """
    try:
        text = config.read_text(encoding="utf-8")
    except OSError as e:
        raise CoverageError(f"cannot read {config}: {e}") from e
    try:
        import yaml  # pre-commit's own dependency; present wherever this gate runs
    except ImportError:
        yaml = None  # type: ignore[assignment]
    if yaml is not None:
        try:
            data = yaml.safe_load(text) or {}
        except Exception as e:  # noqa: BLE001 — a malformed config must fail loudly, not pass
            raise CoverageError(f"cannot parse {config}: {e}") from e
        if not isinstance(data, dict):
            # `yes` / a bare list / a string all parse as VALID yaml but are not a config; the
            # .get() below would raise AttributeError, which is not a CoverageError and surfaces
            # as an unexplained crash (pool finder, reproduced).
            raise CoverageError(f"{config} does not parse to a mapping (got {type(data).__name__})")
        for repo in data.get("repos", []) or []:
            for hook in (repo or {}).get("hooks", []) or []:
                if (hook or {}).get("id") == hook_id:
                    pattern = (hook.get("files") or "").strip()
                    if not pattern:
                        raise CoverageError(f"hook {hook_id!r} has no files: filter")
                    return pattern
        raise CoverageError(f"no {hook_id!r} hook in {config}")
    # No PyYAML: scan ONLY this hook's own block, so a later hook's filter cannot be stolen.
    # Anchor on the real `- id: <hook>` LINE — a bare substring search also matches a comment
    # or another hook's `name:` that merely mentions the id, which then truncates the block at
    # the real hook and raises a spurious "no files: filter" (reproduced by the review).
    start = re.search(rf"^\s*-\s*id:\s*['\"]?{re.escape(hook_id)}['\"]?\s*$", text, re.M)
    if not start:
        raise CoverageError(f"no {hook_id!r} hook in {config}")
    block = text[start.start() :]
    nxt = re.search(r"^\s*- id:", block[start.end() - start.start() :], re.M)
    if nxt:
        block = block[: (start.end() - start.start()) + nxt.start()]
    m = re.search(r"^\s*files:\s*(.+)$", block, re.M)
    if not m:
        raise CoverageError(f"hook {hook_id!r} has no files: filter")
    return m.group(1).strip().strip("'\"")


def running_on_hub(script: Path | None = None) -> bool:
    """True where both lists live — any hub checkout, including a worktree. See `hub_root`."""
    return hub_root(script) is not None


def _manifest():
    """The hub's synced manifest module — the canonical WHAT-is-distributed list."""
    spec = importlib.util.spec_from_file_location(
        "fabrik_synced_manifest", FABRIK_ROOT / "scripts" / "fabrik_synced_manifest.py"
    )
    if spec is None or spec.loader is None:
        raise CoverageError("cannot load scripts/fabrik_synced_manifest.py")
    man = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(man)
    except OSError as e:
        raise CoverageError(f"cannot read scripts/fabrik_synced_manifest.py: {e}") from e
    return man


def synced_surfaces() -> set[str]:
    """Every repo-relative path the manifest distributes (files + directory prefixes)."""
    man = _manifest()
    missing = [a for a in REQUIRED_MANIFEST_ATTRS if not hasattr(man, a)]
    if missing:
        raise CoverageError(
            f"manifest is missing {', '.join(missing)} — renamed? A silently dropped category "
            "stops being coverage-checked while this gate still reports green"
        )

    out: set[str] = set()

    def add(value: object, prefix: str = "") -> None:
        name = value[0] if isinstance(value, tuple) else value
        if not isinstance(name, str) or not name:
            return
        # Prefix unless the entry already carries it — a future nested CORE_SCRIPTS entry
        # ("sub/tool.py") must become "scripts/sub/tool.py", not a bare, wrong path.
        out.add(name if not prefix or name.startswith(prefix) else f"{prefix}{name}")

    for attr in ("GOVERNANCE_FILES", "GOVERNANCE_TEMPLATES", "AGENT_HOOK_FILES", "REFERENCE_DOCS"):
        for item in getattr(man, attr, []) or []:
            add(item)
    # Directory entries are PREFIXES — normalise the trailing slash so the probe below
    # tests a child path against a prefix regex (a bare dir name never matches one).
    for attr in ("GOVERNANCE_DIRS", "VENDORED_DIRS"):
        for item in getattr(man, attr, []) or []:
            name = item[0] if isinstance(item, tuple) else item
            if isinstance(name, str) and name:
                out.add(name.rstrip("/") + "/")
    # CORE_SCRIPTS are bare filenames living under scripts/
    for item in getattr(man, "CORE_SCRIPTS", []) or []:
        add(item, prefix="scripts/")
    # RUN_SCRIPTS are bare filenames under the scaffold template dir
    run_dir = man.RUN_SCRIPTS_SRC_DIR
    for item in getattr(man, "RUN_SCRIPTS", []) or []:
        add(item, prefix=f"{run_dir.rstrip('/')}/")
    enf = getattr(man, "ENFORCEMENT_DIR", "scripts/enforcement")
    if enf:
        out.add(enf.rstrip("/") + "/")
    return out


def _declared(surface: str, seeded: frozenset[str] = frozenset()) -> bool:
    """True iff this surface is a declared non-trigger — either listed above, or SEEDED_NOT_ENFORCED
    in the manifest (distributed once, then owned by each project).

    Matching is EXACT or a real directory prefix: a bare prefix must not shadow a sibling
    (`libs/subagents` must not exempt `libs/subagents_new_thing.py`; review finding).
    """
    if surface in seeded:
        return True
    for d in DECLARED_NON_TRIGGERS:
        base = d.rstrip("/")
        if surface == base or surface.startswith(base + "/"):
            return True
    return False


def _probe(path: str) -> str:
    """A concrete path to test the regex against (a directory entry needs a child)."""
    return f"{path}probe.py" if path.endswith("/") else path


def uncovered(root: Path | None = None) -> list[str]:
    """Synced surfaces that neither trigger a sync nor are declared deliberate non-triggers."""
    root = root or FABRIK_ROOT
    pattern = trigger_pattern(root / ".pre-commit-config.yaml")
    surfaces = synced_surfaces()
    if not surfaces:
        # A broken/renamed manifest constant would yield nothing to check and the gate
        # would report success — the exact silent hole it exists to prevent, reproduced
        # inside the gate itself (review finding).
        raise CoverageError(
            "derived ZERO synced surfaces from the manifest — the derivation is broken "
            "(renamed constant? import failure?); refusing to report a vacuous pass"
        )
    seeded = frozenset(str(s) for s in (getattr(_manifest(), "SEEDED_NOT_ENFORCED", None) or ()))
    gaps = []
    for surface in sorted(surfaces):
        if _declared(surface, seeded):
            continue
        if re.search(pattern, _probe(surface)):
            continue
        gaps.append(surface)
    return gaps


def fix_suggestion(root: Path | None = None) -> str:
    """The regex alternatives to paste into the governance-sync files: filter."""
    parts = []
    for surface in uncovered(root):
        if surface.endswith("/"):
            parts.append("^" + re.escape(surface))
        else:
            parts.append("^" + re.escape(surface) + "$")
    return "|".join(parts)


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if not running_on_hub():
        # This script syncs to ~46 projects with the rest of scripts/enforcement/; there is no
        # manifest there to compare against. Skip, never crash their Tier-2 gate.
        print("(not the hub — sync-trigger coverage check skipped)")
        return 0
    try:
        gaps = uncovered()
    except CoverageError as e:
        print(f"✗ sync-trigger coverage: {e}")
        return 1
    except Exception as e:  # noqa: BLE001 — a gate must never emit a bare traceback to the fleet
        print(f"✗ sync-trigger coverage: unexpected {type(e).__name__}: {e}")
        return 1
    if not gaps:
        print("✓ sync-trigger coverage: every synced surface triggers a sync or is declared")
        return 0
    print("✗ sync-trigger coverage — these are DISTRIBUTED fleet-wide but editing them fires NO")
    print("  governance-sync, so a commit ships nothing and the fleet keeps the old copy:")
    for g in gaps:
        print(f"    · {g}")
    print("\n  Fix ONE of:")
    print("   (a) add to the governance-sync files: filter in .pre-commit-config.yaml —")
    print(f"       |{fix_suggestion()}")
    print("   (b) if it should ride the next unrelated sync by design, declare it in")
    print("       scripts/enforcement/check_sync_trigger_coverage.py::DECLARED_NON_TRIGGERS")
    if "--fix" in args:
        print(f"\n{fix_suggestion()}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
