"""RUBRIC_RUN must credit a RUN, not a mention (trade-intelligence 01M17Z7Q).

A thrice-converged plan carried `review_rubric.py --changed <the paths this plan will
touch>` — script NAMED, placeholder never expanded, pack list an estimate missing the
two packs whose sweeps then produced HIGH findings within minutes. The bare-filename
regex credited the prose. The proof of a run is the script's own generated output
header, which can only exist if it executed — and it lives inside the fenced paste the
command mandates, so the search must read RAW text (the fence-stripped search was the
circular trap check_convergence:383-389 already documents).
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
_spec = importlib.util.spec_from_file_location(
    "crc_rubric_probe", REPO / "scripts" / "enforcement" / "check_review_coverage.py"
)
crc = importlib.util.module_from_spec(_spec)
sys.modules["crc_rubric_probe"] = crc
_spec.loader.exec_module(crc)

_HEADER = "# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)"

_SKELETON = (
    "# R\n**Status:** CONVERGED\n**Surface:** abc\n\n"
    "{rubric}\n\n"
    "## Coverage Checklist\n\n| # | Class | Verdict | Evidence |\n|---|---|---|---|\n"
    "| 1 | fail-open/fail-closed | CLEAN | hunted x.py guards |\n"
    "| 2 | cost/quota accounting | CLEAN | limits in x.py:3 |\n"
    "| 3 | boundary/sentinel/prefix | CLEAN | prefixes in x.py:9 |\n"
    "| 4 | behavior-without-a-test | CLEAN | tests/test_x.py |\n\n"
    "## Pass Ledger\n\n"
    "- Pass 1 (WIDE) — method: citation — found: 1, fixed: 1\n"
    "- Pass 2 (CLOSING) — method: re-derivation — found: 0, fixed: 0\n"
)


def _errs(tmp_path: Path, rubric_para: str) -> list[str]:
    f = tmp_path / "2026-08-30-x-review.md"
    f.write_text(_SKELETON.format(rubric=rubric_para), encoding="utf-8")
    return [e for e in crc.check_file(f) if "rubric" in e.lower()]


def test_a_prose_mention_with_placeholder_is_not_an_invocation(tmp_path):
    errs = _errs(
        tmp_path,
        "Rows derived from `review_rubric.py --changed <the paths this plan will touch>`.",
    )
    assert errs, "an unexpanded placeholder mention must not count as a rubric run"


def test_a_bare_prose_claim_is_not_an_invocation(tmp_path):
    errs = _errs(tmp_path, "Rubric: ran `python scripts/review_rubric.py --changed x.py`.")
    assert errs, "naming the script is not proof it ran"


def test_the_pasted_output_header_inside_a_fence_is(tmp_path):
    errs = _errs(tmp_path, "Rubric output, verbatim:\n\n```\n" + _HEADER + "\n## FLOOR\n```")
    assert not errs, errs
