"""D7 / D-206: both ledger grammars learn `confirmed:` and `unexecuted:`, and the exit rule
grades the counter the CONTRACT now names.

The redesign re-cuts what a quiet round is: a candidate CONFIRMED by execution counts, while
RECORDED and REFUTED rows never reopen the loop (D-206, superseding D-048's `found:` rule). So a
final ledger row may legitimately read `found: 4` and still be the exit round — if it CONFIRMED
nothing, fixed nothing and left nothing unexecuted.

Backward compatibility is the CONTRACT here (DD4), not a nicety: this file is fleet-synced to ~46
repos, whose committed receipts are all written in the old grammar. Two tests below are therefore
INVARIANCE guards measured against the committed gate at the plan's base SHA — the corpus is the
denominator, and every count they print carries it.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
from pathlib import Path
from types import ModuleType

REPO = Path(__file__).resolve().parents[2]
# The plan's base commit — the committed grammar every invariance guard compares against. The
# module imports only the standard library, so a `git show` copy runs standalone (no worktree:
# `git worktree add` writes the shared repo's registry).
BASE_SHA = "8092e8a8"
GATE_REL = "scripts/enforcement/check_review_coverage.py"


def _load(name: str, path: Path) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


crc = _load("crc_confirmed", REPO / GATE_REL)


def _corpus() -> list[Path]:
    """Every COMMITTED review receipt, from git itself — never a bare glob of a tracked path."""
    out = subprocess.run(
        ["git", "-C", str(REPO), "ls-files", "docs/development/reviews/*.md"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    return [REPO / f for f in out]


def _base_gate(tmp_path: Path) -> ModuleType:
    src = subprocess.run(
        ["git", "-C", str(REPO), "show", f"{BASE_SHA}:{GATE_REL}"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    p = tmp_path / "old_gate.py"
    p.write_text(src, encoding="utf-8")
    return _load("crc_base", p)


# A report the blocking reader accepts in full — so an assertion about the EXIT rule is never
# satisfied (or defeated) by an unrelated obligation. `Pass 2` is literal because the two-round
# minimum is a text match; the re-derivation row is the closing-pass mandate.
HEAD = (
    "# Review\n\nStatus: CLOSED\n\n**Surface:** `HEAD abc` · diff md5 `x`\n\n"
    "Rubric: `python scripts/review_rubric.py --changed a.py` (output fenced below)\n\n"
    "```\n# REVIEW RUBRIC — inject into EVERY finder prompt (generated by review_rubric.py)\n"
    "rubric body\n```\n\n"
    "## Coverage Checklist\n\n| # | Class | Verdict | Evidence |\n|---|---|---|---|\n"
    "| 1 | fail-open vs fail-closed | CLEAN | probed a.py guards + callers |\n"
    "| 2 | cost/quota accounting | CLEAN | hunted a.py cost paths |\n"
    "| 3 | boundary/sentinel/prefix | CLEAN | hunted a.py parsers |\n"
    "| 4 | behavior-without-a-test | CLEAN | hunted tests/test_a.py + a.py handlers |\n\n"
    "## Pass Ledger\n\n"
    "| Pass 1 | method: citation | found: 3 | new: 3 | fixed: 3 | finders: opus |\n"
    "| Pass 2 | method: re-derivation | found: 0 | new: 0 | fixed: 0 | finders: opus |\n"
)
# V1 — the canonical D7 closing row: `found:` is 4 and the round is still QUIET.
V1 = "| Pass 19 | opus×1 | found: 4, new: 2, confirmed: 0, fixed: 0, unexecuted: 0 | delta |\n"


def _graded(tmp_path: Path, tail: str) -> list[str]:
    d = tmp_path / "docs" / "development" / "reviews"
    d.mkdir(parents=True, exist_ok=True)
    p = d / "2026-09-09-confirmed-review.md"
    p.write_text(HEAD + tail, encoding="utf-8")
    return crc.check_file(p)


def _exit_errors(errs: list[str]) -> list[str]:
    return [e for e in errs if "final ledger round" in e]


def test_the_canonical_v1_row_exits_quiet_on_confirmed_zero_although_found_is_four(tmp_path):
    """D-206's whole point: `found: 4` with `confirmed: 0` is the exit round."""
    assert _graded(tmp_path, V1) == []


def test_a_confirmed_defect_in_the_final_round_fails_naming_confirmed(tmp_path):
    errs = _graded(
        tmp_path,
        "| Pass 19 | opus×1 | found: 4, new: 2, confirmed: 1, fixed: 1, unexecuted: 0 | delta |\n",
    )
    exits = _exit_errors(errs)
    assert exits and "confirmed: 1" in exits[0], errs
    assert "D-206" in exits[0] and "D-048" not in exits[0], exits


def test_an_unexecuted_candidate_in_the_final_round_fails_naming_unexecuted(tmp_path):
    errs = _graded(
        tmp_path,
        "| Pass 19 | opus×1 | found: 4, new: 2, confirmed: 0, fixed: 0, unexecuted: 1 | delta |\n",
    )
    exits = _exit_errors(errs)
    assert exits and "unexecuted: 1" in exits[0], errs


def test_an_old_grammar_final_row_still_grades_on_found(tmp_path):
    """INVARIANCE guard (DD4): a receipt with no `confirmed:` token anywhere grades exactly as it
    did before D7 — `found: 3` fails, `found: 0` passes. Its red is a mutation on a copy (the
    legacy branch neutered), asserted in the ticket's red-first record."""
    errs = _graded(tmp_path, "| Pass 3 | opus | found: 3 | new: 0 | fixed: 0 |\n")
    exits = _exit_errors(errs)
    assert exits and "raised 3" in exits[0], errs
    assert _graded(tmp_path, "| Pass 3 | opus | found: 0 | new: 0 | fixed: 0 |\n") == []


def test_the_cell_anchored_row_resolves_mega_first_with_or_without_its_closing_pipe():
    """GFM lets the closing pipe go, and a `|`-only terminator would make a correct closing row
    INERT — matching neither grammar, so `founds[-1]` grades the PREVIOUS round (fail-open)."""
    row = "| 19 | found: 0 | confirmed: 0 | fixed: 0 | unexecuted: 0 |"
    for line in (row, row.rstrip("|").rstrip()):
        _t, _p, ordered, refusals = crc._ledger_shapes(line + "\n")
        assert len(ordered) == 1, (line, ordered)
        assert ordered[0][:4] == (0, 0, 0, 0), (line, ordered)
        assert refusals == [], refusals


def test_corpus_the_widened_mega_row_matches_the_same_rows_and_the_new_slot_variant_far_more():
    """The `new:` slot D7 deliberately leaves OUT. Both counts are printed with their
    denominator: a count without one is indistinguishable from having looked at nothing."""
    files = _corpus()
    with_new_slot = re.compile(
        r"^\s*\|.*?\|\s*found:\s*(\d+)\s*(?:\||$)"
        r"(?:\s*new:\s*(\d+)\s*(?:\||$))?"
        r"(?:\s*confirmed:\s*(\d+)\s*(?:\||$))?"
        r"\s*fixed:\s*(\d+)\s*(?:\||$)"
        r"(?:\s*unexecuted:\s*(\d+)\s*(?:\||$))?"
    )
    shipped = slotted = lines = 0
    for p in files:
        for ln in p.read_text(encoding="utf-8", errors="replace").splitlines():
            lines += 1
            shipped += bool(crc._MEGA_ROW.match(ln))
            slotted += bool(with_new_slot.match(ln))
    print(
        f"_MEGA_ROW: shipped={shipped}, with-new-slot={slotted} "
        f"over {lines} lines in {len(files)} committed receipts"
    )
    assert len(files) > 200, f"corpus looks wrong: {len(files)} receipts"
    assert shipped == 2, f"the shipped regex must keep its 2 cell-anchored rows, got {shipped}"
    assert slotted > 10 * shipped, (
        f"an optional `new:` cell would flip {slotted} rows (of {lines} lines in {len(files)} "
        f"receipts) from the Pass grammar to MEGA-first, against {shipped} today"
    )


def test_pass_counters_ext_reads_the_counter_run_and_leaves_pass_counters_alone():
    line = "Pass 19: found: 0, confirmed: 3, fixed: 0"
    assert crc._pass_counters_ext(line) == (0, 3, 0, None)
    assert crc._pass_counters(line) == (0, 0), "the legacy strict pair must not widen"
    # a narrated token AFTER the run is not a counter — the whole-line-is-one-cell reading would
    # flip this row from not-quiet to quiet
    assert crc._pass_counters_ext("Pass 19: found: 5, fixed: 0 — delta (confirmed: 0)") == (
        5,
        None,
        0,
        None,
    )
    # the separate-cell shape: the new tokens live INSIDE the `found:` cell, `fixed:` in its own
    assert crc._pass_counters_ext(
        "| Pass 19 | o | **found: 0, confirmed: 0, unexecuted: 0** | **fixed: 0** |"
    ) == (0, 0, 0, 0)


def test_a_misordered_counter_run_is_refused_by_name_and_the_row_stays_in_ordered(tmp_path):
    """A `None` return would leave the row INERT and hand the exit to the previous round — the
    fail-open direction. The row stays, its counters are `None`, and the reason is reported."""
    line = "Pass 19: found: 0, fixed: 0, confirmed: 0"
    reason = crc._pass_counters_ext(line)
    assert isinstance(reason, str) and "confirmed" in reason, reason
    _t, _p, ordered, refusals = crc._ledger_shapes(line + "\n")
    assert [r[:4] for r in ordered] == [(0, None, 0, None)], ordered
    assert len(refusals) == 1 and "confirmed" in refusals[0], refusals
    errs = _graded(tmp_path, "- Pass 19: found: 0, fixed: 0, confirmed: 0\n")
    assert any(e.startswith("Pass row refused:") and "confirmed" in e for e in errs), errs
    assert crc._pass_counters_ext("Pass 19: found: 0, confirmed: 1, confirmed: 2, fixed: 0") == (
        "a second `confirmed:` counter in the run "
        "('found: 0, confirmed: 1, confirmed: 2, fixed: 0')"
    )


def test_corpus_every_committed_receipt_parses_and_grades_exactly_as_it_did_at_the_base_sha(
    tmp_path,
):
    """INVARIANCE guard, all three readers, 0 flips. Its red is a mutation on a copy (the `None`
    default for an absent `confirmed:`), asserted in the ticket's red-first record."""
    base = _base_gate(tmp_path)
    files = _corpus()
    assert len(files) > 200, f"corpus looks wrong: {len(files)} receipts"
    rows_old = rows_new = 0
    for p in files:
        text = p.read_text(encoding="utf-8", errors="replace")
        o_tables, o_prose, o_ordered, *_ = base._ledger_shapes(text)
        n_tables, n_prose, n_ordered, refusals = crc._ledger_shapes(text)
        rows_old += len(o_ordered)
        rows_new += len(n_ordered)
        assert [r[-1] for r in n_ordered] == [r[-1] for r in o_ordered], p
        assert [(r[0], r[2]) for r in n_ordered] == [(r[0], r[1]) for r in o_ordered], p
        assert all(r[1] is None and r[3] is None for r in n_ordered), p
        assert refusals == [], (p, refusals)
        assert (len(n_tables), len(n_prose)) == (len(o_tables), len(o_prose)), p
        assert crc._unparsed_pass_lines(text) == base._unparsed_pass_lines(text), p
        # reader 1 — the blocking gate, verbatim errors modulo the D-048 -> D-206 rewording
        assert _normalize(crc.check_file(p)) == _normalize(base.check_file(p)), p
        # reader 2 — the mega grammar, for the reports routed to it
        if crc._is_mega_report(p, text):
            assert _normalize(crc.check_mega_validation(p, REPO, live=False)) == _normalize(
                base.check_mega_validation(p, REPO, live=False)
            ), p
    print(f"parsed Pass rows: base={rows_old}, widened={rows_new} over {len(files)} receipts")
    assert rows_new == rows_old
    # reader 3 — the committed advisory, one sweep per gate version
    new_c = [e.split(": COMMITTED")[0] for e in crc._committed_nonquiet(REPO, set())]
    old_c = [e.split(": COMMITTED")[0] for e in base._committed_nonquiet(REPO, set())]
    print(f"committed advisories: base={len(old_c)}, widened={len(new_c)}")
    assert new_c == old_c


_D_CLAUSE = re.compile(r"\(a (?:FRESH|candidate) .*?D-\d+\)")


def _normalize(errs: list[str]) -> list[str]:
    """The one sanctioned text delta: the exit clause is re-keyed from D-048 to D-206."""
    return [_D_CLAUSE.sub("(CLAUSE)", e) for e in errs]


def test_the_line_normalisation_runs_before_the_readers_split_the_text():
    """GFM's notion of a line, imposed once: a zero-width character renders as nothing (so
    `confirmed<ZWSP>: 3` looks like a counter and parses as none) and a `U+2028` splits the row
    in Python but not in a renderer (so the counter fragment lands on a line no reader sees)."""
    zwsp = "| Pass 3 | m | found: 0, confirmed\u200b: 3, fixed: 0 |\n"
    _t, _p, ordered, _r = crc._ledger_shapes(zwsp)
    assert [r[:4] for r in ordered] == [(0, 3, 0, None)], ordered
    split = "| Pass 3 | m | found: 0, confirmed: 3,\u2028fixed: 0 |\n"
    body = crc._strip_fences(split)
    assert "\u2028" not in body and len(body.splitlines()) == 1, repr(body)
    _t, _p, ordered, _r = crc._ledger_shapes(split)
    assert [r[:4] for r in ordered] == [(0, 3, 0, None)], ordered
    # the set is REUSED from _LINE_BREAKS, never retyped
    assert set(crc._LINE_BREAKS) - set("\r\n") <= {chr(c) for c in crc._GFM_NORMALIZE}
    # the header window (built by splitting RAW text) is normalised too
    hidden = "# Review" + "\u2028filler" * 10 + "\n**Status:** IN-PROGRESS\n"
    assert len(hidden.splitlines()) > 10, "fixture must push Status out of the raw 10-line zone"
    assert crc._in_progress(hidden) is True


MEGA = (
    "# Cross-Epic Validation Report\nSurface: {h2}\n\n"
    "| round | found: | confirmed: | fixed: | md5(start) → md5(end) |\n"
    "|------:|-------:|---|---|---|\n"
    "| 1 | found: 0 | confirmed: 0 | fixed: 0 | {h1} → {h2} |\n"
    "| 2 | found: 0 | confirmed: {c} | fixed: 0 | {h2} → {h2} |\n"
)


def test_the_mega_grammar_unpacks_the_widened_row_and_reads_confirmed(tmp_path):
    h1, h2 = "a" * 32, "b" * 32
    p = tmp_path / "2026-09-09-mega-x-validation-review.md"
    p.write_text(MEGA.format(h1=h1, h2=h2, c=0), encoding="utf-8")
    assert crc.check_mega_validation(p, tmp_path, live=False) == []
    p.write_text(MEGA.format(h1=h1, h2=h2, c=3), encoding="utf-8")
    errs = crc.check_mega_validation(p, tmp_path, live=False)
    assert any("final ledger round reads confirmed: 3" in e for e in errs), errs
