#!/usr/bin/env python3
"""Capability doc-audit — consume capabilities.json defects[], resolve the fixable set, ledger the rest.

Reads the generated catalog (``scripts/generate_capability_index.py`` output) and acts on each record's
``defects[]``:

  MECHANICAL (auto-fixable, but DRY-RUN BY DEFAULT — pass ``--apply`` to execute):
    - ``dead_doc``     → unlink the orphan doc (``doc_link``) — .md only; a tool file (.py/.sh) is NEVER
                         unlinked (operator authority + shared-tree safety).
    - ``undocumented`` → write a stub under ``docs/reference/capabilities/`` + point ``doc_link`` at it.
    - ``doc_drift``    → FLAG in the report only (never auto-rewrite prose — that's a human/`doc_reconcile`
                         call, not a mechanical one).

  OPERATOR (never auto-actioned — surfaced in ``docs/development/capability-defects.md``):
    - ``broken`` / ``retired`` / ``incomplete`` → a recommended action (fix / retire-decision / revise).

Dry-run is the default (CLAUDE.md HARD STOP: "destructive script w/o dry-run"). The report is written on
every run and lists the FULL plan of what ``--apply`` would do. A tool is never removed.

Usage: python scripts/audit_capability_docs.py [capabilities.json] [--apply]

# AFTER-EDIT: INDEX.md
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
_REPORT_REL = "docs/development/capability-defects.md"
_STUB_DIR_REL = "docs/reference/capabilities"
_OPERATOR_DEFECTS = ("broken", "retired", "incomplete")
_RECOMMEND = {
    "broken": "FIX — the liveness probe failed; repair the tool or mark it retired.",
    "retired": "RETIRE-DECISION — carries a deprecation marker; confirm removal or un-deprecate.",
    "incomplete": "REVISE — missing its README/doc; add one so agents can use it.",
}


def _slug(name: object) -> str:
    return re.sub(r"[^a-z0-9]+", "-", str(name).lower()).strip("-") or "unnamed"


def _stub_text(cap: dict) -> str:
    return (
        f"# {cap.get('name', 'unnamed')}\n\n"
        f"> STUB (auto-generated by audit_capability_docs.py) — replace with real documentation.\n\n"
        f"- **Kind:** {cap.get('kind', '')}\n"
        f"- **Invoke:** `{cap.get('invoke', '')}`\n"
        f"- **Summary:** {cap.get('summary', '') or '_(none captured)_'}\n"
    )


def _safe_to_unlink(doc: str, root: Path) -> tuple[bool, str]:
    """(safe, reason) — a doc_link may be unlinked ONLY if it is a `.md` AND its resolved path stays
    strictly inside ``root``. Guards against unlinking a tool (.py/.sh) and against absolute-path /
    `../`-traversal / symlink escapes that would delete files outside the repo (untrusted catalog input)."""
    if not str(doc).endswith(".md"):
        return False, f"doc_link {doc!r} is not a .md (looks like a tool)"
    try:
        target = (root / doc).resolve()
        target.relative_to(root.resolve())  # raises ValueError if outside root
    except (ValueError, OSError):
        return False, f"resolved path {doc!r} escapes the repo root"
    return True, ""


def run(catalog_path: Path, apply: bool = False, root: Path = REPO) -> dict:
    """Audit the catalog's defects. Returns ``{fixed: [...], operator_action: [...]}``.

    ``apply=False`` (default) is a dry-run: it PLANS the mechanical fixes (and says so) but changes no
    file except the report. ``apply=True`` executes the unlinks/stubs. A tool file is never touched, and
    no file outside the repo root is ever unlinked.
    """
    try:
        payload = json.loads(Path(catalog_path).read_text())
        catalog = payload.get("capabilities", []) if isinstance(payload, dict) else []
    except (json.JSONDecodeError, OSError):
        catalog = []  # malformed/missing catalog → empty audit, but the report is STILL written
    fixed: list[str] = []
    operator_action: list[dict] = []
    drift: list[dict] = []
    tag = "" if apply else "[dry-run] would "

    for cap in catalog:
        if not isinstance(cap, dict):
            continue
        name = str(cap.get("name", "unnamed"))  # coerce — a non-string name must not crash _slug (untrusted)
        kind = cap.get("kind", "")
        defects = cap.get("defects", [])
        if not isinstance(defects, list):  # a stray string would make `"dead_doc" in defects` a substring test
            defects = []
        doc = cap.get("doc_link")

        if "dead_doc" in defects and doc:
            # SAFETY (two independent guards — a dead_doc's doc_link is UNTRUSTED catalog input):
            #  1. extension — only ever unlink a markdown doc, never a .py/.sh tool (operator authority);
            #  2. CONTAINMENT — the resolved target MUST stay inside the repo, so an absolute path
            #     (`/etc/x.md`), a `../` traversal, or a symlink escaping `root` can NEVER delete another
            #     project's / another AI's files. (CLAUDE.md: destroying another AI's work is critical.)
            safe, why = _safe_to_unlink(doc, root)
            if safe:
                if apply:
                    (root / doc).unlink(missing_ok=True)
                fixed.append(f"{tag}delete dead doc: {doc}")
            else:
                operator_action.append({
                    "name": name, "kind": kind, "defect": "dead_doc",
                    "action": f"SKIPPED unlink of {doc!r} — {why}; resolve by hand.",
                })

        if "undocumented" in defects:
            stub_rel = f"{_STUB_DIR_REL}/{_slug(name)}.md"
            if apply:
                stub = root / stub_rel
                stub.parent.mkdir(parents=True, exist_ok=True)
                stub.write_text(_stub_text(cap))
            fixed.append(f"{tag}write stub: {stub_rel}")

        if "doc_drift" in defects:
            drift.append(cap)

        for d in _OPERATOR_DEFECTS:
            if d in defects:
                operator_action.append({"name": name, "kind": kind, "defect": d, "action": _RECOMMEND[d]})

    _write_report(root, fixed, operator_action, drift, apply, catalog_path)
    return {"fixed": fixed, "operator_action": operator_action}


def _write_report(
    root: Path, fixed: list[str], operator_action: list[dict], drift: list[dict],
    apply: bool, catalog_path: Path,
) -> None:
    report = root / _REPORT_REL
    report.parent.mkdir(parents=True, exist_ok=True)
    mode = "APPLIED" if apply else "DRY-RUN (no changes made except this report)"
    lines = [
        "# Capability defect ledger",
        "",
        f"> Generated by `scripts/audit_capability_docs.py` from `{Path(catalog_path).name}` — mode: **{mode}**.",
        "> Mechanical fixes are dry-run by default; re-run with `--apply` to execute. A tool file is never removed.",
        "",
        "## Mechanical fixes",
        "",
    ]
    lines += [f"- {f}" for f in fixed] or ["- _(none)_"]
    lines += ["", "## Doc drift (flagged — NOT auto-rewritten)", ""]
    lines += [
        f"- `{c.get('name', 'unnamed')}` ({c.get('kind', '')}) → {c.get('doc_link')}" for c in drift
    ] or ["- _(none)_"]
    lines += ["", "## Operator action required", "", "| Capability | Kind | Defect | Recommended action |",
              "|---|---|---|---|"]
    lines += [
        f"| `{o['name']}` | {o['kind']} | {o['defect']} | {o['action']} |" for o in operator_action
    ] or ["| _(none)_ | | | |"]
    lines.append("")
    report.write_text("\n".join(lines))


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    apply = "--apply" in args
    args = [a for a in args if a != "--apply"]
    catalog = Path(args[0]) if args else (REPO / "capabilities.json")
    if not catalog.exists():
        print(f"ERROR: catalog not found: {catalog}", file=sys.stderr)
        return 1
    report = run(catalog, apply=apply)
    print(
        f"capability doc-audit ({'APPLIED' if apply else 'dry-run'}): "
        f"{len(report['fixed'])} mechanical, {len(report['operator_action'])} operator-action → {_REPORT_REL}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
