#!/usr/bin/env python3
"""Probe-vs-doc audit for the VPS fleet.

Runs a fixed set of presence-probes against vps1/vps2/vps3 via SSH and emits:

1. YAML report → data/infra-probe-YYYYMMDD-HHMM.yaml  (machine-readable, commit)
2. Markdown table → stdout  (paste-ready for vps-status.md § Verification log)

Designed to close the gap exposed on 2026-05-31 evening: three doc-audit passes
claimed UFW was active on vps2/vps3 because each grepped for failure symptoms.
None ran `dpkg -l ufw`. Symptom-grep cannot find an absence — this script does
presence-probing instead.

Lesson 66 in docs/LESSONS_LEARNT.md.

Usage:
    scripts/audit_infra_vs_docs.py                  # run probes, write report
    scripts/audit_infra_vs_docs.py --check          # lint: every infra doc must
                                                    # have a 'Last probe report:' link
    scripts/audit_infra_vs_docs.py --hosts vps,vps2 # probe a subset
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
INFRA_DOCS = [
    REPO_ROOT / "docs/infrastructure/vps-complete-inventory.md",
    REPO_ROOT / "docs/infrastructure/vps-status.md",
    REPO_ROOT / "docs/infrastructure/vps-urls.md",
    REPO_ROOT / "docs/infrastructure/vps-bootstrap-plan.md",
]

# Probes are plain strings (NOT f-strings) — the Docker `{{.Names}}` format must
# pass through unmodified.
PROBES: dict[str, str] = {
    "container_count": "sudo docker ps --format '{{.Names}}' | wc -l",
    "ufw_installed": "dpkg -l ufw 2>/dev/null | awk '/^ii/ {print $2}' || true",
    "ufw_active": "sudo systemctl is-active ufw 2>/dev/null || echo not-installed",
    "ufw_rule_count_v4": "sudo ufw status 2>/dev/null | grep -cE '^[0-9]+/(tcp|udp) +ALLOW' || echo 0",
    "fail2ban_active": "sudo systemctl is-active fail2ban 2>/dev/null || echo not-installed",
    "fail2ban_total_ban": "sudo fail2ban-client status sshd 2>/dev/null | awk '/Total banned/ {print $NF}' || echo n/a",
    "listening_public": "sudo ss -tnlp 2>/dev/null | awk 'NR>1 {print $4}' | grep -E '^(0\\.0\\.0\\.0|\\*):' | sort -u | tr '\\n' ',' | sed 's/,$//'",
    "listening_mesh": "sudo ss -tnlp 2>/dev/null | awk 'NR>1 {print $4}' | grep '^10\\.99\\.' | sort -u | tr '\\n' ',' | sed 's/,$//'",
    "docker_user_rules": "sudo iptables -L DOCKER-USER -n 2>/dev/null | grep -cE 'DROP|ACCEPT' || echo 0",
    "iptables_backend": "sudo update-alternatives --display iptables 2>&1 | grep -oE 'iptables-(nft|legacy)' | head -1 || echo unknown",
    "wg_peers_alive": "sudo wg show wg0 latest-handshakes 2>/dev/null | awk '{age=systime()-$2; if (age<300) c++} END {print c+0}' || echo 0",
    "kernel": "uname -r",
    "uptime_s": "cut -d. -f1 /proc/uptime",
    "disk_root_pct": "df / 2>/dev/null | awk 'NR==2 {gsub(\"%\",\"\"); print $5}'",
    "ram_used_mb": "free -m 2>/dev/null | awk '/^Mem:/ {print $3}'",
    "ram_total_mb": "free -m 2>/dev/null | awk '/^Mem:/ {print $2}'",
    "docker_network_fabrik": "sudo docker network inspect fabrik --format '{{.Name}}' 2>/dev/null || echo missing",
}

HOSTS_DEFAULT = ["vps", "vps2", "vps3"]


def _run_ssh(host: str, cmd: str, timeout: int = 15) -> tuple[int, str, str]:
    """Run a command on a host via SSH alias. Returns (rc, stdout, stderr)."""
    try:
        r = subprocess.run(
            ["ssh", "-o", "ConnectTimeout=8", "-o", "BatchMode=yes", host, cmd],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return r.returncode, r.stdout.strip(), r.stderr.strip()
    except subprocess.TimeoutExpired:
        return 124, "", f"timeout after {timeout}s"
    except Exception as e:  # noqa: BLE001
        return 1, "", repr(e)


def probe_host(host: str) -> dict[str, str]:
    """Run all PROBES against a host. Returns name -> value string."""
    results: dict[str, str] = {}
    for name, cmd in PROBES.items():
        rc, out, err = _run_ssh(host, cmd)
        if rc == 0:
            results[name] = out or "(empty)"
        else:
            results[name] = f"ERR rc={rc}: {err or out}"[:200]
    return results


def emit_yaml(report: dict, path: Path) -> None:
    """Write the report as YAML without depending on PyYAML."""
    lines = [
        f"# Infrastructure probe report — {report['timestamp']}",
        f"# Generated by scripts/audit_infra_vs_docs.py",
        f"timestamp: {report['timestamp']}",
        f"hosts:",
    ]
    for host, data in report["hosts"].items():
        lines.append(f"  {host}:")
        for k, v in data.items():
            # Quote values containing special chars
            if any(c in str(v) for c in [":", "#", "\n", "'"]):
                vs = json.dumps(str(v))  # JSON quoting is YAML-safe
            else:
                vs = str(v)
            lines.append(f"    {k}: {vs}")
    path.write_text("\n".join(lines) + "\n")


def emit_markdown(report: dict) -> str:
    """Render the report as a Markdown table for direct paste into vps-status.md."""
    hosts = list(report["hosts"].keys())
    probes = list(PROBES.keys())
    lines = [
        f"### Probe report — {report['timestamp']}",
        "",
        "| Probe | " + " | ".join(hosts) + " |",
        "| :--- | " + " | ".join([":---"] * len(hosts)) + " |",
    ]
    for p in probes:
        row = [p]
        for h in hosts:
            v = str(report["hosts"][h].get(p, "?"))
            # Truncate cells that are very long (e.g., big lists of listening sockets)
            if len(v) > 60:
                v = v[:57] + "..."
            row.append(v)
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def check_doc_headers() -> int:
    """Lint: every infra doc must have a `Last probe report:` line pointing
    to a real file under data/. Returns count of warnings."""
    pattern = re.compile(
        r"\*\*Last probe report:\*\*\s*\[`?(data/infra-probe-[^\)`]+\.yaml)`?\]"
    )
    warnings = 0
    for doc in INFRA_DOCS:
        if not doc.exists():
            print(f"WARN: doc not found: {doc}")
            warnings += 1
            continue
        content = doc.read_text()
        m = pattern.search(content)
        if not m:
            print(f"WARN: {doc.relative_to(REPO_ROOT)} missing 'Last probe report:' header")
            warnings += 1
            continue
        cited = REPO_ROOT / m.group(1)
        if not cited.exists():
            print(
                f"WARN: {doc.relative_to(REPO_ROOT)} cites {cited.relative_to(REPO_ROOT)} but file does not exist"
            )
            warnings += 1
    return warnings


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hosts", default=",".join(HOSTS_DEFAULT), help="Comma-separated list of SSH host aliases")
    ap.add_argument("--check", action="store_true", help="Lint mode: verify infra docs cite a probe report")
    ap.add_argument(
        "--data-dir",
        default=str(DATA_DIR),
        help=f"Output directory for YAML report (default: {DATA_DIR})",
    )
    args = ap.parse_args()

    if args.check:
        n = check_doc_headers()
        if n:
            print(f"\n{n} doc header warning(s).")
            return 1
        print("OK: every infra doc cites a probe report file that exists.")
        return 0

    hosts = [h.strip() for h in args.hosts.split(",") if h.strip()]
    timestamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H-%MZ")

    print(f"# Probing {len(hosts)} host(s): {hosts}", file=sys.stderr)
    report = {"timestamp": timestamp, "hosts": {}}
    for h in hosts:
        print(f"# probing {h}...", file=sys.stderr)
        report["hosts"][h] = probe_host(h)

    data_dir = Path(args.data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    yaml_path = data_dir / f"infra-probe-{timestamp}.yaml"
    emit_yaml(report, yaml_path)
    print(f"# wrote {yaml_path.relative_to(REPO_ROOT)}", file=sys.stderr)
    print()
    print(emit_markdown(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
