#!/usr/bin/env bash
# AFTER-EDIT: docs/workstation/hooks-index.md, tests/enforcement/test_governance_sync_postcommit.py
#
# Installs the hub's POST-COMMIT hook as a PLAIN git hook that runs scripts/governance_sync_postcommit.sh
# directly — never pre-commit's post-commit stage. pre-commit stashes every unstaged change in the tree
# around each `run` and restores with a tree-wide `git checkout -- .` (pre_commit/staged_files_only.py),
# so for the ~60 s the fleet sync took, any edit a sibling session made to any tracked file was silently
# reverted (mail 01M3492KY09K6DP47Z21XVM2SH, D-369). Same shape and reason as the commit-msg shim
# (scripts/check_commit_trailers.py --install). Idempotent; replaces pre-commit's generated post-commit
# shim; refuses any other foreign hook. Re-run by scripts/wsl_startup_hook.sh on every interactive shell.
set -euo pipefail

ROOT=/opt/fabrik
# Test seam, honoured ONLY under the explicit sentinel (the same pattern as the wrapper's SYNC_CMD).
if [ "${GOVERNANCE_SYNC_TEST:-}" = "1" ] && [ -n "${GOVERNANCE_SYNC_ROOT:-}" ]; then
  ROOT="$GOVERNANCE_SYNC_ROOT"
fi

# git reads hooks from core.hooksPath when it is set, so a hook written to .git/hooks would never fire —
# refuse loudly rather than install something inert (pre-commit's own installer refuses the same way).
if hp="$(git -C "$ROOT" config --get core.hooksPath)"; then
  echo "install_post_commit_hook: core.hooksPath is set ($hp) — git would never run .git/hooks/post-commit; unset it first" >&2
  exit 1
fi

# --git-common-dir resolves to the SHARED git dir from a worktree too, so every checkout gets this hook.
common="$(cd "$ROOT" && cd "$(git rev-parse --git-common-dir)" && pwd)"
target="$common/hooks/post-commit"
MARK="Installed by scripts/install_post_commit_hook.sh"

if [ -e "$target" ] && ! grep -qF "$MARK" "$target" && ! grep -qF "File generated by pre-commit" "$target"; then
  echo "install_post_commit_hook: refusing to replace a foreign $target — move it aside first" >&2
  exit 1
fi

mkdir -p "$common/hooks"
tmp="$(mktemp "$common/hooks/.post-commit.XXXXXX")"
trap 'rm -f "$tmp"' EXIT   # a failed write never leaves a stray temp file in the shared hooks dir
cat > "$tmp" <<SHIM
#!/bin/sh
# $MARK — a plain git hook, deliberately NOT pre-commit's post-commit stage (see that script's header).
# git ignores a post-commit hook's exit status, so this shim can never block a commit.
exec bash "$ROOT/scripts/governance_sync_postcommit.sh"
SHIM
chmod 755 "$tmp"
mv -f "$tmp" "$target"   # atomic: a commit running right now reads either the old hook or the new one

# `pre-commit install -t post-commit` keeps a hook it did not write as post-commit.legacy (migration mode).
# Once the plain hook is back, a legacy copy of it is dead weight nobody runs — remove only our own.
legacy="$common/hooks/post-commit.legacy"
if [ -f "$legacy" ] && grep -qF "$MARK" "$legacy"; then rm -f "$legacy"; fi
