#!/usr/bin/env bash
# AFTER-EDIT: docs/workstation/hooks-index.md, tests/enforcement/test_governance_sync_postcommit.py, tests/test_merge_sync.py
#
# Installs the hub's POST-COMMIT and POST-MERGE hooks as PLAIN git hooks that run
# scripts/governance_sync_postcommit.sh directly — never pre-commit's post-commit stage. pre-commit
# stashes every unstaged change in the tree around each `run` and restores with a tree-wide
# `git checkout -- .` (pre_commit/staged_files_only.py), so for the ~60 s the fleet sync took, any edit a sibling session made to any tracked file was silently
# reverted (mail 01M3492KY09K6DP47Z21XVM2SH, D-369). Same shape and reason as the commit-msg shim
# (scripts/check_commit_trailers.py --install). Idempotent; replaces pre-commit's generated
# post-commit/post-merge shims; refuses any other foreign hook. Re-run by scripts/wsl_startup_hook.sh
# on every interactive shell.
set -euo pipefail

ROOT=/opt/fabrik
# Test seam, honoured ONLY under the explicit sentinel (the same pattern as the wrapper's SYNC_CMD).
if [ "${GOVERNANCE_SYNC_TEST:-}" = "1" ] && [ -n "${GOVERNANCE_SYNC_ROOT:-}" ]; then
  ROOT="$GOVERNANCE_SYNC_ROOT"
fi

# git reads hooks from core.hooksPath when it is set, so a hook written to .git/hooks would never fire —
# refuse loudly rather than install something inert (pre-commit's own installer refuses the same way).
if hp="$(git -C "$ROOT" config --get core.hooksPath)"; then
  echo "install_post_commit_hook: core.hooksPath is set ($hp) — git would never run .git/hooks/post-commit or post-merge; unset it first" >&2
  exit 1
fi

# --git-common-dir resolves to the SHARED git dir from a worktree too, so every checkout gets these hooks.
common="$(cd "$ROOT" && cd "$(git rev-parse --git-common-dir)" && pwd)"
MARK="Installed by scripts/install_post_commit_hook.sh"
# Two hooks, one script: post-commit syncs HEAD's own paths; post-merge syncs what a merge brought in,
# because `git merge` (fast-forward or --no-ff) fires no post-commit hook and a worktree commit syncs
# nothing, so a merge is the only way a worktree's governance change reaches the fleet (spec
# 2026-09-29-hub-worktree-cutover-design § D3 (b)).
HOOKS="post-commit post-merge"

# Refuse BEFORE writing anything, so a foreign hook on either name never leaves a half-install.
for name in $HOOKS; do
  target="$common/hooks/$name"
  if [ -e "$target" ] && ! grep -qF "$MARK" "$target" && ! grep -qF "File generated by pre-commit" "$target"; then
    echo "install_post_commit_hook: refusing to replace a foreign $target — move it aside first" >&2
    exit 1
  fi
done

mkdir -p "$common/hooks"
tmp=""
trap 'rm -f "$tmp"' EXIT   # a failed write never leaves a stray temp file in the shared hooks dir
for name in $HOOKS; do
  target="$common/hooks/$name"
  arg=""
  [ "$name" = post-merge ] && arg=" post-merge"
  tmp="$(mktemp "$common/hooks/.$name.XXXXXX")"
  cat > "$tmp" <<SHIM
#!/bin/sh
# $MARK — a plain git hook, deliberately NOT pre-commit's $name stage (see that script's header).
# git ignores a $name hook's exit status, so this shim can never block a commit or a merge.
exec bash "$ROOT/scripts/governance_sync_postcommit.sh"$arg
SHIM
  chmod 755 "$tmp"
  mv -f "$tmp" "$target"   # atomic: a commit running right now reads either the old hook or the new one
  tmp=""

  # `pre-commit install -t <name>` keeps a hook it did not write as <name>.legacy (migration mode).
  # Once the plain hook is back, a legacy copy of it is dead weight nobody runs — remove only our own.
  legacy="$common/hooks/$name.legacy"
  if [ -f "$legacy" ] && grep -qF "$MARK" "$legacy"; then rm -f "$legacy"; fi
done
