#!/usr/bin/env python3
# AFTER-EDIT: tests/test_doc_script_links.py | docs/reference/doc-script-coupling.md | scripts/enforcement/check_script_headers.py
"""render_doc_script_links — the doc side of the doc↔script coupling.

Operator ask (2026-09-06): *"in each doc, indicate the related scripts, in each script indicate
the related document to be kept always uptodate."*

The SCRIPT side already existed: every `scripts/**/*.py` carries a `# AFTER-EDIT:` header naming
what must be updated when it changes, and `check_script_headers.py` warns when a coupled file is
not staged alongside it. The DOC side did not exist at all — the 24 `## Related` sections in
`docs/` point at sibling *docs*, never at the scripts that implement them.

⚠️ THE ONE THING THIS MUST NOT BE IS A SECOND HAND-MAINTAINED LIST. Two independently authored
link lists are two things to drift, and this repo had proven that hours before this script was
written: `docs/workstation/claude-account-rotation.md` restated `caps.json`'s cap values in prose
and BOTH of the numbers it named had gone stale — one of them the same day, in the commit that
changed the value. So the header stays the single declaration, and the doc-side block is
DERIVED from it: generated between markers, never authored, and `--check` fails when it is stale.
The same shape `_doc_registry.py` uses for project docs ("every surface DERIVES from PROJECT_DOCS
here, so they can never drift again").

WHAT IT WRITES — into each `.md` a header names, between HTML comment markers so hand-written
prose is never touched:

    <!-- BEGIN related-scripts … -->
    ## Related scripts
    - `scripts/sysadmin/claude_rotate.py`
    <!-- END related-scripts -->

Tokens that are NOT a single page — a directory (`docs/orchestrator/`), a glob (`docs/**`) — are
REPORTED, never rendered: they are real couplings that cannot be inverted onto one page, and
dropping them silently would hide them from the doc side. A named `.md` that does not exist is
reported as MISSING and never created — creating it would make a typo look correct forever.

  python3 scripts/render_doc_script_links.py            # render
  python3 scripts/render_doc_script_links.py --check    # verify, mutate nothing (exit 1 if stale)
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_CSH = _HERE / "enforcement" / "check_script_headers.py"

# Reuse the header parser rather than writing a second one. Its `_header_of` reads COMMENT tokens
# (never a docstring example), and `_coupled_tokens` already survives the corpus's real shapes —
# both `,` and `|` separators, trailing full stops, prose words, `none`/`n/a` sentinels. Each of
# those is a defect that was found in production and fixed there; a fresh parser here would
# re-earn every one of them.
_spec = importlib.util.spec_from_file_location("_csh", _CSH)
_csh = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_csh)

BEGIN = "<!-- BEGIN related-scripts: generated by scripts/render_doc_script_links.py — do not hand-edit -->"
END = "<!-- END related-scripts -->"

SKIP_DIRS = (".archive/", ".scratch/", "archived/", "__pycache__/")

# ⚠️ NOT EVERY FILE A HEADER NAMES IS A PAGE THIS MAY WRITE INTO. `# AFTER-EDIT:` answers "what
# must I update when this script changes", and its answer is often a Doc Sync Matrix TARGET
# (CHANGELOG, INDEX, PORTS) or a governance/corpus surface — not a subsystem doc that wants a
# list of its scripts. Rendering into those would be actively harmful, in four distinct ways:
#
#   commands/_sources/**  the command corpus, RENDERED box-wide by assemble_commands.py — a block
#                         here ships into every installed command and skill on the box
#   templates/**          fleet-synced into ~46 project repos by the post-commit governance sync
#   plans/ + specs/       frozen artifacts whose CONVERGED status is an md5 of their content, and
#                         whose shape `check_convergence.py` reads — appending voids both
#   ledgers + matrix      CHANGELOG/INDEX/PORTS/DECISIONS/LESSONS are named by dozens of scripts
#                         apiece; the "related scripts" of CHANGELOG.md is every script there is,
#                         which is a list that informs nobody
#
# So the renderer writes ONLY to documentation pages. Everything else stays a one-way coupling —
# still enforced from the script side by check_script_headers.py, just not mirrored onto the page.
RENDER_ROOTS = ("docs/",)
NEVER_RENDER = (
    "docs/development/plans/",
    "docs/development/reviews/",
    "docs/development/epics/",
    "docs/development/certifications/",
    "docs/superpowers/specs/",
    "docs/superpowers/plans/",
    "docs/archive/",
)
NEVER_RENDER_FILES = (
    "docs/DECISIONS.md",
    "docs/LESSONS_LEARNT.md",
    "docs/CHANGELOG.md",
)


def renderable(rel: str) -> bool:
    """A page the doc-side block may be written into. Everything else is reported, not written."""
    if rel in NEVER_RENDER_FILES or any(rel.startswith(d) for d in NEVER_RENDER):
        return False
    return rel.endswith(".md") and any(rel.startswith(r) for r in RENDER_ROOTS)


_GATE_MODE = False  # set by run(): --check / --coverage see tracked + STAGED files only


def _scripts(repo: Path) -> list[Path]:
    """Tracked, live scripts. `git ls-files` is the denominator that matters: a plain rglob over
    `scripts/` returns 3,476 files here, of which 3,235 are untracked benchmark/venv artifacts
    that no one edits and no doc documents. Falls back to rglob where git cannot answer (a
    tmp_path fixture, a tarball) so the renderer is testable without a repo."""
    try:
        # TRACKED **plus** untracked-not-ignored. `ls-files` alone cannot see a script that has
        # not been committed yet — so a brand-new script's coupling would be invisible to the very
        # gate that runs BEFORE its first commit, and the doc side would land one commit late.
        # Found by using this tool on itself: it rendered no block into its own reference doc.
        # GATE modes (--check, --coverage) see tracked + STAGED files: what is about to be
        # committed. A plain render also sees untracked-not-ignored, so a brand-new script's
        # coupling is visible before its first commit. On a three-session tree a SIBLING's
        # untracked scratch script under scripts/ used to enter the gate's graph and could red the
        # BLOCKING --check or raise the ratchet for everyone (review 2026-09-06, E1/E2).
        # `--cached` IS the index (tracked + staged) — listing it beside the default tracked set
        # enumerated every tracked script TWICE in gate mode: notes printed twice and the
        # coverage ratchet's denominator doubled (review 2026-09-06 pass 2).
        extras = [["--cached"]] if _GATE_MODE else [[], ["--others", "--exclude-standard"]]
        names = []
        for extra in extras:
            out = subprocess.run(
                ["git", "-C", str(repo), "ls-files", "-z", *extra, "scripts"],
                capture_output=True,
                timeout=30,
                check=True,
            ).stdout.decode("utf-8", "replace")
            names += [n for n in out.split("\0") if n.endswith(".py")]
    except (subprocess.SubprocessError, OSError):
        names = [p.relative_to(repo).as_posix() for p in (repo / "scripts").rglob("*.py")]
    out = []
    for n in names:
        if any(("scripts/" + s) in ("scripts/" + n) for s in SKIP_DIRS):
            continue
        # A SYMLINK's couplings belong to its TARGET's world, not to this repo's. The hub symlinks
        # `scripts/verify_prod_parity.py` at a scaffold template whose header names `docs/DEPLOYMENT.md`
        # and `docs/OPERATIONS.md` — correct in every PROJECT the scaffolder seeds it into, absent
        # here. Reported as MISSING it is a permanent false finding, and a note that is always wrong
        # is how a reader learns to skip the notes (FIX DIRECTIVE 5: wallpaper is how enforcement dies).
        if (repo / n).is_symlink():
            continue
        out.append(repo / n)
    return sorted(out)


def _declared(script: Path, repo: Path) -> list[str]:
    """The `# AFTER-EDIT:` tokens of one script, as repo-relative strings."""
    try:
        head = "\n".join(
            script.read_text(encoding="utf-8", errors="replace").splitlines()[
                : _csh.HEADER_SCAN_LINES
            ]
        )
    except OSError:
        return []
    listed = _csh._header_of(head)
    if listed is None:
        return []
    return _csh._coupled_tokens(listed, script.relative_to(repo))


def graph(repo: Path) -> tuple[dict[Path, list[str]], list[str]]:
    """Invert the headers: doc -> the scripts that declare it. Returns (graph, notes)."""
    docs: dict[Path, set[str]] = {}
    notes: list[str] = []
    for script in _scripts(repo):
        rel = script.relative_to(repo).as_posix()
        for token in _declared(script, repo):
            if token.endswith("/") or any(ch in token for ch in "*?[") or (repo / token).is_dir():
                # a directory/glob OUTSIDE docs/ is a code-side coupling (a fixtures dir, a test
                # tree) — the doc side's business only when it claims to be a doc target
                # (review 2026-09-06 pass 2: a fixtures dir red the BLOCKING check for every session)
                if not (token.startswith("docs/") or token.endswith(".md")):
                    continue
                notes.append(
                    f"  NOT-A-PAGE  {rel} declares '{token}' — a directory or glob cannot be rendered onto one page"
                )
                continue
            if not token.endswith(".md"):
                continue  # a code coupling (tests, configs) — real, but not the doc side's business
            target = repo / token
            if not target.is_file():
                notes.append(
                    f"  MISSING     {rel} declares '{token}' — no such file (typo, or the doc was moved)"
                )
                continue
            if not renderable(token):
                continue  # a real coupling, enforced script-side; just not mirrored onto that page
            docs.setdefault(target, set()).add(rel)
    return {d: sorted(s) for d, s in sorted(docs.items())}, notes


def block_for(scripts: list[str]) -> str:
    lines = [
        BEGIN,
        "## Related scripts",
        "",
        "Scripts that declare this document in their `# AFTER-EDIT:` header — editing one of them",
        "means updating this page in the same change. This list is generated from those headers",
        "(`python3 scripts/render_doc_script_links.py`); add the doc to a script's header, not here.",
        "",
    ]
    lines += [f"- `{s}`" for s in scripts]
    lines.append(END)
    return "\n".join(lines)


def marker_state(text: str) -> str:
    """ "ok" (a well-formed pair, or none at all) or "malformed".

    A page whose END marker was hand-deleted — or lost to a merge resolution — has a BEGIN with
    no partner. Appending a fresh block there leaves TWO BEGINs and one END, and every later run
    appends another: the page grows a new copy per render and the reader cannot tell which list
    is current. Reported and skipped, never silently repaired, because a half-block means someone
    edited a generated region by hand and that is worth seeing."""
    b, e = text.count(BEGIN), text.count(END)
    if b == e == 0:
        return "ok"
    if b == e == 1 and text.find(END) > text.find(BEGIN):
        return "ok"
    return "malformed"


def apply_block(text: str, scripts: list[str]) -> str:
    """Replace the marked region, or append one. Everything outside the markers is untouched —
    docs carry hand-written `## Related` sections listing sibling docs, and trading a missing
    link for a destroyed one is not a fix."""
    new = block_for(scripts) if scripts else ""
    start, end = text.find(BEGIN), text.find(END)
    if start != -1 and end != -1 and end > start:
        head, tail = text[:start], text[end + len(END) :]
        if not new:  # the last declaring script dropped this doc — the block goes with it
            return (head.rstrip("\n") + "\n" + tail.lstrip("\n")).rstrip("\n") + "\n"
        return head + new + tail
    if not new:
        return text
    return text.rstrip("\n") + "\n\n" + new + "\n"


BASELINE = ".fabrik/doc-script-baseline.json"


def uncoupled(repo: Path) -> list[str]:
    """Scripts carrying NO `# AFTER-EDIT:` header at all — the backfill backlog.

    A header is one line and `none` is a valid answer, so this is not a judgement about whether a
    script HAS a doc; it is about whether anyone ever said. `check_script_headers` is touch-on-change
    by design ("a script gains its header the next time it is edited"), which grandfathers every
    script nobody happens to touch — 427 of them across 36 of 44 repos at the last audit. Operator
    ruling 2026-09-06: the coupling is RETROACTIVE, so the backlog is worked DOWN, not waited out."""
    out = []
    for script in _scripts(repo):
        head = "\n".join(
            script.read_text(encoding="utf-8", errors="replace").splitlines()[
                : _csh.HEADER_SCAN_LINES
            ]
        )
        if _csh._header_of(head) is None:
            out.append(script.relative_to(repo).as_posix())
    return sorted(out)


def ratchet(repo: Path, write: bool) -> tuple[int, str]:
    """Count-may-only-go-DOWN — the contract `check_lint_ratchet.py` already proves in this repo:
    the first run SEEDS at today's count and passes (nothing is bricked), a run that RAISES it
    fails, a run that lowers it tightens the floor, and 0 locks permanently."""
    backlog = uncoupled(repo)
    now, path = len(backlog), repo / BASELINE
    total = len(_scripts(repo))
    try:
        prior = json.loads(path.read_text(encoding="utf-8")).get("headerless")
    except (OSError, ValueError, AttributeError):
        prior = None
    if prior is None:
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps({"headerless": now}, indent=2) + "\n", encoding="utf-8")
        return 0, f"doc-script coverage: SEEDED baseline at {now} headerless of {total} script(s)"
    if now > prior:
        listing = "\n  ".join(backlog[:10])
        return 1, (
            f"doc-script coverage ROSE {prior} -> {now} headerless of {total} script(s). The "
            f"coupling is RETROACTIVE: the count may only go DOWN. Add "
            f"`# AFTER-EDIT: <doc | none>` to the first ~25 lines of:\n  {listing}"
        )
    if now < prior and write:
        path.write_text(json.dumps({"headerless": now}, indent=2) + "\n", encoding="utf-8")
    tail = " — LOCKED at zero" if now == 0 else f"; {now} still owed — backfill them"
    return 0, f"doc-script coverage: {total - now} of {total} script(s) headered{tail}"


def run(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=".", help="repo root (default: cwd)")
    ap.add_argument(
        "--check", action="store_true", help="verify only; mutate nothing, exit 1 if stale"
    )
    ap.add_argument(
        "--coverage",
        action="store_true",
        help="report the headerless-script backlog and ratchet it (count may only go DOWN)",
    )
    args = ap.parse_args(argv)
    global _GATE_MODE
    _GATE_MODE = bool(args.check or args.coverage)
    repo = Path(args.repo).resolve()

    if args.coverage:
        code, msg = ratchet(repo, write=not args.check)
        print(msg)
        return code

    docs, notes = graph(repo)
    stale, written = [], 0
    for doc, scripts in docs.items():
        current = doc.read_text(encoding="utf-8")
        if marker_state(current) == "malformed":
            notes.append(
                f"  MALFORMED   {doc.relative_to(repo).as_posix()} — an unpaired related-scripts "
                f"marker (hand-edited or a lost merge hunk); skipped, fix the markers by hand"
            )
            continue
        desired = apply_block(current, scripts)
        if desired == current:
            continue
        if args.check:
            stale.append(doc.relative_to(repo).as_posix())
        else:
            doc.write_text(desired, encoding="utf-8")
            written += 1

    for note in notes:
        print(note)
    if args.check:
        if stale:
            print(f"\ndoc↔script links STALE in {len(stale)} of {len(docs)} coupled doc(s):")
            for s in stale:
                print(f"  {s}")
            print("\nfix: python3 scripts/render_doc_script_links.py")
            return 1
        print(f"doc↔script links: {len(docs)} coupled doc(s) current")
        return 0
    print(f"doc↔script links: {written} doc(s) updated, {len(docs)} coupled doc(s) total")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
