#!/usr/bin/env python3
# AFTER-EDIT: tests/test_review_receipt.py, commands/_sources/fabrik-review.md, commands/_sources/fabrik-execute-plan.md, scripts/enforcement/check_review_coverage.py, scripts/fabrik_synced_manifest.py | none
"""Review-artifact skeleton — `--init` emits the grammar `check_review_coverage.py` grades.

Why a generator: the artifact's mechanical half (the pasted rubric header, the `Surface:` hash
line, the standing recurrence rows, the ledger and phase-verdict shapes) was hand-written per
review and mis-shaped often enough to fail its own gate (two grammar-gate failures and seven
hand-built receipts in one plan, 2026-09-06). The generator writes that half; the reviewer
writes the verdicts. It never pre-fills a verdict, a ledger row or a gate result: the file is
born `Status: IN-PROGRESS` (exempt from the gate until the reviewer flips it), and every slot
that would satisfy the gate if left alone is spelled `UNCHECKED` — a lazy flip fails loudly.

    python scripts/review_receipt.py --init --changed <paths…> [--out <file> | --scope <slug>]
                                     [--title <h1>] [--plan <path>] [--range A..B]
                                     [--project-root <repo>]

The `Surface:` anchor covers the tracked diff (`git diff HEAD` or `--range`) PLUS the content
of every UNTRACKED changed path — a review's changed set is routinely new files, which `git
diff` never shows; without them the anchor was md5("") on exactly the mandated `--init` moment.

Exit codes: 0 written · 1 the rubric could not run, or the surface is EMPTY (fail closed — an
un-armed artifact, or one anchored to nothing, is the un-reviewed review the gate exists to
refuse) · 2 the target already exists (exclusive create; never overwrite a review in flight).
Fleet-synced (`fabrik_synced_manifest.py`): the commands that call it render box-wide.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REVIEWS_DIR = Path("docs/development/reviews")
_DATED = re.compile(r"^\d{4}-\d{2}-\d{2}-")
# One law, both writers: the gate's own predicate for "a rubric was RUN" — imported from the
# synced gate when it is beside us (every synced repo carries scripts/enforcement/), the literal
# twin otherwise; `tests/test_review_receipt.py` pins the two patterns equal so they cannot drift.
_RUBRIC_RUN_LITERAL = re.compile(r"REVIEW RUBRIC\b[^\n]*generated by review_rubric\.py")
try:
    sys.path.insert(0, str(HERE.parent))
    from scripts.enforcement.check_review_coverage import RUBRIC_RUN  # type: ignore[no-redef]
except Exception:  # noqa: BLE001 — a project without the gate module still gets the literal
    RUBRIC_RUN = _RUBRIC_RUN_LITERAL

# One row per standing recurrence class — the labels carry the exact words
# check_review_coverage.RECURRENCE matches (fail-open · cost/quota/limit · boundary/sentinel/prefix
# · behavior-without-a-test); the two trailing rows are the contract's own classes.
STANDING_ROWS = (
    "Recurrence: fail-open/fail-closed — a swallowed error or an absent check that reads as success",
    "Recurrence: cost/quota accounting — pool units scored, native seats counted, a limit at its edges",
    "Recurrence: boundary/sentinel/prefix — an off-by-one, a sentinel value, a prefix-vs-exact match",
    "Recurrence: behavior-without-a-test — a contract row no test kills (mutation asserted)",
    "Recurrence: denominator on every count — bounded searches state their bound",
    "Recurrence: proxy-as-evidence — the real check EXECUTED, not read",
)


def _git(root: Path, *args: str) -> tuple[int, str]:
    r = subprocess.run(["git", *args], cwd=root, capture_output=True, text=True, check=False)
    return r.returncode, r.stdout


def _git_bytes(root: Path, *args: str) -> tuple[int, bytes]:
    """Raw stdout — the diff is hashed byte-exact (a text decode with `replace` would hash a
    lossy rendering of a binary hunk)."""
    r = subprocess.run(["git", *args], cwd=root, capture_output=True, check=False)
    return r.returncode, r.stdout


def _surface(root: Path, changed: list[str], rng: str | None) -> tuple[str, int]:
    """The anchor line and the byte count it hashes (0 = nothing differs — the caller refuses)."""
    _, head = _git(root, "rev-parse", "HEAD")
    head = head.strip() or "no-git-HEAD"
    if rng:
        # the range's own endpoint, resolved — HEAD alone misdescribes a `A..B` surface
        _, tip = _git(root, "rev-parse", rng.split("..")[-1] or "HEAD")
        head = f"{head}; range tip {tip.strip() or '?'}"
    diff_cmd = ["diff", rng, "--", *changed] if rng else ["diff", "HEAD", "--", *changed]
    rc, blob = _git_bytes(root, *diff_cmd)
    if rc != 0:
        sys.stderr.write(f"review_receipt: `git {' '.join(diff_cmd)}` failed (rc={rc})\n")
        raise SystemExit(1)
    _, untracked_out = _git(root, "ls-files", "--others", "--exclude-standard", "--", *changed)
    untracked = [p for p in untracked_out.splitlines() if p.strip()]
    for p in untracked:
        fp = root / p
        if fp.is_file():
            blob += f"\n--- untracked: {p}\n".encode() + fp.read_bytes()
    digest = hashlib.md5(blob).hexdigest()  # noqa: S324 — a cross-run anchor, not security
    shown = f"git diff {rng or 'HEAD'} -- {' '.join(changed)}"
    extra = f" + {len(untracked)} untracked file(s)" if untracked else ""
    line = f"`git rev-parse HEAD` = {head}; `{shown}`{extra} md5 {digest} ({len(blob)} bytes)"
    return line, len(blob)


def _rubric(root: Path, changed: list[str]) -> str:
    """The hub's extractor, run against `root` — a project root need not carry the script."""
    r = subprocess.run(
        [
            sys.executable,
            str(HERE / "review_rubric.py"),
            "--changed",
            *changed,
            "--project-root",
            str(root),
        ],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if r.returncode != 0 or not RUBRIC_RUN.search(r.stdout):
        sys.stderr.write(
            "review_receipt: review_rubric.py did not produce a rubric the gate recognizes — "
            f"refusing to write an un-armed artifact (rc={r.returncode}): {r.stderr.strip()[:400]}\n"
        )
        raise SystemExit(1)
    return r.stdout.rstrip("\n")


def render(*, title: str, changed: list[str], surface: str, rubric: str, plan: str | None) -> str:
    cmd = f"$ python scripts/review_rubric.py --changed {' '.join(changed)}"
    hunt_rows = "\n".join(
        f"| Hunt: `{p}` — every changed hunk, its enclosing function, its callers | UNCHECKED |"
        for p in changed
    )
    standing = "\n".join(f"| {row} | UNCHECKED |" for row in STANDING_ROWS)
    plan_line = f"**Plan:** `{plan}`\n" if plan else ""
    return f"""# {title}

**Status:** IN-PROGRESS
**Surface:** {surface}
**Command:** /fabrik-review · **Changed:** {", ".join(f"`{p}`" for p in changed)}
{plan_line}
## Coverage Checklist

Rubric invocation (verbatim output — the gate reads the generated header, never a prose mention):

```text
{cmd}
{rubric}
```

| Class | Status |
|---|---|
{hunt_rows}
{standing}

Verdict grammar (the gate refuses anything else): `CLEAN (<the paths/lines hunted>)` — a CLEAN row
must name a path and run past 70 characters · `FIXED r<n> (<what changed>)` · `REFUTED (<the
disproving line>)`. `UNCHECKED` may survive only under a `## BLOCKED` escalation (a finding + 3
failed attempts).

## Pass Ledger

ONE table, one row per pass, counts punctuated (`found: N, fixed: M`) — the gate reads the LAST row
as the exit round and refuses a second ledger group. Minimum two passes; the fixing pass is never
the last; the closing pass re-derives every count and anchor and says so in its Method cell.

| Pass | Finders | Counters | Method |
|---|---|---|---|

Row shapes (quoted here, so the gate does not read them as passes):

```text
| Pass 1 | pool <model×n> + native <model×n> | found: N, fixed: M | citation |
| Pass 2 | pool <model×n> + native <model×n> | found: 0, fixed: 0 | method: re-derivation |
```

## Per-phase verdicts

### Phase 1 — <title>: UNCHECKED

## Gate

`final_gate.py --check --json`, pasted verbatim at the flip (check_convergence reads the fenced
`"status": "success"`):

```json
UNCHECKED — paste the gate output here at the CONVERGED flip
```
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Emit a review-artifact skeleton (--init).")
    ap.add_argument("--init", action="store_true", required=True)
    ap.add_argument("--changed", nargs="+", required=True, help="changed repo-relative paths")
    ap.add_argument(
        "--out", type=Path, help="artifact path (default: reviews/<date>-<scope>-review.md)"
    )
    ap.add_argument("--scope", help="artifact stem slug when --out is not given")
    ap.add_argument("--title", help="H1 (default derived from the scope)")
    ap.add_argument("--plan", help="the plan path this review receipts, if any")
    ap.add_argument(
        "--range", dest="rng", help="A..B diff range for the Surface hash (default HEAD)"
    )
    ap.add_argument("--project-root", type=Path, default=Path.cwd())
    a = ap.parse_args(argv)
    root = a.project_root.resolve()
    if a.out is None:
        if not a.scope:
            ap.error("--out or --scope is required")
        # a plan STEM already starts with its date — never double it
        stem = a.scope if _DATED.match(a.scope) else f"{dt.date.today():%Y-%m-%d}-{a.scope}"
        a.out = root / REVIEWS_DIR / f"{stem}-review.md"
    out = a.out if a.out.is_absolute() else root / a.out
    if out.exists():
        sys.stderr.write(
            f"review_receipt: {out} exists — refusing to overwrite a review in flight\n"
        )
        return 2
    surface, nbytes = _surface(root, a.changed, a.rng)
    if nbytes == 0:
        sys.stderr.write(
            "review_receipt: the surface is EMPTY — nothing differs from "
            f"{a.rng or 'HEAD'} on the changed paths and none is untracked. A review anchored "
            "to nothing reviews nothing: pass --range <base>..HEAD for committed work, or check "
            "the paths.\n"
        )
        return 1
    rubric = _rubric(root, a.changed)
    title = a.title or f"Review — {a.scope or out.stem.removesuffix('-review')}"
    text = render(title=title, changed=a.changed, surface=surface, rubric=rubric, plan=a.plan)
    out.parent.mkdir(parents=True, exist_ok=True)
    try:
        with out.open("x", encoding="utf-8") as fh:  # exclusive: three sessions share this tree
            fh.write(text)
    except FileExistsError:
        sys.stderr.write(f"review_receipt: {out} appeared meanwhile — refusing to overwrite\n")
        return 2
    print(f"wrote {out} ({len(text)} bytes) — Status: IN-PROGRESS; fill every UNCHECKED, then flip")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
